// 全球 GPU 算力平台数据
// 数据来源：各平台官网公开信息
// 最后更新：2025-06-12

var GPU_PLATFORMS = [
  // ==================== 北美 (North America) ====================
  { name: "AWS (Amazon EC2)", country: "美国", region: "北美", website: "https://aws.amazon.com/ec2/instance-types/", pricing_url: "https://aws.amazon.com/ec2/pricing/on-demand/", gpu_types: "NVIDIA H100, H200, A100, L40S, L4, T4", description: "全球最大云服务商，提供 P5/G6/G5 等多种 GPU 实例，支持弹性伸缩和竞价实例，集成 SageMaker 等 AI 服务。" },
  { name: "Microsoft Azure", country: "美国", region: "北美", website: "https://azure.microsoft.com/en-us/products/virtual-machines/gpu/", pricing_url: "https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/", gpu_types: "NVIDIA H100, A100, L40S, L4, T4, AMD MI300X", description: "ND/NC/NV 系列 GPU 虚拟机，深度集成 Azure ML 和 OpenAI 服务，企业级 AI 训练和推理首选之一。" },
  { name: "Google Cloud (GCP)", country: "美国", region: "北美", website: "https://cloud.google.com/compute/docs/gpus", pricing_url: "https://cloud.google.com/compute/gpus-pricing", gpu_types: "NVIDIA H100, A100, L4, T4, P100, TPU v5", description: "A2/G2 GPU 实例，与 Vertex AI 紧密集成，同时提供自研 TPU 用于大规模机器学习训练。" },
  { name: "IBM Cloud", country: "美国", region: "北美", website: "https://www.ibm.com/cloud/gpu", pricing_url: "https://www.ibm.com/cloud/gpu", gpu_types: "NVIDIA A100, T4, V100", description: "裸金属和虚拟 GPU 服务器，Power Systems 支持企业级 AI 工作负载，适合金融和医疗等受监管行业。" },
  { name: "Oracle Cloud Infrastructure", country: "美国", region: "北美", website: "https://www.oracle.com/cloud/compute/gpu/", pricing_url: "https://www.oracle.com/cloud/compute/pricing/", gpu_types: "NVIDIA H100, A100, P100", description: "GPU 裸金属和 VM 实例，低延迟 RDMA 网络，灵活的计算形状，适合机器学习和 VDI 场景。" },
  { name: "DigitalOcean", country: "美国", region: "北美", website: "https://www.digitalocean.com/products/gpu-droplets", pricing_url: "https://www.digitalocean.com/pricing/gpu-droplets", gpu_types: "NVIDIA H100, A100", description: "GPU Droplets 为 AI/ML 工作负载设计，与 Paperspace Gradient 集成，适合开发者和中小团队快速上手。" },
  { name: "Vultr", country: "美国", region: "北美", website: "https://www.vultr.com/products/cloud-gpu/", pricing_url: "https://www.vultr.com/products/cloud-gpu/", gpu_types: "NVIDIA H100, A100, L40S, A40, A16", description: "按需 GPU 云服务器，按小时计费，全球 30+ 数据中心，一键部署 AI 框架。" },
  { name: "Akamai Linode", country: "美国", region: "北美", website: "https://www.linode.com/products/gpu/", pricing_url: "https://www.linode.com/pricing/#compute-gpu", gpu_types: "NVIDIA Quadro RTX 4000, RTX 6000", description: "简单易用的 GPU 实例，可预测的定价，全球多区域部署，适合开发者和小型项目。" },
  { name: "Paperspace (Core/Gradient)", country: "美国", region: "北美", website: "https://www.paperspace.com/", pricing_url: "https://www.paperspace.com/pricing", gpu_types: "NVIDIA H100, A100, A6000, RTX 4000", description: "专注于 GPU 加速计算的云平台，提供 Gradient 笔记本和 MLOps 工具，支持团队协作和版本管理。" },
  { name: "CoreWeave", country: "美国", region: "北美", website: "https://www.coreweave.com/", pricing_url: "https://www.coreweave.com/pricing", gpu_types: "NVIDIA H100, A100, L40S, RTX A6000", description: "Kubernetes 原生的高性能 GPU 云，大规模集群用于 LLM 训练、VFX 渲染和批量推理，增长最快的 GPU 云之一。" },
  { name: "Lambda Labs", country: "美国", region: "北美", website: "https://lambda.ai/", pricing_url: "https://lambda.ai/pricing", gpu_types: "NVIDIA H100, H200, A100, GH200", description: "专注深度学习的 GPU 云，提供预装框架的集群，强调简洁性和速度，同时销售 GPU 工作站和服务器。" },
  { name: "RunPod", country: "美国", region: "北美", website: "https://www.runpod.io/", pricing_url: "https://www.runpod.io/pricing", gpu_types: "NVIDIA H100, A100, RTX 4090, 3090, A6000", description: "无服务器 GPU 平台，按秒计费，适合 LLM 微调、Stable Diffusion 和自定义 API 部署，性价比较高。" },
  { name: "Vast.ai", country: "美国", region: "北美", website: "https://vast.ai/", pricing_url: "https://vast.ai/pricing", gpu_types: "NVIDIA H100, A100, RTX 4090, 3090, 多种消费级", description: "去中心化 GPU 租赁市场，连接算力提供者和需求方，动态定价，通常提供全球最低的 GPU 小时价格。" },
  { name: "TensorDock", country: "美国", region: "北美", website: "https://www.tensordock.com/", pricing_url: "https://www.tensordock.com/cloud-gpus.html", gpu_types: "NVIDIA H100, A100, RTX 4090, 6000 Ada", description: "GPU 市场平台，提供裸金属实例即时部署，在学术界和 AI 原型开发社区中较受欢迎。" },
  { name: "FluidStack", country: "英国/美国", region: "北美", website: "https://www.fluidstack.io/", pricing_url: "https://www.fluidstack.io/pricing", gpu_types: "NVIDIA H100, A100, A6000", description: "全球 GPU 集群聚合平台，连接闲置数据中心 GPU，支持 AI 训练和渲染，液冷服务器。" },
  { name: "Massed Compute", country: "美国", region: "北美", website: "https://www.massedcompute.com/", pricing_url: "https://www.massedcompute.com/pricing", gpu_types: "NVIDIA H100, A100, A6000, RTX 6000 Ada", description: "按需裸金属 GPU 租赁，针对 ML 训练优化，有竞争力的每小时定价和大内存配置。" },
  { name: "Bizon", country: "美国", region: "北美", website: "https://bizon.ai/", pricing_url: "https://bizon.ai/pricing", gpu_types: "NVIDIA H100, A100, RTX 6000 Ada", description: "液冷 GPU 云和工作站，为深度学习优化，提供按需 A100 集群和预装框架环境。" },
  { name: "PhoenixNAP", country: "美国", region: "北美", website: "https://phoenixnap.com/gpu-hosting", pricing_url: "https://phoenixnap.com/gpu-hosting", gpu_types: "NVIDIA A100, V100, RTX 系列, AMD 系列", description: "专用 GPU 托管服务，裸金属和虚拟服务器，支持深度学习、VDI 和区块链工作负载。" },
  { name: "Equinix Metal", country: "美国", region: "北美", website: "https://metal.equinix.com/product/servers/", pricing_url: "https://metal.equinix.com/developers/docs/servers/server-specs/", gpu_types: "NVIDIA A100, T4", description: "自动化裸金属 GPU 服务器，部署在全球 Equinix 数据中心，适合混合云和低延迟应用。" },
  { name: "Hivelocity", country: "美国", region: "北美", website: "https://www.hivelocity.net/products/gpu-servers/", pricing_url: "https://www.hivelocity.net/products/gpu-servers/", gpu_types: "NVIDIA H100, A100, RTX 系列", description: "即时部署 GPU 裸金属，40+ 数据中心可选，按需计费，支持 CUDA/OpenCL。" },
  { name: "QuadraNet", country: "美国", region: "北美", website: "https://quadranet.com/gpu-dedicated-servers", pricing_url: "https://quadranet.com/gpu-dedicated-servers", gpu_types: "NVIDIA RTX 系列, GTX 系列", description: "洛杉矶 GPU 主机服务商，含 DDoS 防护，适用于深度学习、VDI 和加密货币挖矿。" },
  { name: "Psychz", country: "美国", region: "北美", website: "https://www.psychz.net/", pricing_url: "https://www.psychz.net/", gpu_types: "NVIDIA RTX 系列, GTX 系列", description: "高性价比 GPU 服务器，高带宽端口，在美国和亚洲有节点，适合自由职业者和小型 AI 实验室。" },
  { name: "TurnKey Internet", country: "美国", region: "北美", website: "https://turnkeyinternet.net/gpu-dedicated-server/", pricing_url: "https://turnkeyinternet.net/gpu-dedicated-server/", gpu_types: "NVIDIA RTX 系列, Tesla 系列", description: "纽约绿色数据中心 GPU 产品，定制化硬件配置，适合 AI 和视觉效果渲染。" },
  { name: "Dedicated.com", country: "美国", region: "北美", website: "https://dedicated.com/dedicated-servers/gpu", pricing_url: "https://dedicated.com/dedicated-servers/gpu", gpu_types: "NVIDIA RTX 系列, AMD 系列", description: "托管 GPU 服务器，注重低成本入门级配置，适合 GPU 计算初学者和小型项目。" },
  { name: "Rackspace Technology", country: "美国", region: "北美", website: "https://www.rackspace.com/cloud/gpu", pricing_url: "https://www.rackspace.com/cloud/gpu", gpu_types: "NVIDIA A100, V100, T4", description: "托管 GPU 解决方案，可部署在专用硬件或公有云上，适合 AI/ML、VDI 和高强度计算应用。" },
  { name: "NVIDIA DGX Cloud", country: "美国", region: "北美", website: "https://www.nvidia.com/en-us/data-center/dgx-cloud/", pricing_url: "https://www.nvidia.com/en-us/data-center/dgx-cloud/", gpu_types: "NVIDIA H100, H200, GH200 (DGX 平台)", description: "NVIDIA 自营全托管 AI 超级计算云，DGX 基础设施，专为基础模型大规模训练设计，与各大云合作。" },
  { name: "Cirrascale", country: "美国", region: "北美", website: "https://www.cirrascale.com/cloud-services/", pricing_url: "https://www.cirrascale.com/cloud-services/", gpu_types: "NVIDIA H100, A100, A800", description: "深度学习云服务，大规模 GPU 集群，针对自动驾驶训练和数据分析优化。" },
  { name: "SabrePC", country: "美国", region: "北美", website: "https://www.sabrepc.com/hpc-cloud", pricing_url: "https://www.sabrepc.com/hpc-cloud", gpu_types: "NVIDIA A100, RTX A6000, 6000 Ada", description: "工作站级 GPU 云，可配置裸金属节点，服务工程、AI 和图形渲染领域。" },
  { name: "Applied Digital", country: "美国", region: "北美", website: "https://www.applieddigital.com/", pricing_url: "https://www.applieddigital.com/", gpu_types: "NVIDIA H100, A100", description: "高密度 GPU 托管和云平台，支持加密挖矿和 HPC，提供液冷选项。" },
  { name: "Rescale", country: "美国", region: "北美", website: "https://www.rescale.com/", pricing_url: "https://www.rescale.com/pricing/", gpu_types: "NVIDIA A100, V100, 多 GPU 类型", description: "云 HPC 平台，多云端 GPU 访问，服务航空航天、汽车和生命科学领域的仿真计算。" },
  { name: "Databricks", country: "美国", region: "北美", website: "https://www.databricks.com/", pricing_url: "https://www.databricks.com/product/pricing", gpu_types: "NVIDIA T4, A10G, A100 (通过云伙伴)", description: "统一分析平台，GPU 集群支持 ML、深度学习和 LLM 微调，基于 Apache Spark 构建。" },
  { name: "Anyscale", country: "美国", region: "北美", website: "https://www.anyscale.com/", pricing_url: "https://www.anyscale.com/pricing", gpu_types: "NVIDIA A100, T4 (通过 AWS/GCP)", description: "基于 Ray 的 ML 平台，GPU 加速的分布式计算，部署和扩展 ML 工作负载。" },
  { name: "Saturn Cloud", country: "美国", region: "北美", website: "https://saturncloud.io/", pricing_url: "https://saturncloud.io/pricing/", gpu_types: "NVIDIA T4, A10G, A100", description: "数据科学云平台，提供 GPU 和 Dask 集群，支持 Python/R 团队协作和生产 ML。" },
  { name: "Coiled", country: "美国", region: "北美", website: "https://www.coiled.io/", pricing_url: "https://www.coiled.io/pricing", gpu_types: "NVIDIA GPU (通过 AWS/GCP)", description: "托管 Dask 服务，GPU 支持的 Worker 节点，自动扩展用于并行计算和分布式训练。" },
  { name: "Modal", country: "美国", region: "北美", website: "https://modal.com/", pricing_url: "https://modal.com/pricing", gpu_types: "NVIDIA H100, A100, T4, L40S", description: "无服务器 Python 云，GPU 自动伸缩，按秒计费，适合推理 API、批量作业和定时任务。" },
  { name: "Replicate", country: "美国", region: "北美", website: "https://replicate.com/", pricing_url: "https://replicate.com/pricing", gpu_types: "NVIDIA H100, A100, T4, A40", description: "ML 模型 API 云平台，GPU 后端支持图像生成、语音转写和 LLM 推理，按使用量计费。" },
  { name: "Fireworks.ai", country: "美国", region: "北美", website: "https://fireworks.ai/", pricing_url: "https://fireworks.ai/pricing", gpu_types: "NVIDIA H100, A100, L40S", description: "生成式 AI 推理平台，优化的 GPU 运行时，高吞吐低延迟，专注 LLM 和扩散模型服务。" },
  { name: "Together AI", country: "美国", region: "北美", website: "https://www.together.ai/", pricing_url: "https://www.together.ai/pricing", gpu_types: "NVIDIA H100, A100", description: "开源 AI 云平台，大规模 GPU 集群用于训练和微调 LLaMA、Stable Diffusion 等模型。" },
  { name: "OctoML (OctoAI)", country: "美国", region: "北美", website: "https://octoml.ai/", pricing_url: "https://octoml.ai/pricing/", gpu_types: "NVIDIA A100, T4, L4", description: "ML 加速平台，自动化模型优化和 GPU 部署，提升推理性能并降低成本，已被 NVIDIA 收购。" },
  { name: "BentoML (BentoCloud)", country: "美国", region: "北美", website: "https://www.bentoml.com/", pricing_url: "https://www.bentoml.com/pricing", gpu_types: "NVIDIA A100, T4, L4", description: "无服务器推理平台，BentoML 模型自动伸缩 GPU 资源，按请求计费。" },
  { name: "Cerebrium", country: "南非", region: "其他", website: "https://www.cerebrium.ai/", pricing_url: "https://www.cerebrium.ai/pricing", gpu_types: "NVIDIA A100, T4, L4", description: "无服务器 GPU 平台，支持模型部署、微调和监控，优化冷启动。" },
  { name: "Monster API", country: "美国", region: "北美", website: "https://monsterapi.ai/", pricing_url: "https://monsterapi.ai/pricing", gpu_types: "NVIDIA H100, A100, RTX 系列", description: "API 优先的 GPU 云，支持生成式 AI 模型微调和部署，按 token 计费和专用实例。" },
  { name: "Mystic AI", country: "英国", region: "欧洲", website: "https://mystic.ai/", pricing_url: "https://mystic.ai/pricing", gpu_types: "NVIDIA H100, A100, T4", description: "无服务器 GPU 推理，pip 部署模型，为定制 ML 流水线的快速迭代而设计。" },
  { name: "Deepnote", country: "美国", region: "北美", website: "https://deepnote.com/", pricing_url: "https://deepnote.com/pricing", gpu_types: "NVIDIA T4, L4", description: "协作数据笔记本，GPU 加速 Python/SQL，适合团队 ML 探索和分析。" },
  { name: "CodeOcean", country: "美国", region: "北美", website: "https://codeocean.com/", pricing_url: "https://codeocean.com/pricing", gpu_types: "NVIDIA GPU (计算胶囊)", description: "可复现研究云平台，GPU 胶囊支持科学家共享和运行计算密集型代码。" },
  { name: "Google Colab", country: "美国", region: "北美", website: "https://colab.research.google.com/", pricing_url: "https://colab.research.google.com/signup", gpu_types: "NVIDIA T4, L4, P100, TPU v2", description: "免费和订阅制 GPU/TPU 笔记本，非常适合教育、原型开发和小模型训练，入门门槛最低。" },
  { name: "Hugging Face (Inference Endpoints)", country: "美国/法国", region: "北美", website: "https://huggingface.co/inference-endpoints", pricing_url: "https://huggingface.co/pricing#endpoints", gpu_types: "NVIDIA A100, T4, L4, A10G", description: "托管 GPU 推理服务，Hugging Face 模型一键部署，自动伸缩，按秒计费。" },
  { name: "Salad", country: "美国", region: "北美", website: "https://salad.com/", pricing_url: "https://salad.com/pricing", gpu_types: "NVIDIA RTX 3090, 4090, 多种消费级 GPU", description: "分布式 GPU 云，利用闲置消费级 GPU 进行推理，适合生成式 AI 任务如图像生成。" },
  { name: "Akash Network", country: "美国", region: "北美", website: "https://akash.network/", pricing_url: "https://akash.network/pricing/", gpu_types: "NVIDIA A100, RTX 系列, 多种 GPU", description: "DePIN 去中心化云计算市场，反向拍卖定价，无需许可的 GPU 容器部署。" },
  { name: "Render Network", country: "美国", region: "北美", website: "https://rendertoken.com/", pricing_url: "https://rendertoken.com/", gpu_types: "NVIDIA RTX 系列, 多种 GPU", description: "区块链 GPU 渲染生态，连接艺术家与闲置 GPU 提供者，基于 OctaneRender 引擎。" },
  { name: "Mining Rig Rentals", country: "美国", region: "北美", website: "https://www.miningrigrentals.com/", pricing_url: "https://www.miningrigrentals.com/", gpu_types: "NVIDIA/AMD 挖矿 GPU", description: "P2P 矿机租赁平台，支持短期 GPU 算力租赁，面向加密货币挖矿和哈希计算。" },
  { name: "Q Blocks", country: "美国", region: "北美", website: "https://qblocks.cloud/", pricing_url: "https://qblocks.cloud/", gpu_types: "NVIDIA A100, RTX 系列", description: "去中心化 GPU 云，聚合数据中心和加密矿工算力，聚焦 Web3 AI 领域。" },
  { name: "Golem Network", country: "瑞士", region: "欧洲", website: "https://www.golem.network/", pricing_url: "https://www.golem.network/", gpu_types: "多种消费级 GPU (P2P)", description: "P2P 去中心化算力网络，用户可出租 GPU 处理 CGI 渲染和计算任务，用 GLM 代币结算。" },
  { name: "NiceHash", country: "斯洛文尼亚", region: "欧洲", website: "https://www.nicehash.com/", pricing_url: "https://www.nicehash.com/pricing", gpu_types: "NVIDIA/AMD 挖矿 GPU", description: "算力市场，用户可以购买或出售 GPU 算力用于加密货币挖矿和其他计算工作负载。" },

  // ==================== 欧洲 (Europe) ====================
  { name: "OVHcloud", country: "法国", region: "欧洲", website: "https://www.ovhcloud.com/en/public-cloud/gpu/", pricing_url: "https://www.ovhcloud.com/en/public-cloud/prices/", gpu_types: "NVIDIA H100, A100, L40S, T4", description: "欧洲最大云服务商，提供 GPU 实例，注重数据主权和可预测成本，适合有合规需求的欧洲客户。" },
  { name: "Scaleway", country: "法国", region: "欧洲", website: "https://www.scaleway.com/en/gpu-instances/", pricing_url: "https://www.scaleway.com/en/gpu-instances/", gpu_types: "NVIDIA H100, L40S, L4", description: "法国云服务商，REWORK GPU 实例，灵活计费，环保数据中心，适合模型训练和渲染。" },
  { name: "Hetzner", country: "德国", region: "欧洲", website: "https://www.hetzner.com/cloud/gpu/", pricing_url: "https://www.hetzner.com/cloud/gpu/", gpu_types: "NVIDIA A100, RTX 系列, Tesla 系列", description: "德国高性价比 GPU 云，数据中心在德国/芬兰，以极具竞争力的价格和稳定服务著称。" },
  { name: "T-Systems (Open Telekom Cloud)", country: "德国", region: "欧洲", website: "https://open-telekom-cloud.com/en/", pricing_url: "https://open-telekom-cloud.com/en/pricing/", gpu_types: "NVIDIA A100, T4, V100", description: "欧洲主权云，严格的 GDPR 合规，GPU 实例用于 AI 和 HPC，德国电信旗下。" },
  { name: "Exoscale", country: "瑞士", region: "欧洲", website: "https://www.exoscale.com/gpu/", pricing_url: "https://www.exoscale.com/gpu/", gpu_types: "NVIDIA A100, T4, V100", description: "瑞士云服务商，GPU 实例用于渲染、AI 推理和 VDI，符合欧洲数据法规要求。" },
  { name: "G-Core Labs", country: "卢森堡", region: "欧洲", website: "https://gcore.com/cloud/gpu-cloud", pricing_url: "https://gcore.com/cloud/gpu-cloud", gpu_types: "NVIDIA H100, A100, L40S", description: "全球边缘 GPU 云，为游戏、媒体分发和实时 ML 推理优化，全球覆盖广泛。" },
  { name: "UpCloud", country: "芬兰", region: "欧洲", website: "https://upcloud.com/gpu/", pricing_url: "https://upcloud.com/pricing/", gpu_types: "NVIDIA A100, T4, L4", description: "高性能 GPU 计算，MaxIOPS 存储，适合渲染、VDI 和轻量级模型训练。" },
  { name: "DataCrunch", country: "芬兰", region: "欧洲", website: "https://verda.com/", pricing_url: "https://verda.com/pricing", gpu_types: "NVIDIA H100, A100, A6000", description: "欧洲 GPU 云（已更名为 Verda），低成本的 A100/H100 实例，专注 ML 训练和数据分析，性价比突出。" },
  { name: "Genesis Cloud", country: "冰岛/德国", region: "欧洲", website: "https://genesiscloud.com/", pricing_url: "https://genesiscloud.com/pricing", gpu_types: "NVIDIA A100, V100, RTX 系列", description: "绿色 GPU 云，100% 可再生能源驱动，提供经济实惠的 GPU 实例用于神经网络训练。" },
  { name: "NexGen Cloud", country: "英国", region: "欧洲", website: "https://www.nexgencloud.com/", pricing_url: "https://www.nexgencloud.com/pricing", gpu_types: "NVIDIA H100, L40S, A100", description: "可持续 GPU 云，水力发电驱动，提供 H100 和 L40S 用于 AI 和视觉特效。" },
  { name: "Cherry Servers", country: "立陶宛", region: "欧洲", website: "https://www.cherryservers.com/gpu-servers", pricing_url: "https://www.cherryservers.com/pricing/gpu-servers", gpu_types: "NVIDIA A100, RTX 系列", description: "裸金属 GPU 服务器，按需或预留，可定制配置，全球 BGP 路由。" },
  { name: "Leaseweb", country: "荷兰", region: "欧洲", website: "https://www.leaseweb.com/en/dedicated-servers/gpu", pricing_url: "https://www.leaseweb.com/en/dedicated-servers/gpu", gpu_types: "NVIDIA A100, RTX 系列, Tesla 系列", description: "欧洲老牌主机商，托管和非托管 GPU 服务器，覆盖欧洲、美国和亚洲节点。" },
  { name: "21Cloud", country: "荷兰", region: "欧洲", website: "https://www.21cloud.com/cloud/gpu-cloud", pricing_url: "https://www.21cloud.com/cloud/gpu-cloud", gpu_types: "NVIDIA A100, V100, RTX 系列", description: "荷兰 GPU 云和托管服务，专注合规、HPC 和媒体制作。" },
  { name: "Hostkey", country: "荷兰", region: "欧洲", website: "https://www.hostkey.com/gpu-servers", pricing_url: "https://www.hostkey.com/gpu-servers", gpu_types: "NVIDIA A100, RTX 系列, Tesla 系列", description: "即开 GPU 服务器，欧洲/美国节点，支持深度学习框架和虚拟工作站部署。" },
  { name: "LeaderGPU", country: "法国", region: "欧洲", website: "https://www.leadergpu.com/", pricing_url: "https://www.leadergpu.com/pricing", gpu_types: "NVIDIA RTX 系列, Tesla 系列, Quadro", description: "专用 GPU 服务器，欧洲/美国部署，统一定价，面向渲染、CGI 和 ML 开发者。" },
  { name: "Aruba Cloud", country: "意大利", region: "欧洲", website: "https://www.arubacloud.com/", pricing_url: "https://www.arubacloud.com/cloud-pricing.aspx", gpu_types: "NVIDIA T4, V100", description: "意大利云服务商，GPU 选项适合小型企业，提供 VPS 和专用 GPU 服务器。" },
  { name: "Cudo Compute", country: "英国", region: "欧洲", website: "https://www.cudocompute.com/", pricing_url: "https://www.cudocompute.com/products/virtual-machines", gpu_types: "NVIDIA H100, A100, RTX 系列", description: "去中心化云市场，利用闲置 GPU 容量，适合突发性渲染、AI 和区块链工作负载。" },
  { name: "ServerMania", country: "加拿大", region: "北美", website: "https://www.servermania.com/gpu-servers.htm", pricing_url: "https://www.servermania.com/gpu-servers.htm", gpu_types: "NVIDIA A100, RTX 系列", description: "可定制 GPU 专用服务器，10 Gbps 网络，常用于 AI 初创公司和渲染农场。" },
  { name: "DataPacket", country: "美国/英国", region: "北美", website: "https://www.datapacket.com/gpu-hosting", pricing_url: "https://www.datapacket.com/gpu-hosting", gpu_types: "NVIDIA RTX 系列, Tesla 系列", description: "裸金属 GPU 服务器，全球 20+ 节点，不限流量带宽，适合视频编码和 ML。" },
  { name: "Servers.com", country: "荷兰", region: "欧洲", website: "https://www.servers.com/gpu-servers/", pricing_url: "https://www.servers.com/gpu-servers/", gpu_types: "NVIDIA A100, RTX 系列", description: "全球裸金属 GPU 实例，灵活按小时/月计费，常用于游戏开发和科研计算。" },

  // ==================== 亚太 - 中国 (Asia Pacific - China) ====================
  { name: "阿里云 (Alibaba Cloud)", country: "中国", region: "亚太", website: "https://www.alibabacloud.com/product/ecs/gpu", pricing_url: "https://www.alibabacloud.com/product/ecs/pricing", gpu_types: "NVIDIA H100, A100, V100, T4, PAI 平台", description: "中国最大云服务商，GPU 加速 ECS 实例和 PAI 平台，覆盖亚洲广泛区域，支持弹性计费。" },
  { name: "腾讯云 (Tencent Cloud)", country: "中国", region: "亚太", website: "https://intl.cloud.tencent.com/product/gpu", pricing_url: "https://buy.cloud.tencent.com/price/cvm/overview", gpu_types: "NVIDIA H100, A100, T4, V100 (GN/GT 系列)", description: "提供 GN 和 GT 系列 GPU 实例，针对模型训练、转码和视频 AI 优化，在亚太地区覆盖广泛。" },
  { name: "华为云 (Huawei Cloud)", country: "中国", region: "亚太", website: "https://www.huaweicloud.com/intl/en-us/product/gpu.html", pricing_url: "https://www.huaweicloud.com/intl/en-us/pricing.html#/ecs", gpu_types: "NVIDIA H100, A100, 昇腾 Ascend 系列", description: "昇腾和 NVIDIA GPU 云服务器，与 ModelArts 深度集成，提供端到端 AI 开发部署平台。" },
  { name: "百度智能云 (Baidu AI Cloud)", country: "中国", region: "亚太", website: "https://cloud.baidu.com/product/gpu.html", pricing_url: "https://cloud.baidu.com/product/gpu.html", gpu_types: "NVIDIA A100, V100, T4, 昆仑芯片", description: "GPU 裸金属和虚拟实例，自研昆仑 AI 芯片，通过 ABC Stack 提供 AI 训练和 HPC 服务。" },
  { name: "火山引擎 (Volcengine)", country: "中国", region: "亚太", website: "https://www.volcengine.com/product/gpu", pricing_url: "https://www.volcengine.com/product/gpu", gpu_types: "NVIDIA H100, A100, A800, L40S", description: "字节跳动旗下云平台，先进 GPU 实例用于 LLM 训练/推理和内容 AI，弹性伸缩。" },
  { name: "京东云 (JD Cloud)", country: "中国", region: "亚太", website: "https://www.jdcloud.com/cn/public/compute/gpu", pricing_url: "https://www.jdcloud.com/cn/public/compute/gpu", gpu_types: "NVIDIA T4, V100, A100", description: "GPU VM 和物理服务器，服务电商 AI、图像识别和云渲染场景。" },
  { name: "金山云 (Kingsoft Cloud)", country: "中国", region: "亚太", website: "https://www.ksyun.com/post/product/KEC.html", pricing_url: "https://www.ksyun.com/post/product/KEC.html", gpu_types: "NVIDIA T4, V100, A10", description: "KEC GPU 系列支持训练和推理，可突发或预留实例，在游戏和媒体领域应用广泛。" },
  { name: "UCloud", country: "中国", region: "亚太", website: "https://www.ucloud.cn/site/product/uhost.html", pricing_url: "https://www.ucloud.cn/site/product/uhost.html", gpu_types: "NVIDIA T4, V100, A100", description: "GPU 云主机和裸金属服务器，按量付费和包月可选，服务 AI 创业公司，覆盖中国和东南亚。" },
  { name: "青云 (QingCloud)", country: "中国", region: "亚太", website: "https://www.qingcloud.com/products/gpu_server/", pricing_url: "https://www.qingcloud.com/products/gpu_server/", gpu_types: "NVIDIA T4, V100, A100", description: "GPU 计算实例，灵活 SDN 网络，适合深度学习、HPC 和桌面虚拟化。" },
  { name: "中国移动云 (China Mobile Cloud)", country: "中国", region: "亚太", website: "https://ecloud.10086.cn/home/product-introduction/gpu", pricing_url: "https://ecloud.10086.cn/home/product-introduction/gpu", gpu_types: "NVIDIA T4, V100, A100", description: "运营商云，GPU 虚拟机和容器实例，支持边缘 AI 推理和数据中心训练。" },
  { name: "天翼云 (China Telecom e-Surfing Cloud)", country: "中国", region: "亚太", website: "https://www.ctyun.cn/product/gpu", pricing_url: "https://www.ctyun.cn/product/gpu", gpu_types: "NVIDIA T4, V100, A100", description: "中国电信云品牌，GPU 实例部署于全国基础设施，面向视频分析和 AI 训练。" },
  { name: "联通云 (China Unicom Cloud)", country: "中国", region: "亚太", website: "https://www.cucloud.cn/product/gpu.html", pricing_url: "https://www.cucloud.cn/product/gpu.html", gpu_types: "NVIDIA T4, V100, A100", description: "联通云 GPU 服务器，结合联通 5G 和边缘网络，低延迟推理服务。" },
  { name: "浪潮云 (Inspur Cloud)", country: "中国", region: "亚太", website: "https://cloud.inspur.com/product/gpu/", pricing_url: "https://cloud.inspur.com/product/gpu/", gpu_types: "NVIDIA A100, V100, T4", description: "浪潮集团旗下 GPU 云，HPC 传统优势，专注科学计算、AI 建模和工程仿真。" },
  { name: "矩池云 (Matpool)", country: "中国", region: "亚太", website: "https://matpool.com/", pricing_url: "https://matpool.com/pricing", gpu_types: "NVIDIA RTX 3090, A100, V100, RTX 4090", description: "国内 GPU 租赁平台，即时短期实例，在高校学生和 AI 竞赛参与者中很受欢迎。" },
  { name: "AutoDL", country: "中国", region: "亚太", website: "https://www.autodl.com", pricing_url: "https://www.autodl.com/price", gpu_types: "NVIDIA H100, A100, RTX 4090, RTX 3090, V100, T4, L20, A40", description: "国内领先 GPU 租赁平台，按小时计费，预装深度学习环境一键部署，深受高校和 AI 开发者青睐。" },
  { name: "并行科技 (Paratera)", country: "中国", region: "亚太", website: "https://www.paratera.com/", pricing_url: "https://www.paratera.com/", gpu_types: "NVIDIA A100, V100, 多种 GPU", description: "高性能计算云，可扩展 GPU 节点，服务高校和工业界仿真、AI 和生命科学。" },
  { name: "极视角 (Video++ AI Cloud)", country: "中国", region: "亚太", website: "https://www.videopuzzles.com/", pricing_url: "https://www.videopuzzles.com/", gpu_types: "NVIDIA T4, V100, A100", description: "AI 视频识别 GPU 云，中国视频分析和内容理解领域，提供易用的 Web 控制台。" },

  // ==================== 亚太 - 日本 (Asia Pacific - Japan) ====================
  { name: "Sakura Internet", country: "日本", region: "亚太", website: "https://www.sakura.ad.jp/services/cloud/gpu/", pricing_url: "https://www.sakura.ad.jp/services/cloud/gpu/", gpu_types: "NVIDIA A100, T4, V100", description: "日本云服务商，简单 GPU 实例，被日本国内初创公司和教育机构广泛使用。" },
  { name: "IIJ GIO", country: "日本", region: "亚太", website: "https://www.iij.ad.jp/biz/gio/", pricing_url: "https://www.iij.ad.jp/biz/gio/", gpu_types: "NVIDIA T4, V100, A100", description: "日本互联网骨干运营商 IIJ 旗下 GPU 云主机，面向企业渲染和数据分析。" },

  // ==================== 亚太 - 韩国 (Asia Pacific - South Korea) ====================
  { name: "KT Cloud", country: "韩国", region: "亚太", website: "https://cloud.kt.com/", pricing_url: "https://cloud.kt.com/", gpu_types: "NVIDIA T4, V100, A100", description: "韩国电信云平台，GPU 实例用于 AI、媒体和游戏，基于韩国本土数据中心。" },
  { name: "Naver Cloud", country: "韩国", region: "亚太", website: "https://www.ncloud.com/product/compute/gpu", pricing_url: "https://www.ncloud.com/product/compute/gpu", gpu_types: "NVIDIA T4, V100, A100, H100", description: "韩国 Naver 旗下云服务，GPU 服务器用于深度学习和 VDI，与 Naver AI 服务集成。" },

  // ==================== 亚太 - 其他 (Asia Pacific - Others) ====================
  { name: "Yandex Cloud", country: "俄罗斯", region: "亚太", website: "https://cloud.yandex.com/en/services/compute", pricing_url: "https://cloud.yandex.com/en/services/compute#pricing", gpu_types: "NVIDIA A100, T4, V100", description: "俄罗斯最大云平台，GPU 虚拟机和托管 Kubernetes 节点，适合 ML 和视频处理。" },
  { name: "JarvisLabs", country: "印度", region: "亚太", website: "https://jarvislabs.ai/", pricing_url: "https://jarvislabs.ai/pricing/", gpu_types: "NVIDIA A100, V100, RTX 6000 Ada", description: "简化的 GPU 云平台，预置深度学习环境，按量付费，适合个人开发者和教学使用。" },

  // ==================== 中国超算中心 (China Supercomputing Centers) ====================
  { name: "鹏城云脑 (Pengcheng Cloud Brain)", country: "中国", region: "亚太", website: "https://cloudbrain.pcl.ac.cn/", pricing_url: "https://cloudbrain.pcl.ac.cn/", gpu_types: "华为昇腾 NPU 集群", description: "深圳国家级 AI 计算平台，大规模 NPU 资源用于 AI 科研，鹏城实验室运营。" },
  { name: "之江实验室 (Zhejiang Lab)", country: "中国", region: "亚太", website: "https://www.zhejianglab.com/", pricing_url: "https://www.zhejianglab.com/", gpu_types: "NVIDIA A100, 多种 GPU", description: "浙江省政府与高校合作的研究型云平台，GPU 集群支持 AI、机器人和智慧社会应用。" },
  { name: "国家超算深圳中心 (NSCC-SZ)", country: "中国", region: "亚太", website: "http://www.nsccsz.gov.cn/", pricing_url: "http://www.nsccsz.gov.cn/", gpu_types: "NVIDIA A100, V100", description: "公共超算中心，GPU AI 计算服务，面向政府和学术界开放。" },
  { name: "国家超算广州中心 (NSCC-GZ)", country: "中国", region: "亚太", website: "https://www.nscc-gz.cn/", pricing_url: "https://www.nscc-gz.cn/", gpu_types: "NVIDIA A100, V100, 国产加速卡", description: "天河二号/天河星逸所在地，GPU 集群用于气象、基因组和工业 CAE。" },
  { name: "国家超算天津中心 (NSCC-TJ)", country: "中国", region: "亚太", website: "https://nscc-tj.cn/", pricing_url: "https://nscc-tj.cn/", gpu_types: "NVIDIA A100, 国产加速器", description: "天河系列超算设施，GPU 计算节点服务科学研究和创新项目。" },
  { name: "国家超算无锡中心 (NSCC-WX)", country: "中国", region: "亚太", website: "http://www.nsccwx.cn/", pricing_url: "http://www.nsccwx.cn/", gpu_types: "NVIDIA GPU, 神威加速器", description: "神威太湖之光所在地，GPU 节点用于 AI 和地球科学仿真，国产处理器。" },
  { name: "上海超算中心 (SSCS)", country: "中国", region: "亚太", website: "https://www.sscs.cn/", pricing_url: "https://www.sscs.cn/", gpu_types: "NVIDIA A100, V100, 多种加速卡", description: "上海市级 HPC 中心，GPU 分区用于药物发现、汽车设计和金融建模。" },
  { name: "北京超级云计算中心 (BLSC)", country: "中国", region: "亚太", website: "https://www.blsc.cn/", pricing_url: "https://www.blsc.cn/", gpu_types: "NVIDIA A100, V100, T4", description: "云化超算中心，弹性 GPU 资源用于深度学习和科学计算。" },
  { name: "合肥先进计算中心 (Hefei ACC)", country: "中国", region: "亚太", website: "http://www.hpcc.ustc.edu.cn/", pricing_url: "http://www.hpcc.ustc.edu.cn/", gpu_types: "NVIDIA A100, V100", description: "中科大旗下 GPU 集群，用于量子化学、AI 和材料仿真。" }
];

// 按名称排序
GPU_PLATFORMS.sort((a, b) => a.name.localeCompare(b.name, 'zh'));

// 导出以供 HTML 使用（浏览器环境直接使用全局变量）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = GPU_PLATFORMS;
}
