// GPU算力期货新闻 v3
// Generated: 2026-06-13T04:45:14Z
var NEWS_FETCHED_AT = "2026-06-13T04:45:14Z";
var GPU_NEWS = [
  {
    "title": "Place Your Bets – Futures Traders Are About To See The Launch Of AI Semiconductor Contracts",
    "source": "Benzinga",
    "source_url": "https://www.benzinga.com/news/topics/26/05/52762722/place-your-bets-futures-traders-are-about-to-see-the-launch-of-ai-semiconductor-contracts",
    "url": "https://www.benzinga.com/news/topics/26/05/52762722/place-your-bets-futures-traders-are-about-to-see-the-launch-of-ai-semiconductor-contracts",
    "published": "2026-05-13",
    "summary": "Place Your Bets – Futures Traders Are About To See The Launch Of AI Semiconductor Contracts - CME Group ( - BenzingaBenzingaEspañaItalia대한민국日本FrançaisMy AccountBenzinga EdgeBenzinga ResearchBenzinga ProLoginGet Benzinga Pro Data & APIsEventsPremarketAdvertiseContributeEspañaItalia대한민국日本FrançaisLoginRegisterBenzingaPremium Services Financial News Financial NewsLarge Cap StocksSmall-Cap StocksInside",
    "full_text": "Place Your Bets – Futures Traders Are About To See The Launch Of AI Semiconductor Contracts - CME Group ( - BenzingaBenzingaEspañaItalia대한민국日本FrançaisMy AccountBenzinga EdgeBenzinga ResearchBenzinga ProLoginGet Benzinga Pro Data & APIsEventsPremarketAdvertiseContributeEspañaItalia대한민국日本FrançaisLoginRegisterBenzingaPremium Services Financial News Financial NewsLarge Cap StocksSmall-Cap StocksInsider TradesEarningsTechnologyAI NewsPersonal FinanceETF NewsCrypto NewsDividend NewsLatest RumorsLatest Offerings NewsInvestment Ideas Investment IdeasStock of the DayStock Whisper IndexAnalyst RatingsAnalyst ColorFinancial AdvisorsGovernment TradesTrading IdeasStock ScreenerMarkets MarketsPremarket MoversAfter HoursOptionsETFsCommoditiesPrediction MarketsPrivate MarketsBondsFuturesForexTop Stocks Top StocksApple (AAPL)Tesla (TSLA)Amazon (AMZN)Nvidia (NVDA)Alphabet (GOOGL)Meta Platforms (META)Microsoft (MSFT)StreetTracks Gold Shares (GLD)IBIT Bitcoin Trust (IBIT)Top Value StocksTop Momentum StocksTop Growth StocksTop Quality StocksLearn LearnInvesting GuidesPersonal FinanceMortgagesBest Credit CardsBest Dividend StocksBest Swing Trade StocksInvestment Ideas Investment IdeasStock of the DayStock Whisper IndexAnalyst RatingsAnalyst ColorFinancial AdvisorsGovernment TradesTrading IdeasStock ScreenerMarkets MarketsPremarket MoversAfter HoursOptionsETFsCommoditiesPrediction MarketsPrivate MarketsBondsFuturesForexTop Stocks Top StocksApple (AAPL)Tesla (TSLA)Amazon (AMZN)Nvidia (NVDA)Alphabet (GOOGL)Meta Platforms (META)Microsoft (MSFT)StreetTracks Gold Shares (GLD)IBIT Bitcoin Trust (IBIT)Top Value StocksTop Momentum StocksTop Growth StocksTop Quality StocksLearn LearnInvesting GuidesPersonal FinanceMortgagesBest Credit CardsBest Dividend StocksBest Swing Trade StocksResearchMy StocksToolsFree Benzinga Pro Trial CalendarsAnalyst Ratings CalendarConference Call CalendarDividend CalendarEarnings CalendarEconomic CalendarEvents CalendarFDA CalendarGuidance CalendarIPO CalendarM&A CalendarUnusual Options Activity CalendarSPAC CalendarStock Split CalendarTrade IdeasStock ReportsInsider TradesTrade Idea FeedAnalyst RatingsUnusual Options ActivityHeatmapsFree NewsletterGovernment TradesPerfect Stock PortfolioEasy Income PortfolioShort InterestMost ShortedLargest IncreaseLargest DecreaseCalculatorsOptions Profit CalculatorMargin CalculatorForex Profit Calculator100x Options Profit CalculatorCovered Call CalculatorCash-Secured Put CalculatorLong Call CalculatorLong Put CalculatorScreenersStock ScreenerTop Momentum StocksTop Quality StocksTop Value StocksTop Growth StocksCompare Best StocksBest Momentum StocksBest Quality StocksBest Value StocksBest Growth StocksRecentMarkets May 23, 2026 1:01 PM 7 min read Place Your Bets – Futures Traders Are About To See The Launch Of AI Semiconductor ContractsCME Group (NYSE:CME) and data provider Silicon Data are partnering on a brand new market, allowing traders to place bets and hedge their investment risk on GPU price indexes.Futures traders will have access to contracts on a \"compute futures market,\" which will track the underlying price of AI semiconductors.AI Chips Arrive On The Financial Trading Stage With billions of dollars being invested in GPUs and AI infrastructure, the new market will give investors and traders the ability to lock in the price of computing capacity based on a GPU benchmark, the companies said in a joint statement released last week.Don't Miss:\"GPU markets have historically lacked standardized reference pricing,\" Silicon Data CEO Carmen Li said in the statement. \"The launch of compute futures is an important step toward giving AI builders, cloud providers, and investors more reliable tools for valuation, hedging, and long-term planning.\"The partnership will bring trusted compute pricing data together with a regulated derivatives provider to create \"a more mature and risk-manageable financial market,\" Li added.As new futures markets tied to AI infrastructure and semiconductor pricing continue to emerge, some active traders are exploring firms like Apex Trader Funding, which gives eligible traders the opportunity to qualify for funded futures trading accounts through a performance evaluation process.The new market still has to clear regulatory hurdles, but is expected to land on CME exchanges later this year, according to the companies.See Also: This Lithium Breakthrough Is Turning Heads on Wall Street — See Why Investors Are WatchingAI Capex Spend Drives GPU Pricing VolatilityThe arrival of a futures trading contract for chip prices comes as Wall Street continues to project huge capital expenditure in the AI sector, which is adding volatility to the semiconductor market.Read Next: \nWhat If Your Investment Income Didn't Rely Entirely on Market Swings? Some Investors Are Taking a Different Approach\nThis Under-$1 Pre-IPO AI Company Is Still Open to Retail Investors — Learn More\nBuilding Wealth Across More Than Just the MarketRad AIImmersedConnect InvestrHealthrHealth is building a space-tested diagnostics platform designed to bring lab-quality blood testing closer to patients in minutes rather than weeks. Originally validated in collaboration with NASA for use aboard the International Space Station, the technology is now being adapted for at-home and point-of-care settings to address widespread delays in diagnostic access.Backed by institutions including NASA and the NIH, rHealth is targeting the large global diagnostics market with a multi-test platform and a model built around devices, consumables, and software. With FDA registration in progress, the company is positioning itself as a potential shift toward faster, more decentralized healthcare testing.ArrivedMasterworksLightstoneAdviserMatchAccredited Debt ReliefImage: ShutterstockMarket News and Data brought to you by Benzinga APIs© 2026 Benzinga.com. Benzinga does not provide investment advice. All rights reserved.To add Benzinga News as your preferred source on Google, click here.Posted In: MarketsBZ-REALESTATEConnect With Us                                             About BenzingaAbout UsCareersAdvertiseContact UsMarket ResourcesAdvanced Stock Screener ToolsOptions Trading Chain AnalysisComprehensive Earnings CalendarDividend Investor Calendar and AlertsEconomic Calendar and Market EventsIPO Calendar and New ListingsMarket Outlook and AnalysisWall Street Analyst Ratings and TargetsTrading Tools & EducationBenzinga Pro Trading PlatformOptions Trading Strategies and NewsStock Market Trading Ideas and AnalysisTechnical Analysis Charts and IndicatorsFundamental Analysis and ValuationDay Trading Guides and StrategiesLive Investor EventsPre-market Stock Analysis and NewsCryptocurrency Market Analysis and NewsRing the BellA newsletter built for market enthusiasts by market enthusiasts. Top stories, top movers, and trade ideas delivered to your inbox every weekday before and after the market closes.SubscribeTerms & Conditions Do Not Sell My Personal Data/Privacy PolicyDisclaimer Service StatusSitemap© 2026 Benzinga | All Rights Reservedby Kevin George Benzinga Staff WriterFollowFlipboardIcon version of the Flipboard logoCMECME Group Inc$270.000.17%Overview\nOne futures evaluation could unlock access to significantly more buying power—see how Apex Trader Funding works.\nThe Difference Between a Fragmented Plan and an Integrated One Often Comes Down to Structure — See How PCM Encore Brings Investment, Tax, and Estate Planning Into Alignment.\nJ.P. Morgan analyst Samik Chatterjee recently raised his expectations for the top U.S. hyperscalers to spend $200 billion in 2026, according to media reports. The AI buildout is driving prices for memory chips higher in 2026, as chipmakers prioritize large customers, leading to supply shortages.Building a resilient portfolio means thinking beyond a single asset or market trend. Economic cycles shift, sectors rise and fall, and no one investment performs well in every environment. That's why many investors look to diversify with",
    "images": [
      "https://cdn.benzinga.com/cdn-cgi/image/width=1300,format=auto,quality=85/files/images/story/2025/07/24/article-header-background-image.png",
      "https://cdn.benzinga.com/cdn-cgi/image/width=1300,format=auto,quality=85/files/images/story/2025/07/24/article-header-background-image.png",
      "https://cdn.benzinga.com/cdn-cgi/image/width=850,format=auto,quality=85/files/images/story/2026/05/23/Semiconductor-Or-Microchip-Concepts-tech.jpeg",
      "https://cdn.benzinga.com/cdn-cgi/image/width=850,format=auto,quality=85/files/images/story/2026/05/23/Semiconductor-Or-Microchip-Concepts-tech.jpeg",
      "https://image-util.benzinga.com/api/v2/logos/file/image/1156375/mark_vector_light__c0d0fdb5010dcb30cb08a96f3ee19589.svg?x-bz-cred=sb~8wd0bR8CPZ4wS4iNzupIjz4WNk8y9lqr_ZkFB_Zb3wG3q8vi4cPF2AVHWSpULZq7_HvgNdqvW5ap8gh63kQiZlxzCu5oBKBLdtgXAmaFWGdaCluPc3wmDHhLboP2Z50L3QpUWvf-TbRkSICTxaomzLCZF5p2&x-bz-exp=1781412002&x-bz-security-isin=&x-bz-security-symbol=CME&x-bz-signature=21d5139fbf0e9ddee1e1134ef080834ade0e5c8fd6f6c373286e5913e2bb5147"
    ],
    "lang": "en",
    "title_cn": "下注——期货交易者即将看到人工智能半导体合约的推出",
    "summary_cn": "下注 – 期货交易者即将看到人工智能半导体合约的推出 - CME Group ( - BenzingaBenzingaEspañaItalia대한민국日本Français我的账户Benzinga EdgeBenzinga ResearchBenzinga ProLogin获取 Benzinga Pro 数据 & API活动上市前广告贡献西班牙意大利대한민국日本Français登录注册Benzinga高级服务财经新闻财经新闻大盘股小盘股内部",
    "translated": true
  },
  {
    "title": "Is CME Group Expanding Into the Compute Futures Market?",
    "source": "Nasdaq",
    "source_url": "https://www.nasdaq.com/articles/cme-group-expanding-compute-futures-market",
    "url": "https://www.nasdaq.com/articles/cme-group-expanding-compute-futures-market",
    "published": "2026-05-13",
    "summary": "AAPL\n\nTSLA\n\nAMZN\n\nMETA\n\nAMD\n\nNVDA\n\nPEP\n\nCOST\n\nADBE\n\nGOOG\n\nAMGN\n\nHON\n\nINTC\n\nINTU\n\nNFLX\n\nADP\n\nSBUX\n\nMRNA\n\nAAPL\n\nTSLA\n\nAMZN\n\nMETA\n\nAMD\n\nNVDA\n\nPEP\n\nCOST\n\nADBE\n\nGOOG\n\nAMGN\n\nHON\n\nINTC\n\nINTU\n\nNFLX\n\nADP\n\nSBUX\n\nMRNA\n\nAAPL\n\nTSLA\n\nAMZN\n\nMETA\n\nAMD\n\nNVDA\n\nPEP\n\nCOST\n\nADBE\n\nGOOG\n\nAMGN\n\nHON\n\nINTC\n\nINTU\n\nNFLX\n\nADP\n\nSBUX\n\nMRNA\n\nStocks\n\n      Is CME Group Expanding Into the Compute Futures Market?\n    \n\nMay 13, 2026",
    "full_text": "AAPL\n\nTSLA\n\nAMZN\n\nMETA\n\nAMD\n\nNVDA\n\nPEP\n\nCOST\n\nADBE\n\nGOOG\n\nAMGN\n\nHON\n\nINTC\n\nINTU\n\nNFLX\n\nADP\n\nSBUX\n\nMRNA\n\nAAPL\n\nTSLA\n\nAMZN\n\nMETA\n\nAMD\n\nNVDA\n\nPEP\n\nCOST\n\nADBE\n\nGOOG\n\nAMGN\n\nHON\n\nINTC\n\nINTU\n\nNFLX\n\nADP\n\nSBUX\n\nMRNA\n\nAAPL\n\nTSLA\n\nAMZN\n\nMETA\n\nAMD\n\nNVDA\n\nPEP\n\nCOST\n\nADBE\n\nGOOG\n\nAMGN\n\nHON\n\nINTC\n\nINTU\n\nNFLX\n\nADP\n\nSBUX\n\nMRNA\n\nStocks\n\n      Is CME Group Expanding Into the Compute Futures Market?\n    \n\nMay 13, 2026 — 12:00 pm EDT\n\n      Written by\n                        Zacks Equity Research for                             \n        \n\nZacks->\n\nCME Group Inc. CME is expanding its presence in next-generation financial markets through a partnership with Silicon Data, which is backed by global trading firm DRW, to launch a first-of-its-kind compute futures market later this year, pending regulatory approval. The initiative highlights CME’s strategy to capitalize on the rapidly growing AI infrastructure economy by introducing risk-management tools tied to compute and GPU pricing.The new futures contracts will be based on Silicon Data’s daily GPU benchmark indices for on-demand rental rates, allowing traders, financial institutions, AI developers and cloud-service providers to manage volatility and price risk in the expanding compute market. As demand for GPUs and AI infrastructure continues to surge, pricing across compute markets has remained fragmented and volatile due to differences among providers, regions and contract structures.By introducing standardized futures tied to transparent benchmark pricing, CME brings the scale, market structure and credibility needed to help transform compute from an opaque operational cost into a more mature and risk-manageable financial market. The launch of compute futures is an important step toward giving AI builders, cloud providers and investors more reliable tools for valuation, hedging and long-term planning as demand for compute continues to accelerate.The development aligns with CME Group’s strategy to expand into emerging asset classes tied to rising AI and cloud infrastructure demand. Growing adoption of compute futures could drive higher trading volumes, clearing activity and revenue diversification over time while strengthening CME’s position in evolving derivatives markets.How Are Competitors Faring?Peers like Nasdaq, Inc. NDAQ and London Stock Exchange Group plc LSEGY are also increasing investments in next-generation financial infrastructure through strategic technology partnerships.Nasdaq has expanded its collaboration with Amazon Web Services to modernize global capital markets infrastructure, cloud-enabled trading systems and AI-powered market solutions. The partnership reflects Nasdaq’s broader strategy to build scalable and resilient financial ecosystems capable of supporting future trading and data demands driven by AI and cloud adoption.LSEGY has strengthened its partnership with Amazon Web Services to migrate more of its markets, risk intelligence and analytics infrastructure to the cloud. The move is aimed at improving resilience, accelerating product innovation and enhancing large-scale data and risk analysis capabilities.CME’s Price Performance, Valuation & EstimatesShares of CME have risen 6.5% over the past year against the industry's decline of 6.9%.Image Source: Zacks Investment ResearchFrom a valuation standpoint, CME Group trades at a forward price-to-earnings ratio of 22.97X, up from the industry average of 20.90X.Image Source: Zacks Investment ResearchThe Zacks Consensus Estimate for CME Group’s 2026 earnings is pegged at $12.26 per share, implying a 9.5% jump from the year-ago period.Image Source: Zacks Investment ResearchCME currently carries a Zacks Rank #3 (Hold). You can see the complete list of today’s Zacks #1 Rank (Strong Buy) stocks here.\n\tZacks' Research Chief Names \"Stock Most Likely to Double\"\n\n\tOur team of experts has just released the 5 stocks with the greatest probability of gaining +100% or more in the coming months. Of those 5, Director of Research Sheraz Mian highlights the one stock set to climb highest.\n\n\tThis top pick is a little-known satellite-based communications firm. Space is projected to become a trillion dollar industry, and this company's customer base is growing fast. Analysts have forecasted a major revenue breakout in 2025. Of course, all our elite picks aren't winners but this one could far surpass earlier Zacks' Stocks Set to Double like Hims & Hers Health, which shot up +209%.Free: See Our Top Stock And 4 Runners UpWant the latest recommendations from Zacks Investment Research? Today, you can download 7 Best Stocks for the Next 30 Days. Click to get this free reportCME Group Inc. (CME) : Free Stock Analysis ReportNasdaq, Inc. (NDAQ) : Free Stock Analysis ReportLondon Stock Exchange Group plc - Unsponsored ADR (LSEGY) : Free Stock Analysis ReportThis article originally published on Zacks Investment Research (zacks.com).Zacks Investment Research\nThe views and opinions expressed herein are the views and opinions of the author and do not necessarily reflect those of Nasdaq, Inc.\n\n        Tags\n      \nStocks\n\nZacks\n\n          Zacks is the leading investment research firm focusing on stock research, analysis and recommendations. In 1978, our founder discovered the power of earnings estimate revisions to enable profitable investment decisions. Today, that discovery is still the heart of the Zacks Rank. A wealth of resources for individual investors is available at www.zacks.com.       \n\nMore articles by this source->\n\nStocks mentioned\n\nCME\n\nNDAQ\n\nMore Related Articles\n  \n\nThis data feed is not available at this time.\n\n            Data is currently not available\n        \n\n•\n\n  Sign up for the TradeTalks newsletter to receive your weekly dose of trading news, trends and education. Delivered Wednesdays.",
    "images": [
      "https://staticx-tuner.zacks.com/images/articles/charts/dd/160257.jpg?v=302636747",
      "https://staticx-tuner.zacks.com/images/articles/charts/17/160258.jpg?v=187014601",
      "https://staticx-tuner.zacks.com/images/articles/charts/02/160260.jpg?v=1735282957",
      "https://www.nasdaq.com/akam/13/pixel_6f4d97d4?a=dD1mZDRiYjVjOWU1MmNiNTUxYzA3NWNiMTYxNmQ0ZjU0ZmU2YmE2Yzc2JmpzPW9mZg=="
    ],
    "lang": "en",
    "title_cn": "芝商所是否正在进军计算期货市场？",
    "summary_cn": "AAPL\n\n特斯拉\n\n亚马逊\n\n梅塔\n\nAMD\n\nNVDA\n\nPEP\n\n成本\n\n阿德贝\n\nGoogle\n\nAMGN\n\n荣誉勋章\n\n国际贸易中心\n\n英图\n\nNFLX\n\n腺苷二磷酸\n\nSBUX\n\n信使核糖核酸\n\nAAPL\n\n特斯拉\n\n亚马逊\n\n梅塔\n\nAMD\n\nNVDA\n\nPEP\n\n成本\n\n阿德贝\n\nGoogle\n\nAMGN\n\n荣誉勋章\n\n国际贸易中心\n\n英图\n\nNFLX\n\n腺苷二磷酸\n\nSBUX\n\n信使核糖核酸\n\nAAPL\n\n特斯拉\n\n亚马逊\n\n梅塔\n\nAMD\n\nNVDA\n\nPEP\n\n成本\n\n阿德贝\n\nGoogle\n\nAMGN\n\n荣誉勋章\n\n国际贸易中心\n\n英图\n\nNFLX\n\n腺苷二磷酸\n\nSBUX\n\n信使核糖核酸\n\n股票\n\n      芝商所是否正在进军计算期货市场？\n    \n\n2026 年 5 月 13 日",
    "translated": true
  },
  {
    "title": "AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFB1NXZMVWl6N1JYV2xKd0V1ajlGdk1Dem10ajR5RUx6WXJpc1FoV3N4OFJvdHZfdXFjUFJDSi1zR0gxeWhTZWM5Nw?oc=5",
    "published": "2026-06-12",
    "summary": "AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场&nbsp;&nbsp;财联社",
    "full_text": "「AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场」\n\n📰 来源：财联社\n📅 发布日期：2026-06-12\n\n本文由 Google News 聚合自 财联社。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "贝莱德CEO预言：需求如此巨大 算力期货市场终将诞生",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE84MXdmRXdRUFRFb213eWhseWpvdTkxOVo5cFJuQm1WWTAwT0RIZkRCd09ST2FyR2FRNnVrR2U3UWd1TW5RNWt5cw?oc=5",
    "published": "2026-06-12",
    "summary": "贝莱德CEO预言：需求如此巨大 算力期货市场终将诞生&nbsp;&nbsp;财联社",
    "full_text": "「贝莱德CEO预言：需求如此巨大 算力期货市场终将诞生」\n\n📰 来源：财联社\n📅 发布日期：2026-06-12\n\n本文由 Google News 聚合自 财联社。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "万亿AI投资急需风险对冲 算力期货闯关多题待解",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE84dGlCTnFpanc2Qm9xbTdnU0dKaGNwQU9XdW1tU0ZLRkxPQkNJaTlrU1ZmbVkyV3VVUzl2NnJyXzNVTTRqWUR0bVE1dDFTZ0k5QUs3MFlFX0kwOEdsZkdWcGlKNzdhNDVqb210NFNwbS1iLTF0N2g0cw?oc=5",
    "published": "2026-06-12",
    "summary": "万亿AI投资急需风险对冲 算力期货闯关多题待解&nbsp;&nbsp;Sina finance",
    "full_text": "「万亿AI投资急需风险对冲 算力期货闯关多题待解」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-12\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力金融化“寻锚”",
    "source": "QQ News",
    "source_url": "https://news.qq.com",
    "url": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5iUXRFWExEUklDWmc4OVRnYWs0TENfVGJtVy14V0MxOFhPZnpwOEVPa2VxM0NtSUk1dWxHbS13WFJNRGEtbTY5dVFmQXdxd2VyRlpTSHpR?oc=5",
    "published": "2026-06-11",
    "summary": "算力金融化“寻锚”&nbsp;&nbsp;QQ News",
    "full_text": "「算力金融化“寻锚”」\n\n📰 来源：QQ News\n📅 发布日期：2026-06-11\n\n本文由 Google News 聚合自 QQ News。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "推出算力期货，存在哪些痛点？",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxQdl9LTW5sNWoxWFp6MmVNZ1lpSndib1pVRFFwWktKdDNad0J6ZjBiMURRdmlQcy1JdWZSNU5mZmxZTlIwa3lmcXZFWVZXSlRQVFRNd3lZbGZIanJzTVJPbmFXdk5VNVYySW1sbFlVMlh5ZHpzeVFJdTlySURrUVdyYnhXRXBxRDBkUnYzVw?oc=5",
    "published": "2026-06-11",
    "summary": "推出算力期货，存在哪些痛点？&nbsp;&nbsp;Sina finance",
    "full_text": "「推出算力期货，存在哪些痛点？」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-11\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Demand",
    "source": "GuruFocus",
    "source_url": "https://www.gurufocus.com",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPclFSSHpBX2hWRVRidnNQajlWWngybEtsNnFvRmdKbVNEdVF6TnBjYVpfb1l1X01zU1RzMFNYeGRaMVlkXzYweEJXMFRoNVhrcHBpR0Qyck1wYWlrMnd5WmREenlFSGlWVk16VnVKaHQwTW5qMUZLWVhPMGVOMDNJMi1wUVpQSEtYNC1FNjBEbVQ0ZkNxX1J3Y0I1dlZZcVBHVll2Qkk3UzFTck91dTUtQXh3?oc=5",
    "published": "2026-06-09",
    "summary": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Demand&nbsp;&nbsp;GuruFocus",
    "full_text": "「高盛和摩根大通在人工智能需求中探索 GPU 未来」\n\n📰 Source: GuruFocus\n📅 Published: 2026-06-09\n\nOriginal title: Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Demand\n\nThis article is aggregated from GuruFocus via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "高盛和摩根大通在人工智能需求中探索 GPU 未来",
    "summary_cn": "高盛和摩根大通在人工智能需求中探索 GPU 未来 &nbsp;&nbsp;GuruFocus",
    "translated": true
  },
  {
    "title": "Goldman, JPMorgan Explore AI Compute Futures Trading",
    "source": "Let's Data Science",
    "source_url": "https://letsdatascience.com",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxNMlFXSWpxMkVLVTEtd0sweTdqazVCZzl2cmo0bkZCSFZpSmo0dENILXdKcGRteHd0LUlCaHVudmZLM1dkVURnSVNPaFNjTmoxSGtscXpkLXJBNHkteTBTaWt4XzIweVBKQkJLeHBMcnhuR1ZlQkd6cHJ1ZWlTZTlNZzVYODRRQjFGVU5LX3RJd0k5UkRJa2dKdQ?oc=5",
    "published": "2026-06-09",
    "summary": "Goldman, JPMorgan Explore AI Compute Futures Trading&nbsp;&nbsp;Let's Data Science",
    "full_text": "「高盛、摩根大通探索人工智能计算期货交易」\n\n📰 Source: Let's Data Science\n📅 Published: 2026-06-09\n\nOriginal title: Goldman, JPMorgan Explore AI Compute Futures Trading\n\nThis article is aggregated from Let's Data Science via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "高盛、摩根大通探索人工智能计算期货交易",
    "summary_cn": "高盛、摩根大通探索人工智能计算期货交易&nbsp;&nbsp;让我们数据科学",
    "translated": true
  },
  {
    "title": "高盛与摩根大通探索算力期货交易以对冲AI融资风险 多家交易所与机构争相布局新兴市场",
    "source": "太平洋科技",
    "source_url": "http://news.pconline.com.cn",
    "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE00Y292blNxamJDUkRiODJPZFk0Y2VsMEZPNkhUSllXbXFIQ0tyV0ZNMFJQUV9oOER6UEZHd3ZTVE5FdjFxY3pLMy1KRXZfUVZIZVM5ZHp1WUZSdw?oc=5",
    "published": "2026-06-09",
    "summary": "高盛与摩根大通探索算力期货交易以对冲AI融资风险 多家交易所与机构争相布局新兴市场&nbsp;&nbsp;太平洋科技",
    "full_text": "「高盛与摩根大通探索算力期货交易以对冲AI融资风险 多家交易所与机构争相布局新兴市场」\n\n📰 来源：太平洋科技\n📅 发布日期：2026-06-09\n\n本文由 Google News 聚合自 太平洋科技。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "高盛、摩根大通探索算力期货交易，用作AI融资风险对冲工具",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxQY0dJWjlNbUFPVHdzSVo0VWpTd3ZaZ0VPQTk2QzNTTFRCWkVYNmV3Vk94aElwX0dFM0VOUG5vcE4xcU1SUGx0cXYtY1U2eWZpODVGQTZMdFlzYkJBUkh2WjAtbUtYQ1ZKMUR0WkdBTi1yUnFoYzg4WWRkcUdObzU0SXZmRVVHanM?oc=5",
    "published": "2026-06-09",
    "summary": "高盛、摩根大通探索算力期货交易，用作AI融资风险对冲工具&nbsp;&nbsp;Sina finance",
    "full_text": "「高盛、摩根大通探索算力期货交易，用作AI融资风险对冲工具」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-09\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "高盛摩根大通探索算力期货交易 为AI融资风险对冲助力",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE1vZVpHSURNaWtKQjNDUk85TGQ0bDNWTFZRQkotMF9xRUVjRExMVHIxZUFxSzV1S1Jwb3JkMmp6dUd1b2VyZXR3T2o1SU5Cam9MTGMxeWJCTVZZcGJmXzh1MWp6OE5rY2h6TVVpem9OcFJoMjRySkN2YQ?oc=5",
    "published": "2026-06-09",
    "summary": "高盛摩根大通探索算力期货交易 为AI融资风险对冲助力&nbsp;&nbsp;Sina finance",
    "full_text": "「高盛摩根大通探索算力期货交易 为AI融资风险对冲助力」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-09\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Boom",
    "source": "GuruFocus",
    "source_url": "https://www.gurufocus.com",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNdXlZUmlVdTM2MWFlM0hqTTZ5X09nd1pFQ2xKRXdDZURxNEJBUFlJTklsVmVKZDlleHlaMkc5bnA4MFFhZVdOd3JKTWI4dHg0MFlhaWI3Wm9selRoTzhfXzJHY2VYdnR0SjJOTUZYQ19Cd19wR0xCZFpqZEN0YnhSQVp3ay0xdW41Wno1TFZaaWt2ak0yZmNHRU5vekt6anhqWmJReHI3ZlpfMWdaa1dz?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Boom&nbsp;&nbsp;GuruFocus",
    "full_text": "「高盛和摩根大通在人工智能热潮中探索 GPU 未来」\n\n📰 Source: GuruFocus\n📅 Published: 2026-06-08\n\nOriginal title: Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Boom\n\nThis article is aggregated from GuruFocus via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "高盛和摩根大通在人工智能热潮中探索 GPU 未来",
    "summary_cn": "高盛和摩根大通在人工智能热潮中探索 GPU 未来 &nbsp;&nbsp;GuruFocus",
    "translated": true
  },
  {
    "title": "Goldman Sachs and JPMorgan Chase explore the financialization of computing power, planning to launch GPU leasing futures to hedge AI risks",
    "source": "WEEX",
    "source_url": "https://www.weex.com",
    "url": "https://news.google.com/rss/articles/CBMioAJBVV95cUxQMnZOeXZnQWtrbUt4MXFfdW9lY3FORHBsNmRheFVQeGFLQzJ5ZElsWkF1aHBHVjRRU0xwM2xXaWVfTFd2MWp6c3l3cEtzeDhTWWMyUmdWeXVZejlNUU9OUjg4Y3dIbTZqM044Qm1FelEtTlBoVW1RMW5NS3hfVzdxTkxvaklObHRXWDJrYS16ZEZQUUphLTlONm1YWWNNdDVYdktPS0dZcURYNUUtYmNpcUE5LU1yLXRhbndOblBNRFROVmR3cGY0UW11RmRSZjI1NWxHQlVHYkgtY0E5aVU4U19EN2VXSlBwWjNjb3JzZGI1REoxbDFyMHRITlQyMG9qVGNLOUMyMmk4bnhHUWZZZHgyUUZGVDkxRXRDMFlBTHk?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman Sachs and JPMorgan Chase explore the financialization of computing power, planning to launch GPU leasing futures to hedge AI risks&nbsp;&nbsp;WEEX",
    "full_text": "「高盛联手摩根大通探索算力金融化，拟推出GPU租赁期货对冲AI风险」\n\n📰 Source: WEEX\n📅 Published: 2026-06-08\n\nOriginal title: Goldman Sachs and JPMorgan Chase explore the financialization of computing power, planning to launch GPU leasing futures to hedge AI risks\n\nThis article is aggregated from WEEX via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "高盛联手摩根大通探索算力金融化，拟推出GPU租赁期货对冲AI风险",
    "summary_cn": "高盛携手摩根大通探索算力金融化，计划推出GPU租赁期货对冲AI风险 WEEX",
    "translated": true
  },
  {
    "title": "Goldman Sachs and JPMorgan explore the financialization of computing power, planning to launch GPU rental futures to hedge AI risks",
    "source": "Bitget",
    "source_url": "https://www.bitget.com",
    "url": "https://news.google.com/rss/articles/CBMiY0FVX3lxTE1OZ1U2TTE5aHBXVTFlWFpEd1VpSTZ6ZXdhLVZrbGxSQmo0U3N4WmZEdW9jMlEwS2kzSXphcXJodmNPSEdzY21keVFrVFNsSlo2dGxZX2pCV05TWXk2dXhmUnk2a9IBY0FVX3lxTE1OZ1U2TTE5aHBXVTFlWFpEd1VpSTZ6ZXdhLVZrbGxSQmo0U3N4WmZEdW9jMlEwS2kzSXphcXJodmNPSEdzY21keVFrVFNsSlo2dGxZX2pCV05TWXk2dXhmUnk2aw?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman Sachs and JPMorgan explore the financialization of computing power, planning to launch GPU rental futures to hedge AI risks&nbsp;&nbsp;Bitget",
    "full_text": "「高盛与摩根大通探索算力金融化，计划推出GPU租赁期货对冲AI风险」\n\n📰 Source: Bitget\n📅 Published: 2026-06-08\n\nOriginal title: Goldman Sachs and JPMorgan explore the financialization of computing power, planning to launch GPU rental futures to hedge AI risks\n\nThis article is aggregated from Bitget via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "高盛与摩根大通探索算力金融化，计划推出GPU租赁期货对冲AI风险",
    "summary_cn": "高盛与摩根大通探索算力金融化，计划推出GPU租赁期货对冲AI风险 Bitget",
    "translated": true
  },
  {
    "title": "Wall Street Tests New Ways To Price AI Compute",
    "source": "Finimize",
    "source_url": "https://finimize.com",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxObUsxeDNKQTN1c2pLZEdyR3JfX014THpHLXNXNUx5d1hlUEVFcEkyU1J6N2FiR1ZtbEU5VnFOSDFzOXIyWEl1R2tERE9BelVlRlQxSGlBWi1pQmxSM05DWXcwUncxM0J2dWV2Y25RMWttQ3N0TVZDbWxLMEZtY0Y5Uw?oc=5",
    "published": "2026-06-08",
    "summary": "Wall Street Tests New Ways To Price AI Compute&nbsp;&nbsp;Finimize",
    "full_text": "「华尔街测试人工智能计算定价的新方法」\n\n📰 Source: Finimize\n📅 Published: 2026-06-08\n\nOriginal title: Wall Street Tests New Ways To Price AI Compute\n\nThis article is aggregated from Finimize via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "华尔街测试人工智能计算定价的新方法",
    "summary_cn": "华尔街测试人工智能计算定价的新方法",
    "translated": true
  },
  {
    "title": "Goldman, JPMorgan Explore Trading Compute Futures as AI Financing Hedge",
    "source": "The Information",
    "source_url": "https://www.theinformation.com",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQalQyZEs0bnljOE5xZHkyRDliYk1GSnJHUXRraUdIbWhBUGtfSl9NcE5tQ2NfRXRPd3VsazA1VHcwdFRGTXBaNGZmWUJ1RnRUTnEyVVFiUDRFWWdaaVBYUEJqXzVBMzd1MklNWFBVSFdSaFZJemVEdHh1RGwtYUQycjFTaTN4V09paXNmcG11eF9tRTE0Y1FLNG9LUQ?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman, JPMorgan Explore Trading Compute Futures as AI Financing Hedge&nbsp;&nbsp;The Information",
    "full_text": "「高盛和摩根大通探索计算期货交易作为人工智能融资对冲」\n\n📰 Source: The Information\n📅 Published: 2026-06-08\n\nOriginal title: Goldman, JPMorgan Explore Trading Compute Futures as AI Financing Hedge\n\nThis article is aggregated from The Information via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "高盛和摩根大通探索计算期货交易作为人工智能融资对冲",
    "summary_cn": "高盛和摩根大通探索计算期货交易作为人工智能融资对冲&nbsp;&nbsp;信息",
    "translated": true
  },
  {
    "title": "高盛和摩根大通考虑推出与GPU租赁价格挂钩的期货",
    "source": "富途牛牛",
    "source_url": "https://news.futunn.com",
    "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1pVVRCMTNUT21zaklCb0YtbHpEU2R1UGhYWTFaX2Q3UFUzTzJLTkgtS05iNXVxaXdTOVlxLWxkaElpWHZXNXFNbHVkV3k2dw?oc=5",
    "published": "2026-06-08",
    "summary": "高盛和摩根大通考虑推出与GPU租赁价格挂钩的期货&nbsp;&nbsp;富途牛牛",
    "full_text": "「高盛和摩根大通考虑推出与GPU租赁价格挂钩的期货」\n\n📰 来源：富途牛牛\n📅 发布日期：2026-06-08\n\n本文由 Google News 聚合自 富途牛牛。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "经济学家宋清辉：算力期货孕育A股新机遇，四大板块料享红利",
    "source": "财经号",
    "source_url": "http://mp.cnfol.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE42SzFTSjFHQk5Ja1owMGJRQU54QWc0bF80clJ4M0hzQ2dEdm9PaWNJQlU1eUZKdmZ4Z0ZudU12RTExTkVhVThiaUJqcU1vek83cEpqNk5HdFB4RVIxRF9OcG5hb3JlOHNLVDNJ?oc=5",
    "published": "2026-06-08",
    "summary": "经济学家宋清辉：算力期货孕育A股新机遇，四大板块料享红利&nbsp;&nbsp;财经号",
    "full_text": "「经济学家宋清辉：算力期货孕育A股新机遇，四大板块料享红利」\n\n📰 来源：财经号\n📅 发布日期：2026-06-08\n\n本文由 Google News 聚合自 财经号。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI的新价格语言，算力何以成期货",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPODYwTkp4R3dYbDdCRUpkWTF1S2dsbGFnNmxjRXZtcmhHcVJ3OEkteWZNQkEyNUlxMDZRZ1pRRmFDeGNhRkxwWERkMld6Vzg3UjFRVHJlc1kzdmdGSlIyaHpNQ2pxTlMzZXhMTzNzSC1rV3FfZVJCWkZVekptT2lSMDFNNVVKZmc?oc=5",
    "published": "2026-06-08",
    "summary": "AI的新价格语言，算力何以成期货&nbsp;&nbsp;Sina finance",
    "full_text": "「AI的新价格语言，算力何以成期货」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-08\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "高盛与摩根大通探索算力金融化，拟推出 GPU 租赁期货对冲 AI 风险",
    "source": "Bitget",
    "source_url": "https://www.bitget.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE9lRlhVOGUwb1dqdTNVcmhLeTZ4SlloSkZHS2JYby1vSUhnVThwWk1HOTdWdzFpdDQ5UU12RDR1dUNsZmVaUmdnUm1EazFaeUZPNHhFWm1iT3FRSE9MOGdwVUQ5Q1lhUdIBa0FVX3lxTFA5RGw5aDQ2cDRPYjAxczJSRUE1T2ZtVWZEZzNOZkpyVE9hblkxN215VUNoaEpZSG1nR1pTdGY4N0JLNmtEUnVhQ3UtMnpKMnJjVnNqLVJXWnR5anRNdGYxV1M2dWllRjAzMlBn?oc=5",
    "published": "2026-06-07",
    "summary": "高盛与摩根大通探索算力金融化，拟推出 GPU 租赁期货对冲 AI 风险&nbsp;&nbsp;Bitget",
    "full_text": "「高盛与摩根大通探索算力金融化，拟推出 GPU 租赁期货对冲 AI 风险」\n\n📰 来源：Bitget\n📅 发布日期：2026-06-07\n\n本文由 Google News 聚合自 Bitget。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Why benchmark integrity will determine the success of India’s electricity futures",
    "source": "ET Edge Insights",
    "source_url": "https://etedge-insights.com",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxPYlBBZHhldmo0NEZMTmJ3aWNBc3FNQ2hBb1F4ZUNCMWlRNzJDeEhYeXQwckVvTGY3WlBpNEY2ZERycTJKT0JKbHliQUZDeGdoenVQNTAxbVpOcmNmc2l0cmNpWU9NQVRFNVZ0VG0yWGtWRTZiS21ZNElJZmNjLURoc1BlTGRtTnN1Wm9RN05STXluRFlDNkczeHBCd2IyR0lVTzV5LXZQZzhXMENFbUQwWXNFeWg3OEc3?oc=5",
    "published": "2026-06-06",
    "summary": "Why benchmark integrity will determine the success of India’s electricity futures&nbsp;&nbsp;ET Edge Insights",
    "full_text": "「为什么基准完整性将决定印度电力期货的成功」\n\n📰 Source: ET Edge Insights\n📅 Published: 2026-06-06\n\nOriginal title: Why benchmark integrity will determine the success of India’s electricity futures\n\nThis article is aggregated from ET Edge Insights via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "为什么基准完整性将决定印度电力期货的成功",
    "summary_cn": "为什么基准完整性将决定印度电力期货的成功 ET Edge Insights",
    "translated": true
  },
  {
    "title": "新华能源周报丨上海：做好电力期货、算力期货研发准备；今夏国家电网最大用电负荷同比增约6%",
    "source": "新华网",
    "source_url": "https://www.news.cn",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxQV3BJX053bkFiNGk4UmlKOWhNVmVZU2gzNDNqRFhzRFkwVHlhYTAtNWZORzVHdkVsTnYxSGhpVDZVZ3c4S1VLRGdOeEFPY0N1SHdaR1BqUkl3ZUJUMWdPU3k2T3VzamxDUE5kZktFRjdQR09mYnpPVmwybFZwNGJnbw?oc=5",
    "published": "2026-06-05",
    "summary": "新华能源周报丨上海：做好电力期货、算力期货研发准备；今夏国家电网最大用电负荷同比增约6%&nbsp;&nbsp;新华网",
    "full_text": "「新华能源周报丨上海：做好电力期货、算力期货研发准备；今夏国家电网最大用电负荷同比增约6%」\n\n📰 来源：新华网\n📅 发布日期：2026-06-05\n\n本文由 Google News 聚合自 新华网。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力期货提上日程，市场布局新赛道",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5BQ0VvaE9haGFxUERxODBVbFRlSGZJaDdvN2dPTjU3eUZmcFpKZWVld3E2RkcxTW03WDMzeFV6WVZ5bmZIdk9FbDJUX3I5aWlEMzhmOXJKYW4tVWRCQ3dIYnQ0dkJ5cEhPdUVv?oc=5",
    "published": "2026-06-05",
    "summary": "算力期货提上日程，市场布局新赛道&nbsp;&nbsp;财富号",
    "full_text": "「算力期货提上日程，市场布局新赛道」\n\n📰 来源：财富号\n📅 发布日期：2026-06-05\n\n本文由 Google News 聚合自 财富号。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "薛鹤翔：算力期货将引领AI产业迭代与体系重塑——算力期货专题报告",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE5udWRCbl9mcjJEdjRsODR5cUNROTVKWHcwVlBHYXpveDJ0aHo0U3BhYzNKMVJiSEJ1ZDNBSW5CQ0Y3Uk1NSWJqTGhiOUczMjYwZGdaVGRBcTJSeGw5MDVIWFAyOGxhMHg4dS1KWHdmeERydG9GTEE?oc=5",
    "published": "2026-06-05",
    "summary": "薛鹤翔：算力期货将引领AI产业迭代与体系重塑——算力期货专题报告&nbsp;&nbsp;Sina finance",
    "full_text": "「薛鹤翔：算力期货将引领AI产业迭代与体系重塑——算力期货专题报告」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-05\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "无锡金融委：推出算力期货 国联民生将发挥什么作用？",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxOQ0QwbUtkZjZHUURQbi1FbE82aVVVTVJCZk9YQmdJQjVQdTJqQ3VzZ19qWWZ2d2d2aXd5TWNva1VaTXdVVDR4SWJLLXhfc29pa21vaE9tcmg5Q3FibWJFWlByLU83YXV2RVpTLUEwbmNhV3BYZ0VWNk9sZEFPdXBjNHl3d0NoNlo2?oc=5",
    "published": "2026-06-05",
    "summary": "无锡金融委：推出算力期货 国联民生将发挥什么作用？&nbsp;&nbsp;Sina finance",
    "full_text": "「无锡金融委：推出算力期货 国联民生将发挥什么作用？」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-05\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海市发文做好\"算力期货\"研发准备",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE1GUnVSV21NYjNreHpOdE9jTHJUUjVkWmlLTFBIb0hoTnViZ3g4aklkNjNZNkJoV2hIRWtqUEFKSG5xa3RQdlVMQjN6Q0NMV293bGVNOHViLW9FN0RmVkp2TUh6TTNhd2gtUUFfalBjbGxnUHZFQnc?oc=5",
    "published": "2026-06-04",
    "summary": "上海市发文做好\"算力期货\"研发准备&nbsp;&nbsp;Sina finance",
    "full_text": "「上海市发文做好\"算力期货\"研发准备」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-04\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海提出做好算力期货研发准备 还需跨越这些坎",
    "source": "东方财富",
    "source_url": "https://wap.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE9UTDhtVHotYTZKRDNsa25Od3NESVRtRVFJWlh5RWtYR0I4dGVqRXdhRmRrYm9VTzdIbzlSSERfUzVuZW15UUt4UFlrNkVobzVFRkpHU0p1TUJUX21NZXRUSg?oc=5",
    "published": "2026-06-04",
    "summary": "上海提出做好算力期货研发准备 还需跨越这些坎&nbsp;&nbsp;东方财富",
    "full_text": "「上海提出做好算力期货研发准备 还需跨越这些坎」\n\n📰 来源：东方财富\n📅 发布日期：2026-06-04\n\n本文由 Google News 聚合自 东方财富。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI时代的“算力”期货市场什么样？",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE5ORXM3UVlMLU1ZTVFWbzBHa3ljU0JwZXlGTW9GbVV6MGJseHNXZ1JFaTlYeTI5cHk4bWg1VVdjZDV1OGViQXdjbkh3LUQ5WGFJMk9iOXBsRWllOXd5a2ZkSlNwX083QU5TRXRPRzBfZnNEcG9VYVE?oc=5",
    "published": "2026-06-04",
    "summary": "AI时代的“算力”期货市场什么样？&nbsp;&nbsp;Sina finance",
    "full_text": "「AI时代的“算力”期货市场什么样？」\n\n📰 来源：Sina finance\n📅 发布日期：2026-06-04\n\n本文由 Google News 聚合自 Sina finance。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海明确加快推出液化天然气期货期权，研发电力、算力期货",
    "source": "新浪财经",
    "source_url": "https://cj.sina.cn",
    "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTFBfSTBuZFpqRDA5T1l2RE5xWXBfWGNQTWwtVlNBdjNCVU9MdmhRRlByTjVtRDZFYUR6X1dwX1RkTzhxREwyQ2J5Z1d1YzREcjItNFFRUW5oYnAyMWlJZTlrZkc0ZHYzWVo5UXlVNFUxTQ?oc=5",
    "published": "2026-06-03",
    "summary": "上海明确加快推出液化天然气期货期权，研发电力、算力期货&nbsp;&nbsp;新浪财经",
    "full_text": "「上海明确加快推出液化天然气期货期权，研发电力、算力期货」\n\n📰 来源：新浪财经\n📅 发布日期：2026-06-03\n\n本文由 Google News 聚合自 新浪财经。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "6月3日早餐 | 上海推动算力期货研发；美英伟达CPO交换机全面量产",
    "source": "Sohu",
    "source_url": "https://www.sohu.com",
    "url": "https://news.google.com/rss/articles/CBMiUkFVX3lxTE8tU0FENUp5bXFkUnY4VEpmZGtZWkZHN0ozTnFTaW5KS3dsWXNaV2RKdVpud0huNlRhRDI4MUZDSTItaUgtVkdCdjhaYWhpQUtDeUE?oc=5",
    "published": "2026-06-03",
    "summary": "6月3日早餐 | 上海推动算力期货研发；美英伟达CPO交换机全面量产&nbsp;&nbsp;Sohu",
    "full_text": "「6月3日早餐 | 上海推动算力期货研发；美英伟达CPO交换机全面量产」\n\n📰 来源：Sohu\n📅 发布日期：2026-06-03\n\n本文由 Google News 聚合自 Sohu。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "全球算力定价权将花落谁家？上海宣布研发算力期货 抢占数字经济新高地",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFAyMlYyVmI3b0VFaU9halRSODExbTJjZWtLam5aUXV6TUM2WjJzZU1WbFNHeWs0cW5vbEREZFBjVkR2OXZHbzFCNmh6UE0wY0lSVnFNWUVrbXlDZFlWaDBLRWJwT2ZTQQ?oc=5",
    "published": "2026-06-03",
    "summary": "全球算力定价权将花落谁家？上海宣布研发算力期货 抢占数字经济新高地&nbsp;&nbsp;东方财富",
    "full_text": "「全球算力定价权将花落谁家？上海宣布研发算力期货 抢占数字经济新高地」\n\n📰 来源：东方财富\n📅 发布日期：2026-06-03\n\n本文由 Google News 聚合自 东方财富。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "布局电力、算力等期货，推动科创50等股指期货期权上市，“上海价格”影响力持续跃升",
    "source": "Jiemian.com",
    "source_url": "https://www.jiemian.com",
    "url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE9zODhHdjRwNThjMHFWVlNYNWt0cGtnTUtFSHZYX3RGWUdXWENUUzhlZDB3WW5hYlVTWGtkZHR5b1RwU0g2eUFEb2pnNzk4amVRTDdFMUtnMVE?oc=5",
    "published": "2026-06-02",
    "summary": "布局电力、算力等期货，推动科创50等股指期货期权上市，“上海价格”影响力持续跃升&nbsp;&nbsp;Jiemian.com",
    "full_text": "「布局电力、算力等期货，推动科创50等股指期货期权上市，“上海价格”影响力持续跃升」\n\n📰 来源：Jiemian.com\n📅 发布日期：2026-06-02\n\n本文由 Google News 聚合自 Jiemian.com。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "14:13:23【上海：加快推出液化天然气期货和期权 做好电力期货、算力期货研发准备】",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFBrWk40bzlaVjlrQ244RUZrdEpOaEtlY0x5X0pBRUh3bGllV2stOWZiNjRnMjRSQzRFbFV1d2s4d3lYcXd4Q2NNbw?oc=5",
    "published": "2026-06-02",
    "summary": "14:13:23【上海：加快推出液化天然气期货和期权 做好电力期货、算力期货研发准备】&nbsp;&nbsp;财联社",
    "full_text": "「14:13:23【上海：加快推出液化天然气期货和期权 做好电力期货、算力期货研发准备】」\n\n📰 来源：财联社\n📅 发布日期：2026-06-02\n\n本文由 Google News 聚合自 财联社。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海：做好算力期货研发准备，推动科创50、深证100、创业板股指期货和期权上市",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE1qLWl4QlAwTTFxckJnd09WUFNQNGtJWGUzazdEVkl3T0RjOVdTM3F4UjVLRjBxZkVXLVZ6MzZqSWVUNkhHZmNzSg?oc=5",
    "published": "2026-06-02",
    "summary": "上海：做好算力期货研发准备，推动科创50、深证100、创业板股指期货和期权上市&nbsp;&nbsp;财联社",
    "full_text": "「上海：做好算力期货研发准备，推动科创50、深证100、创业板股指期货和期权上市」\n\n📰 来源：财联社\n📅 发布日期：2026-06-02\n\n本文由 Google News 聚合自 财联社。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海发布算力期货研发筹备对云赛智联有何影响？",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5Idmt1RDduM0IzTzdlSFZYRW9adjJjNGFkMnNXWndSVGpuX240a2ZaZ3ZBS2JTdGJUX0lPa0ZMU0lrTzhzNDIxWmdUYkItNVNZZzFSd2dNUTdtazFrQldYWWNPT3ZGNC1ycHE4?oc=5",
    "published": "2026-06-02",
    "summary": "上海发布算力期货研发筹备对云赛智联有何影响？&nbsp;&nbsp;财富号",
    "full_text": "「上海发布算力期货研发筹备对云赛智联有何影响？」\n\n📰 来源：财富号\n📅 发布日期：2026-06-02\n\n本文由 Google News 聚合自 财富号。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "南华期货：中国发展自身算力期货市场，具有超越单纯经济价值的战略意义",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFBoS29vRldSdUphVVZ1U1NvcWMtanhPX3ZBZEMtS0dpZjdUVlBKOFBXSDBPRE9GTU4yX1Ria2N4QlMtNWF0V0VtaEdSLWMyb2JycmZNaFJEMlV3anVHOGFOWlFPOFBoQQ?oc=5",
    "published": "2026-06-02",
    "summary": "南华期货：中国发展自身算力期货市场，具有超越单纯经济价值的战略意义&nbsp;&nbsp;东方财富",
    "full_text": "「南华期货：中国发展自身算力期货市场，具有超越单纯经济价值的战略意义」\n\n📰 来源：东方财富\n📅 发布日期：2026-06-02\n\n本文由 Google News 聚合自 东方财富。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力期货提上日程 衍生品服务科创大有可为",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFBmNlB1RHVoWU5wUWJEcldFcXJUaFREUzhEeko1bXQ1SnpXeXJ5VEVSUnZ5RUZLdjdHdlVxMWhkWVdGSkpub2Y1R0ozX04xZzdRN3VUblJkTVBxbHdZSnItYUFSTmR2dw?oc=5",
    "published": "2026-06-02",
    "summary": "算力期货提上日程 衍生品服务科创大有可为&nbsp;&nbsp;东方财富",
    "full_text": "「算力期货提上日程 衍生品服务科创大有可为」\n\n📰 来源：东方财富\n📅 发布日期：2026-06-02\n\n本文由 Google News 聚合自 东方财富。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力期货说明什么",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1SekZRdklYcEJIZVRteWptNWNUWDNrdVY3M2I0WnFMcWRnZDVkcnV0OU01bHpWem13dFNKM1kzY1QyQVhXT3ZUT3RZZk13RGtGTC1COWlqT2R3MTBXVk9tS1hsdWQxUW5YWlNF?oc=5",
    "published": "2026-06-02",
    "summary": "算力期货说明什么&nbsp;&nbsp;财富号",
    "full_text": "「算力期货说明什么」\n\n📰 来源：财富号\n📅 发布日期：2026-06-02\n\n本文由 Google News 聚合自 财富号。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海做好算力期货研发准备 新大宗商品呼之欲出",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE0ySjNmM0swbkFaeTQ1ZHRtbWhLclplVkxhV0g4ai1RTXZ5SXJYb21UeGUzdEZCdVlZT0pncENXYlg5MzVoVGRscmNCU0E5ejNoSTNsRUFMdW5XckxFRjNVMHhVUlJUUQ?oc=5",
    "published": "2026-06-01",
    "summary": "上海做好算力期货研发准备 新大宗商品呼之欲出&nbsp;&nbsp;东方财富",
    "full_text": "「上海做好算力期货研发准备 新大宗商品呼之欲出」\n\n📰 来源：东方财富\n📅 发布日期：2026-06-01\n\n本文由 Google News 聚合自 东方财富。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Is ICE’s Record Energy OI and GPU Futures Push Altering The Investment Case For Intercontinental Exchange (ICE)?",
    "source": "simplywall.st",
    "source_url": "https://simplywall.st",
    "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxQX0tXNGx6NTJBWl9faFZYRGVQdzd0UkNEZm1mTlVzSkc3dWdCa1VHanY5d0tMcWw3VzFXY0RLMlFFOXhMczdjV00yWi1qX1c2UjFvalJnMG9aaTA0bWw2TEdiQlZSM0NTT3V0VGZmY3h1RFoyU0hrTUNrcERydTRKemc0LXJqUGZoNG5rb3IteGs4Y2VPeHNKdEZaYXVIdHdtTVI0Yl9DMkZuWEpzWm5VUmNFbmdneHB1NldyNGRxTGwzUndVeXpWUTNNZEdpY0FsVVRzRGtFREF6bVNjTmxZUEs0WkYxakhzM0pF0gHwAUFVX3lxTE51LXFUamx1ZGRJMGQ0bG9Ea2M3SlNUbHltZGlIOUgzLWlEWVotaVdFWjlwVkJROExSZmdNbWhBTUFyMk5sZVNTSHBmcHpvY2JpYmV1M09xSUQyeGljTVJPSFM2aWt2SFEydExSVXZIbmFhUHE0OXFaanRpdUVfajRWZ09pcnJRdHRPWTlEcHlGYVR1VnFEQVotRGM4NDB5QXk2OUdIOGNNdkhseGd5VWtGeHpQNEJHcFV5Ym14NFVqVDhvWUdEeTg5aTdoclBGcklMZjJubDdndm9SVlF2bkVwRFZmV1ltSWFNNE5LdUpJOA?oc=5",
    "published": "2026-05-31",
    "summary": "Is ICE’s Record Energy OI and GPU Futures Push Altering The Investment Case For Intercontinental Exchange (ICE)?&nbsp;&nbsp;simplywall.st",
    "full_text": "「ICE 创纪录的能源 OI 和 GPU 期货推动是否会改变洲际交易所 (ICE) 的投资案例？」\n\n📰 Source: simplywall.st\n📅 Published: 2026-05-31\n\nOriginal title: Is ICE’s Record Energy OI and GPU Futures Push Altering The Investment Case For Intercontinental Exchange (ICE)?\n\nThis article is aggregated from simplywall.st via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "ICE 创纪录的能源 OI 和 GPU 期货推动是否会改变洲际交易所 (ICE) 的投资案例？",
    "summary_cn": "ICE 创纪录的能源 OI 和 GPU 期货推动是否会改变洲际交易所 (ICE) 的投资案例？&nbsp;&nbsp;simplywall.st",
    "translated": true
  },
  {
    "title": "09:32:37【香港交易所回应“算力期货布局规划”：暂无评论可提供，将来如有相关信息将及时公布】",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE5tVldKenNwOVBXSUhyZV8tNFQ2SXJ3cGNJU3hqMko5Ykk0M2xtR0V4NjJyRkFUQjk5N0JTOUdnNWpuWFMzRFkybA?oc=5",
    "published": "2026-05-25",
    "summary": "09:32:37【香港交易所回应“算力期货布局规划”：暂无评论可提供，将来如有相关信息将及时公布】&nbsp;&nbsp;财联社",
    "full_text": "「09:32:37【香港交易所回应“算力期货布局规划”：暂无评论可提供，将来如有相关信息将及时公布】」\n\n📰 来源：财联社\n📅 发布日期：2026-05-25\n\n本文由 Google News 聚合自 财联社。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Wall Street giants are scrambling to buy GPU futures, the crypto market has already begun its battle.",
    "source": "PANews",
    "source_url": "https://www.panewslab.com",
    "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTFB0YWFJOWxjejBsbnZDMmh3OUJwcUhGbVltSmNYQm5XWlZ0ME5VSFBrdjVLekh4Mjk1U0xhQmJSU2FjZUxobkU5cVNlQmdSd0pqQ2d3VWhVUG03UWhFbm5UcWRDMHc0aGxvN0ZfMlI5eUk4OUd1b2ZVUlFqT09aM3M?oc=5",
    "published": "2026-05-22",
    "summary": "Wall Street giants are scrambling to buy GPU futures, the crypto market has already begun its battle.&nbsp;&nbsp;PANews",
    "full_text": "「华尔街巨头争先恐后买入GPU期货，加密市场已然打响。」\n\n📰 Source: PANews\n📅 Published: 2026-05-22\n\nOriginal title: Wall Street giants are scrambling to buy GPU futures, the crypto market has already begun its battle.\n\nThis article is aggregated from PANews via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "华尔街巨头争先恐后买入GPU期货，加密市场已然打响。",
    "summary_cn": "华尔街巨头争相买入GPU期货，加密市场已然打响。&nbsp;&nbsp;PANews",
    "translated": true
  },
  {
    "title": "华尔街巨头抢滩GPU期货，加密市场已经提前开打",
    "source": "PANews",
    "source_url": "https://www.panewslab.com",
    "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE1QUEo2d1ZWQmxqNUU1N1hFSDZrZjZaNW04ejdMUk13R3VjdHhsSi1wSnZxZGpMUExoazNWN1ZqWklUVG5INE9mRHpGWmhqZ3k5Vjd6SVdEUFFvanJScHdfandSQ2hsc2Y4U1otY2FoTWhxamI4UUtYbFhFbmxmQW8?oc=5",
    "published": "2026-05-22",
    "summary": "华尔街巨头抢滩GPU期货，加密市场已经提前开打&nbsp;&nbsp;PANews",
    "full_text": "「华尔街巨头抢滩GPU期货，加密市场已经提前开打」\n\n📰 来源：PANews\n📅 发布日期：2026-05-22\n\n本文由 Google News 聚合自 PANews。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "当算力可以像期货一样交易，会发生什么",
    "source": "thepaper.cn",
    "source_url": "https://m.thepaper.cn",
    "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTFBiOXc2czRaX3FrbmNWRnZhRGI2UWl5NXFLTXh2R0s2ZUZoYVFSOVdZeWJ5R2g2ZGNNallwSUM2Tk5UZm1lQjBXMm5va1BNeG1DdjhTU3NlQWdvNVV5SWc?oc=5",
    "published": "2026-05-22",
    "summary": "当算力可以像期货一样交易，会发生什么&nbsp;&nbsp;thepaper.cn",
    "full_text": "「当算力可以像期货一样交易，会发生什么」\n\n📰 来源：thepaper.cn\n📅 发布日期：2026-05-22\n\n本文由 Google News 聚合自 thepaper.cn。点击下方「文章来源」链接可在浏览器中自动跳转到原始文章页面，阅读完整内容。\n\n💡 提示：本栏目聚焦 GPU 算力期货市场动态，涵盖芝商所（CME）、洲际交易所（ICE）、Silicon Data 等机构推出的算力期货/衍生品合约，以及高盛、摩根大通等华尔街机构在算力金融化领域的布局。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Intercontinental Exchange and Ornn Launching Suite Of GPU Compute Futures Contracts",
    "source": "Pulse 2.0",
    "source_url": "https://pulse2.com",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQTGcxRW5oVkliWDl3VlJlZHlvU25iUlZIVTVTU1N0Nm9SaUwtbTBsb1NBelI5NmMwUkFFdS1Pb0kzSTc3VVUyZVE1aFNEdU9WY2M0Y05fNGNUYUZiSzlNZ0Nuano2eU5UMkZJdjV3VjJWa2VJd2pZVWZpX3JOYkVqSENLR1R0LWlvOFNGVkF5bXhoZHNtYjVLUGtZT0NCNlB0QUYzcXhn0gGrAUFVX3lxTFBvNmFGcEpBelNLbHlDSEhuamxSUG0xUVZiUE0xTWxESVpxTjlyT3BydFg5Q1RGWnYzckt0QXBLbkx0bWZ0LVdSM2FIMGJUVkVOeWhNMDRsTFgtNHpLWEZzd0JyekFQZzVkazAtS1hOdWc4azUxTzItWmxVSVhCSFF6dFRTZzNFaTFNVmx4R09YYmtmbmdNYks4X1VjcWx3dFJDS0tLWlR4bkdwYw?oc=5",
    "published": "2026-05-21",
    "summary": "Intercontinental Exchange and Ornn Launching Suite Of GPU Compute Futures Contracts&nbsp;&nbsp;Pulse 2.0",
    "full_text": "「洲际交易所和 Ornn 推出 GPU 计算期货合约套件」\n\n📰 Source: Pulse 2.0\n📅 Published: 2026-05-21\n\nOriginal title: Intercontinental Exchange and Ornn Launching Suite Of GPU Compute Futures Contracts\n\nThis article is aggregated from Pulse 2.0 via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "洲际交易所和 Ornn 推出 GPU 计算期货合约套件",
    "summary_cn": "洲际交易所和 Ornn 推出 GPU 计算期货合约套件 Pulse 2.0",
    "translated": true
  },
  {
    "title": "Intercontinental Exchange (ICE) To Launch GPU Compute Futures Contracts Suite To Bring Transparency To GPU Costs",
    "source": "Yahoo Finance",
    "source_url": "https://finance.yahoo.com",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNX1FXLXBxbTNoMnZqVkVZVmF0QXF6YVR3ZmJDdjExSlBsNUpIRm9BZzhSeTZKU0t0MFo3dXVxRExsMWR1YmFPR0hQZUhHaE13YW9CSGxXVHhLdUZTQnFLTXUzSmtuNjVIU2pqYTBteWIxM1l6dHRVUGxuMUFGellaYUd0ZFZ2YVNyanhEcG9qRmJkeEU0QTgtWWVRTlg3U0d0NGVFMy1IOWJ4QQ?oc=5",
    "published": "2026-05-21",
    "summary": "Intercontinental Exchange (ICE) To Launch GPU Compute Futures Contracts Suite To Bring Transparency To GPU Costs&nbsp;&nbsp;Yahoo Finance",
    "full_text": "「洲际交易所 (ICE) 将推出 GPU 计算期货合约套件，以提高 GPU 成本的透明度」\n\n📰 Source: Yahoo Finance\n📅 Published: 2026-05-21\n\nOriginal title: Intercontinental Exchange (ICE) To Launch GPU Compute Futures Contracts Suite To Bring Transparency To GPU Costs\n\nThis article is aggregated from Yahoo Finance via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "洲际交易所 (ICE) 将推出 GPU 计算期货合约套件，以提高 GPU 成本的透明度",
    "summary_cn": "洲际交易所 (ICE) 将推出 GPU 计算期货合约套件，以提高 GPU 成本的透明度 雅虎财经",
    "translated": true
  },
  {
    "title": "How ICE’s Planned GPU Compute Futures Could Reshape Intercontinental Exchange (ICE) Investors’ AI Narrative",
    "source": "Yahoo Finance",
    "source_url": "https://finance.yahoo.com",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxPWVEySmJjaUhNUlZrV1RfSUlTaW9PdEEwOC05MjBaa05EaXlnck1YX1V1YW01VFoyMGRGMTlqZ2NfbnhMb19FZGFGS3MyS2loSjU5ZllLUFBQbnhZZHFkUjBDckQyQm05VzlVU3NmOHR6TDBjRjdTVzVlVGRaM29FMENjYWhzOEZpSkd4WGNlbTFlZmNGRVFlVnV5TGx5QQ?oc=5",
    "published": "2026-05-20",
    "summary": "How ICE’s Planned GPU Compute Futures Could Reshape Intercontinental Exchange (ICE) Investors’ AI Narrative&nbsp;&nbsp;Yahoo Finance",
    "full_text": "「ICE 计划的 GPU 计算未来如何重塑洲际交易所 (ICE) 投资者的人工智能叙事」\n\n📰 Source: Yahoo Finance\n📅 Published: 2026-05-20\n\nOriginal title: How ICE’s Planned GPU Compute Futures Could Reshape Intercontinental Exchange (ICE) Investors’ AI Narrative\n\nThis article is aggregated from Yahoo Finance via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "ICE 计划的 GPU 计算未来如何重塑洲际交易所 (ICE) 投资者的人工智能叙事",
    "summary_cn": "ICE 计划的 GPU 计算未来如何重塑洲际交易所 (ICE) 投资者的人工智能叙事 雅虎财经",
    "translated": true
  },
  {
    "title": "DERIVSOURCE: CME Group, Silicon Data to Launch Futures for Computing Power",
    "source": "Traders Magazine",
    "source_url": "https://www.tradersmagazine.com",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOcDZLaktzYVM0NW5xUjB1eDBGUkRPMFlXdXhhX1M3RGEwcjFiMGQ5cEVkbnkyY19SNTdvMWpxenhYdzMzSGc5NjZnaG1wQ3JmNVdDeHhZbW1wZU4weUNjLTBXTmh4ZEJrUXp5MVdiUV9NWkN1NzBsUW9zSXM2cUFYTzJzeDhUbkNNd2pGeVBQVFYwZ0VwSnpXZmNyOEFhZFRxTjhTb1l3MXNfVFFILVdzV09zWW95SkFS?oc=5",
    "published": "2026-05-20",
    "summary": "DERIVSOURCE: CME Group, Silicon Data to Launch Futures for Computing Power&nbsp;&nbsp;Traders Magazine",
    "full_text": "「DERIVSOURCE：CME 集团与 Silicon Data 推出计算能力期货」\n\n📰 Source: Traders Magazine\n📅 Published: 2026-05-20\n\nOriginal title: DERIVSOURCE: CME Group, Silicon Data to Launch Futures for Computing Power\n\nThis article is aggregated from Traders Magazine via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "DERIVSOURCE：CME 集团与 Silicon Data 推出计算能力期货",
    "summary_cn": "DERIVSOURCE：CME 集团和 Silicon Data 将推出计算能力期货交易者杂志",
    "translated": true
  },
  {
    "title": "ICE moves to list futures on GPU compute, putting AI infrastructure on the trading floor",
    "source": "Startup Fortune",
    "source_url": "https://startupfortune.com",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPUDhmdjk2bWx1OGFXMy1acXhYTmJIaFpKajh1X3dpWVE5V1NuaUpwYUVwTVFhRlduSEhsdnE4MzdkUGhDRmZvZUY0enlNQ1BJcDFIcGQ4R0JuSlNNMnJkbERzWTBpRTJZLVBZVk1aQWQtTmlKY0RpOWNERDVfaHBHU3JLVHBtcV9rcF9KcXVYd1VUVzdUb2M2YVI3dTZPZzBRLXN0NXoxUTEzTGd0cW1NdHFZdWRRQQ?oc=5",
    "published": "2026-05-19",
    "summary": "ICE moves to list futures on GPU compute, putting AI infrastructure on the trading floor&nbsp;&nbsp;Startup Fortune",
    "full_text": "「ICE moves to list futures on GPU compute, putting AI infrastructure on the trading floor」\n\n📰 Source: Startup Fortune\n📅 Published: 2026-05-19\n\nOriginal title: ICE moves to list futures on GPU compute, putting AI infrastructure on the trading floor\n\nThis article is aggregated from Startup Fortune via Google News. Click the source link below to read the full article. The Google News link will automatically redirect you to the original article page.\n\n💡 This section focuses on GPU compute futures market developments, including CME Group, ICE, Silicon Data compute futures contracts, and Wall Street's involvement in compute financialization.",
    "images": [],
    "lang": "en",
    "title_cn": "",
    "summary_cn": "ICE 开始上市 GPU 计算期货，将人工智能基础设施置于交易大厅 创业财富",
    "translated": true
  }
];
