// GPU算力期货新闻
// 生成: 2026-06-13T03:56:48Z
var NEWS_FETCHED_AT = "2026-06-13T03:56:48Z";
var GPU_NEWS = [
  {
    "title": "AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFB1NXZMVWl6N1JYV2xKd0V1ajlGdk1Dem10ajR5RUx6WXJpc1FoV3N4OFJvdHZfdXFjUFJDSi1zR0gxeWhTZWM5Nw?oc=5",
    "published": "2026-06-12",
    "summary": "AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场&nbsp;&nbsp;财联社",
    "full_text": "AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场&nbsp;&nbsp;财联社",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "贝莱德CEO预言：需求如此巨大 算力期货市场终将诞生",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE84MXdmRXdRUFRFb213eWhseWpvdTkxOVo5cFJuQm1WWTAwT0RIZkRCd09ST2FyR2FRNnVrR2U3UWd1TW5RNWt5cw?oc=5",
    "published": "2026-06-12",
    "summary": "贝莱德CEO预言：需求如此巨大 算力期货市场终将诞生&nbsp;&nbsp;财联社",
    "full_text": "贝莱德CEO预言：需求如此巨大 算力期货市场终将诞生&nbsp;&nbsp;财联社",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "万亿AI投资急需风险对冲 算力期货闯关多题待解",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE84dGlCTnFpanc2Qm9xbTdnU0dKaGNwQU9XdW1tU0ZLRkxPQkNJaTlrU1ZmbVkyV3VVUzl2NnJyXzNVTTRqWUR0bVE1dDFTZ0k5QUs3MFlFX0kwOEdsZkdWcGlKNzdhNDVqb210NFNwbS1iLTF0N2g0cw?oc=5",
    "published": "2026-06-12",
    "summary": "万亿AI投资急需风险对冲 算力期货闯关多题待解&nbsp;&nbsp;Sina finance",
    "full_text": "万亿AI投资急需风险对冲 算力期货闯关多题待解&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力金融化“寻锚”",
    "source": "腾讯新闻",
    "source_url": "https://news.qq.com",
    "url": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5iUXRFWExEUklDWmc4OVRnYWs0TENfVGJtVy14V0MxOFhPZnpwOEVPa2VxM0NtSUk1dWxHbS13WFJNRGEtbTY5dVFmQXdxd2VyRlpTSHpR?oc=5",
    "published": "2026-06-11",
    "summary": "算力金融化“寻锚”&nbsp;&nbsp;腾讯新闻",
    "full_text": "算力金融化“寻锚”&nbsp;&nbsp;腾讯新闻",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "推出算力期货，存在哪些痛点？",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxQdl9LTW5sNWoxWFp6MmVNZ1lpSndib1pVRFFwWktKdDNad0J6ZjBiMURRdmlQcy1JdWZSNU5mZmxZTlIwa3lmcXZFWVZXSlRQVFRNd3lZbGZIanJzTVJPbmFXdk5VNVYySW1sbFlVMlh5ZHpzeVFJdTlySURrUVdyYnhXRXBxRDBkUnYzVw?oc=5",
    "published": "2026-06-11",
    "summary": "推出算力期货，存在哪些痛点？&nbsp;&nbsp;Sina finance",
    "full_text": "推出算力期货，存在哪些痛点？&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Demand",
    "source": "GuruFocus",
    "source_url": "https://www.gurufocus.com",
    "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPclFSSHpBX2hWRVRidnNQajlWWngybEtsNnFvRmdKbVNEdVF6TnBjYVpfb1l1X01zU1RzMFNYeGRaMVlkXzYweEJXMFRoNVhrcHBpR0Qyck1wYWlrMnd5WmREenlFSGlWVk16VnVKaHQwTW5qMUZLWVhPMGVOMDNJMi1wUVpQSEtYNC1FNjBEbVQ0ZkNxX1J3Y0I1dlZZcVBHVll2Qkk3UzFTck91dTUtQXh3?oc=5",
    "published": "2026-06-09",
    "summary": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Demand&nbsp;&nbsp;GuruFocus",
    "full_text": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Demand&nbsp;&nbsp;GuruFocus",
    "images": [],
    "lang": "en",
    "title_cn": "高盛和摩根大通在人工智能需求中探索 GPU 未来",
    "summary_cn": "高盛和摩根大通在人工智能需求中探索 GPU 未来 &nbsp;&nbsp;GuruFocus",
    "translated": true
  },
  {
    "title": "Goldman, JPMorgan Explore AI Compute Futures Trading",
    "source": "Let's Data Science",
    "source_url": "https://letsdatascience.com",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxNMlFXSWpxMkVLVTEtd0sweTdqazVCZzl2cmo0bkZCSFZpSmo0dENILXdKcGRteHd0LUlCaHVudmZLM1dkVURnSVNPaFNjTmoxSGtscXpkLXJBNHkteTBTaWt4XzIweVBKQkJLeHBMcnhuR1ZlQkd6cHJ1ZWlTZTlNZzVYODRRQjFGVU5LX3RJd0k5UkRJa2dKdQ?oc=5",
    "published": "2026-06-09",
    "summary": "Goldman, JPMorgan Explore AI Compute Futures Trading&nbsp;&nbsp;Let's Data Science",
    "full_text": "Goldman, JPMorgan Explore AI Compute Futures Trading&nbsp;&nbsp;Let's Data Science",
    "images": [],
    "lang": "en",
    "title_cn": "高盛、摩根大通探索人工智能计算期货交易",
    "summary_cn": "高盛、摩根大通探索人工智能计算期货交易&nbsp;&nbsp;让我们数据科学",
    "translated": true
  },
  {
    "title": "高盛与摩根大通探索算力期货交易以对冲AI融资风险 多家交易所与机构争相布局新兴市场",
    "source": "太平洋科技",
    "source_url": "http://news.pconline.com.cn",
    "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE00Y292blNxamJDUkRiODJPZFk0Y2VsMEZPNkhUSllXbXFIQ0tyV0ZNMFJQUV9oOER6UEZHd3ZTVE5FdjFxY3pLMy1KRXZfUVZIZVM5ZHp1WUZSdw?oc=5",
    "published": "2026-06-09",
    "summary": "高盛与摩根大通探索算力期货交易以对冲AI融资风险 多家交易所与机构争相布局新兴市场&nbsp;&nbsp;太平洋科技",
    "full_text": "高盛与摩根大通探索算力期货交易以对冲AI融资风险 多家交易所与机构争相布局新兴市场&nbsp;&nbsp;太平洋科技",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "高盛、摩根大通探索算力期货交易，用作AI融资风险对冲工具",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxQY0dJWjlNbUFPVHdzSVo0VWpTd3ZaZ0VPQTk2QzNTTFRCWkVYNmV3Vk94aElwX0dFM0VOUG5vcE4xcU1SUGx0cXYtY1U2eWZpODVGQTZMdFlzYkJBUkh2WjAtbUtYQ1ZKMUR0WkdBTi1yUnFoYzg4WWRkcUdObzU0SXZmRVVHanM?oc=5",
    "published": "2026-06-09",
    "summary": "高盛、摩根大通探索算力期货交易，用作AI融资风险对冲工具&nbsp;&nbsp;Sina finance",
    "full_text": "高盛、摩根大通探索算力期货交易，用作AI融资风险对冲工具&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "高盛摩根大通探索算力期货交易 为AI融资风险对冲助力",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE1vZVpHSURNaWtKQjNDUk85TGQ0bDNWTFZRQkotMF9xRUVjRExMVHIxZUFxSzV1S1Jwb3JkMmp6dUd1b2VyZXR3T2o1SU5Cam9MTGMxeWJCTVZZcGJmXzh1MWp6OE5rY2h6TVVpem9OcFJoMjRySkN2YQ?oc=5",
    "published": "2026-06-09",
    "summary": "高盛摩根大通探索算力期货交易 为AI融资风险对冲助力&nbsp;&nbsp;Sina finance",
    "full_text": "高盛摩根大通探索算力期货交易 为AI融资风险对冲助力&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Boom",
    "source": "GuruFocus",
    "source_url": "https://www.gurufocus.com",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNdXlZUmlVdTM2MWFlM0hqTTZ5X09nd1pFQ2xKRXdDZURxNEJBUFlJTklsVmVKZDlleHlaMkc5bnA4MFFhZVdOd3JKTWI4dHg0MFlhaWI3Wm9selRoTzhfXzJHY2VYdnR0SjJOTUZYQ19Cd19wR0xCZFpqZEN0YnhSQVp3ay0xdW41Wno1TFZaaWt2ak0yZmNHRU5vekt6anhqWmJReHI3ZlpfMWdaa1dz?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Boom&nbsp;&nbsp;GuruFocus",
    "full_text": "Goldman Sachs and JPMorgan Explore GPU Futures Amid AI Boom&nbsp;&nbsp;GuruFocus",
    "images": [],
    "lang": "en",
    "title_cn": "高盛和摩根大通在人工智能热潮中探索 GPU 未来",
    "summary_cn": "高盛和摩根大通在人工智能热潮中探索 GPU 未来 &nbsp;&nbsp;GuruFocus",
    "translated": true
  },
  {
    "title": "Goldman Sachs and JPMorgan Chase explore the financialization of computing power, planning to launch GPU leasing futures to hedge AI risks",
    "source": "WEEX",
    "source_url": "https://www.weex.com",
    "url": "https://news.google.com/rss/articles/CBMioAJBVV95cUxQMnZOeXZnQWtrbUt4MXFfdW9lY3FORHBsNmRheFVQeGFLQzJ5ZElsWkF1aHBHVjRRU0xwM2xXaWVfTFd2MWp6c3l3cEtzeDhTWWMyUmdWeXVZejlNUU9OUjg4Y3dIbTZqM044Qm1FelEtTlBoVW1RMW5NS3hfVzdxTkxvaklObHRXWDJrYS16ZEZQUUphLTlONm1YWWNNdDVYdktPS0dZcURYNUUtYmNpcUE5LU1yLXRhbndOblBNRFROVmR3cGY0UW11RmRSZjI1NWxHQlVHYkgtY0E5aVU4U19EN2VXSlBwWjNjb3JzZGI1REoxbDFyMHRITlQyMG9qVGNLOUMyMmk4bnhHUWZZZHgyUUZGVDkxRXRDMFlBTHk?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman Sachs and JPMorgan Chase explore the financialization of computing power, planning to launch GPU leasing futures to hedge AI risks&nbsp;&nbsp;WEEX",
    "full_text": "Goldman Sachs and JPMorgan Chase explore the financialization of computing power, planning to launch GPU leasing futures to hedge AI risks&nbsp;&nbsp;WEEX",
    "images": [],
    "lang": "en",
    "title_cn": "高盛联手摩根大通探索算力金融化，拟推出GPU租赁期货对冲AI风险",
    "summary_cn": "高盛携手摩根大通探索算力金融化，计划推出GPU租赁期货对冲AI风险 WEEX",
    "translated": true
  },
  {
    "title": "Goldman Sachs and JPMorgan explore the financialization of computing power, planning to launch GPU rental futures to hedge AI risks",
    "source": "Bitget",
    "source_url": "https://www.bitget.com",
    "url": "https://news.google.com/rss/articles/CBMiY0FVX3lxTE1OZ1U2TTE5aHBXVTFlWFpEd1VpSTZ6ZXdhLVZrbGxSQmo0U3N4WmZEdW9jMlEwS2kzSXphcXJodmNPSEdzY21keVFrVFNsSlo2dGxZX2pCV05TWXk2dXhmUnk2a9IBY0FVX3lxTE1OZ1U2TTE5aHBXVTFlWFpEd1VpSTZ6ZXdhLVZrbGxSQmo0U3N4WmZEdW9jMlEwS2kzSXphcXJodmNPSEdzY21keVFrVFNsSlo2dGxZX2pCV05TWXk2dXhmUnk2aw?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman Sachs and JPMorgan explore the financialization of computing power, planning to launch GPU rental futures to hedge AI risks&nbsp;&nbsp;Bitget",
    "full_text": "Goldman Sachs and JPMorgan explore the financialization of computing power, planning to launch GPU rental futures to hedge AI risks&nbsp;&nbsp;Bitget",
    "images": [],
    "lang": "en",
    "title_cn": "高盛与摩根大通探索算力金融化，计划推出GPU租赁期货对冲AI风险",
    "summary_cn": "高盛与摩根大通探索算力金融化，计划推出GPU租赁期货对冲AI风险 Bitget",
    "translated": true
  },
  {
    "title": "Wall Street Tests New Ways To Price AI Compute",
    "source": "Finimize",
    "source_url": "https://finimize.com",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxObUsxeDNKQTN1c2pLZEdyR3JfX014THpHLXNXNUx5d1hlUEVFcEkyU1J6N2FiR1ZtbEU5VnFOSDFzOXIyWEl1R2tERE9BelVlRlQxSGlBWi1pQmxSM05DWXcwUncxM0J2dWV2Y25RMWttQ3N0TVZDbWxLMEZtY0Y5Uw?oc=5",
    "published": "2026-06-08",
    "summary": "Wall Street Tests New Ways To Price AI Compute&nbsp;&nbsp;Finimize",
    "full_text": "Wall Street Tests New Ways To Price AI Compute&nbsp;&nbsp;Finimize",
    "images": [],
    "lang": "en",
    "title_cn": "华尔街测试人工智能计算定价的新方法",
    "summary_cn": "华尔街测试人工智能计算定价的新方法",
    "translated": true
  },
  {
    "title": "Goldman, JPMorgan Explore Trading Compute Futures as AI Financing Hedge",
    "source": "The Information",
    "source_url": "https://www.theinformation.com",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxQalQyZEs0bnljOE5xZHkyRDliYk1GSnJHUXRraUdIbWhBUGtfSl9NcE5tQ2NfRXRPd3VsazA1VHcwdFRGTXBaNGZmWUJ1RnRUTnEyVVFiUDRFWWdaaVBYUEJqXzVBMzd1MklNWFBVSFdSaFZJemVEdHh1RGwtYUQycjFTaTN4V09paXNmcG11eF9tRTE0Y1FLNG9LUQ?oc=5",
    "published": "2026-06-08",
    "summary": "Goldman, JPMorgan Explore Trading Compute Futures as AI Financing Hedge&nbsp;&nbsp;The Information",
    "full_text": "Goldman, JPMorgan Explore Trading Compute Futures as AI Financing Hedge&nbsp;&nbsp;The Information",
    "images": [],
    "lang": "en",
    "title_cn": "高盛和摩根大通探索计算期货交易作为人工智能融资对冲",
    "summary_cn": "高盛和摩根大通探索计算期货交易作为人工智能融资对冲&nbsp;&nbsp;信息",
    "translated": true
  },
  {
    "title": "高盛和摩根大通考虑推出与GPU租赁价格挂钩的期货",
    "source": "富途牛牛",
    "source_url": "https://news.futunn.com",
    "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE1pVVRCMTNUT21zaklCb0YtbHpEU2R1UGhYWTFaX2Q3UFUzTzJLTkgtS05iNXVxaXdTOVlxLWxkaElpWHZXNXFNbHVkV3k2dw?oc=5",
    "published": "2026-06-08",
    "summary": "高盛和摩根大通考虑推出与GPU租赁价格挂钩的期货&nbsp;&nbsp;富途牛牛",
    "full_text": "高盛和摩根大通考虑推出与GPU租赁价格挂钩的期货&nbsp;&nbsp;富途牛牛",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "经济学家宋清辉：算力期货孕育A股新机遇，四大板块料享红利",
    "source": "财经号",
    "source_url": "http://mp.cnfol.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE42SzFTSjFHQk5Ja1owMGJRQU54QWc0bF80clJ4M0hzQ2dEdm9PaWNJQlU1eUZKdmZ4Z0ZudU12RTExTkVhVThiaUJqcU1vek83cEpqNk5HdFB4RVIxRF9OcG5hb3JlOHNLVDNJ?oc=5",
    "published": "2026-06-08",
    "summary": "经济学家宋清辉：算力期货孕育A股新机遇，四大板块料享红利&nbsp;&nbsp;财经号",
    "full_text": "经济学家宋清辉：算力期货孕育A股新机遇，四大板块料享红利&nbsp;&nbsp;财经号",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI的新价格语言，算力何以成期货",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMihwFBVV95cUxPODYwTkp4R3dYbDdCRUpkWTF1S2dsbGFnNmxjRXZtcmhHcVJ3OEkteWZNQkEyNUlxMDZRZ1pRRmFDeGNhRkxwWERkMld6Vzg3UjFRVHJlc1kzdmdGSlIyaHpNQ2pxTlMzZXhMTzNzSC1rV3FfZVJCWkZVekptT2lSMDFNNVVKZmc?oc=5",
    "published": "2026-06-08",
    "summary": "AI的新价格语言，算力何以成期货&nbsp;&nbsp;Sina finance",
    "full_text": "AI的新价格语言，算力何以成期货&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "高盛与摩根大通探索算力金融化，拟推出 GPU 租赁期货对冲 AI 风险",
    "source": "Bitget",
    "source_url": "https://www.bitget.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE9lRlhVOGUwb1dqdTNVcmhLeTZ4SlloSkZHS2JYby1vSUhnVThwWk1HOTdWdzFpdDQ5UU12RDR1dUNsZmVaUmdnUm1EazFaeUZPNHhFWm1iT3FRSE9MOGdwVUQ5Q1lhUdIBa0FVX3lxTFA5RGw5aDQ2cDRPYjAxczJSRUE1T2ZtVWZEZzNOZkpyVE9hblkxN215VUNoaEpZSG1nR1pTdGY4N0JLNmtEUnVhQ3UtMnpKMnJjVnNqLVJXWnR5anRNdGYxV1M2dWllRjAzMlBn?oc=5",
    "published": "2026-06-07",
    "summary": "高盛与摩根大通探索算力金融化，拟推出 GPU 租赁期货对冲 AI 风险&nbsp;&nbsp;Bitget",
    "full_text": "高盛与摩根大通探索算力金融化，拟推出 GPU 租赁期货对冲 AI 风险&nbsp;&nbsp;Bitget",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Why benchmark integrity will determine the success of India’s electricity futures",
    "source": "ET Edge Insights",
    "source_url": "https://etedge-insights.com",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxPYlBBZHhldmo0NEZMTmJ3aWNBc3FNQ2hBb1F4ZUNCMWlRNzJDeEhYeXQwckVvTGY3WlBpNEY2ZERycTJKT0JKbHliQUZDeGdoenVQNTAxbVpOcmNmc2l0cmNpWU9NQVRFNVZ0VG0yWGtWRTZiS21ZNElJZmNjLURoc1BlTGRtTnN1Wm9RN05STXluRFlDNkczeHBCd2IyR0lVTzV5LXZQZzhXMENFbUQwWXNFeWg3OEc3?oc=5",
    "published": "2026-06-06",
    "summary": "Why benchmark integrity will determine the success of India’s electricity futures&nbsp;&nbsp;ET Edge Insights",
    "full_text": "Why benchmark integrity will determine the success of India’s electricity futures&nbsp;&nbsp;ET Edge Insights",
    "images": [],
    "lang": "en",
    "title_cn": "为什么基准完整性将决定印度电力期货的成功",
    "summary_cn": "为什么基准完整性将决定印度电力期货的成功 ET Edge Insights",
    "translated": true
  },
  {
    "title": "新华能源周报丨上海：做好电力期货、算力期货研发准备；今夏国家电网最大用电负荷同比增约6%",
    "source": "新华网",
    "source_url": "https://www.news.cn",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxQV3BJX053bkFiNGk4UmlKOWhNVmVZU2gzNDNqRFhzRFkwVHlhYTAtNWZORzVHdkVsTnYxSGhpVDZVZ3c4S1VLRGdOeEFPY0N1SHdaR1BqUkl3ZUJUMWdPU3k2T3VzamxDUE5kZktFRjdQR09mYnpPVmwybFZwNGJnbw?oc=5",
    "published": "2026-06-05",
    "summary": "新华能源周报丨上海：做好电力期货、算力期货研发准备；今夏国家电网最大用电负荷同比增约6%&nbsp;&nbsp;新华网",
    "full_text": "新华能源周报丨上海：做好电力期货、算力期货研发准备；今夏国家电网最大用电负荷同比增约6%&nbsp;&nbsp;新华网",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力期货提上日程，市场布局新赛道",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5BQ0VvaE9haGFxUERxODBVbFRlSGZJaDdvN2dPTjU3eUZmcFpKZWVld3E2RkcxTW03WDMzeFV6WVZ5bmZIdk9FbDJUX3I5aWlEMzhmOXJKYW4tVWRCQ3dIYnQ0dkJ5cEhPdUVv?oc=5",
    "published": "2026-06-05",
    "summary": "算力期货提上日程，市场布局新赛道&nbsp;&nbsp;财富号",
    "full_text": "算力期货提上日程，市场布局新赛道&nbsp;&nbsp;财富号",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "薛鹤翔：算力期货将引领AI产业迭代与体系重塑——算力期货专题报告",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE5udWRCbl9mcjJEdjRsODR5cUNROTVKWHcwVlBHYXpveDJ0aHo0U3BhYzNKMVJiSEJ1ZDNBSW5CQ0Y3Uk1NSWJqTGhiOUczMjYwZGdaVGRBcTJSeGw5MDVIWFAyOGxhMHg4dS1KWHdmeERydG9GTEE?oc=5",
    "published": "2026-06-05",
    "summary": "薛鹤翔：算力期货将引领AI产业迭代与体系重塑——算力期货专题报告&nbsp;&nbsp;Sina finance",
    "full_text": "薛鹤翔：算力期货将引领AI产业迭代与体系重塑——算力期货专题报告&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "无锡金融委：推出算力期货 国联民生将发挥什么作用？",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxOQ0QwbUtkZjZHUURQbi1FbE82aVVVTVJCZk9YQmdJQjVQdTJqQ3VzZ19qWWZ2d2d2aXd5TWNva1VaTXdVVDR4SWJLLXhfc29pa21vaE9tcmg5Q3FibWJFWlByLU83YXV2RVpTLUEwbmNhV3BYZ0VWNk9sZEFPdXBjNHl3d0NoNlo2?oc=5",
    "published": "2026-06-05",
    "summary": "无锡金融委：推出算力期货 国联民生将发挥什么作用？&nbsp;&nbsp;Sina finance",
    "full_text": "无锡金融委：推出算力期货 国联民生将发挥什么作用？&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海市发文做好\"算力期货\"研发准备",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE1GUnVSV21NYjNreHpOdE9jTHJUUjVkWmlLTFBIb0hoTnViZ3g4aklkNjNZNkJoV2hIRWtqUEFKSG5xa3RQdlVMQjN6Q0NMV293bGVNOHViLW9FN0RmVkp2TUh6TTNhd2gtUUFfalBjbGxnUHZFQnc?oc=5",
    "published": "2026-06-04",
    "summary": "上海市发文做好\"算力期货\"研发准备&nbsp;&nbsp;Sina finance",
    "full_text": "上海市发文做好\"算力期货\"研发准备&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海提出做好算力期货研发准备 还需跨越这些坎",
    "source": "东方财富",
    "source_url": "https://wap.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE9UTDhtVHotYTZKRDNsa25Od3NESVRtRVFJWlh5RWtYR0I4dGVqRXdhRmRrYm9VTzdIbzlSSERfUzVuZW15UUt4UFlrNkVobzVFRkpHU0p1TUJUX21NZXRUSg?oc=5",
    "published": "2026-06-04",
    "summary": "上海提出做好算力期货研发准备 还需跨越这些坎&nbsp;&nbsp;东方财富",
    "full_text": "上海提出做好算力期货研发准备 还需跨越这些坎&nbsp;&nbsp;东方财富",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI时代的“算力”期货市场什么样？",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE5ORXM3UVlMLU1ZTVFWbzBHa3ljU0JwZXlGTW9GbVV6MGJseHNXZ1JFaTlYeTI5cHk4bWg1VVdjZDV1OGViQXdjbkh3LUQ5WGFJMk9iOXBsRWllOXd5a2ZkSlNwX083QU5TRXRPRzBfZnNEcG9VYVE?oc=5",
    "published": "2026-06-04",
    "summary": "AI时代的“算力”期货市场什么样？&nbsp;&nbsp;Sina finance",
    "full_text": "AI时代的“算力”期货市场什么样？&nbsp;&nbsp;Sina finance",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海明确加快推出液化天然气期货期权，研发电力、算力期货",
    "source": "新浪财经",
    "source_url": "https://cj.sina.cn",
    "url": "https://news.google.com/rss/articles/CBMib0FVX3lxTFBfSTBuZFpqRDA5T1l2RE5xWXBfWGNQTWwtVlNBdjNCVU9MdmhRRlByTjVtRDZFYUR6X1dwX1RkTzhxREwyQ2J5Z1d1YzREcjItNFFRUW5oYnAyMWlJZTlrZkc0ZHYzWVo5UXlVNFUxTQ?oc=5",
    "published": "2026-06-03",
    "summary": "上海明确加快推出液化天然气期货期权，研发电力、算力期货&nbsp;&nbsp;新浪财经",
    "full_text": "上海明确加快推出液化天然气期货期权，研发电力、算力期货&nbsp;&nbsp;新浪财经",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "6月3日早餐 | 上海推动算力期货研发；美英伟达CPO交换机全面量产",
    "source": "Sohu",
    "source_url": "https://www.sohu.com",
    "url": "https://news.google.com/rss/articles/CBMiUkFVX3lxTE8tU0FENUp5bXFkUnY4VEpmZGtZWkZHN0ozTnFTaW5KS3dsWXNaV2RKdVpud0huNlRhRDI4MUZDSTItaUgtVkdCdjhaYWhpQUtDeUE?oc=5",
    "published": "2026-06-03",
    "summary": "6月3日早餐 | 上海推动算力期货研发；美英伟达CPO交换机全面量产&nbsp;&nbsp;Sohu",
    "full_text": "6月3日早餐 | 上海推动算力期货研发；美英伟达CPO交换机全面量产&nbsp;&nbsp;Sohu",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "全球算力定价权将花落谁家？上海宣布研发算力期货 抢占数字经济新高地",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFAyMlYyVmI3b0VFaU9halRSODExbTJjZWtLam5aUXV6TUM2WjJzZU1WbFNHeWs0cW5vbEREZFBjVkR2OXZHbzFCNmh6UE0wY0lSVnFNWUVrbXlDZFlWaDBLRWJwT2ZTQQ?oc=5",
    "published": "2026-06-03",
    "summary": "全球算力定价权将花落谁家？上海宣布研发算力期货 抢占数字经济新高地&nbsp;&nbsp;东方财富",
    "full_text": "全球算力定价权将花落谁家？上海宣布研发算力期货 抢占数字经济新高地&nbsp;&nbsp;东方财富",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "布局电力、算力等期货，推动科创50等股指期货期权上市，“上海价格”影响力持续跃升",
    "source": "Jiemian.com",
    "source_url": "https://www.jiemian.com",
    "url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE9zODhHdjRwNThjMHFWVlNYNWt0cGtnTUtFSHZYX3RGWUdXWENUUzhlZDB3WW5hYlVTWGtkZHR5b1RwU0g2eUFEb2pnNzk4amVRTDdFMUtnMVE?oc=5",
    "published": "2026-06-02",
    "summary": "布局电力、算力等期货，推动科创50等股指期货期权上市，“上海价格”影响力持续跃升&nbsp;&nbsp;Jiemian.com",
    "full_text": "布局电力、算力等期货，推动科创50等股指期货期权上市，“上海价格”影响力持续跃升&nbsp;&nbsp;Jiemian.com",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "14:13:23【上海：加快推出液化天然气期货和期权 做好电力期货、算力期货研发准备】",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFBrWk40bzlaVjlrQ244RUZrdEpOaEtlY0x5X0pBRUh3bGllV2stOWZiNjRnMjRSQzRFbFV1d2s4d3lYcXd4Q2NNbw?oc=5",
    "published": "2026-06-02",
    "summary": "14:13:23【上海：加快推出液化天然气期货和期权 做好电力期货、算力期货研发准备】&nbsp;&nbsp;财联社",
    "full_text": "14:13:23【上海：加快推出液化天然气期货和期权 做好电力期货、算力期货研发准备】&nbsp;&nbsp;财联社",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海：做好算力期货研发准备，推动科创50、深证100、创业板股指期货和期权上市",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE1qLWl4QlAwTTFxckJnd09WUFNQNGtJWGUzazdEVkl3T0RjOVdTM3F4UjVLRjBxZkVXLVZ6MzZqSWVUNkhHZmNzSg?oc=5",
    "published": "2026-06-02",
    "summary": "上海：做好算力期货研发准备，推动科创50、深证100、创业板股指期货和期权上市&nbsp;&nbsp;财联社",
    "full_text": "上海：做好算力期货研发准备，推动科创50、深证100、创业板股指期货和期权上市&nbsp;&nbsp;财联社",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海发布算力期货研发筹备对云赛智联有何影响？",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5Idmt1RDduM0IzTzdlSFZYRW9adjJjNGFkMnNXWndSVGpuX240a2ZaZ3ZBS2JTdGJUX0lPa0ZMU0lrTzhzNDIxWmdUYkItNVNZZzFSd2dNUTdtazFrQldYWWNPT3ZGNC1ycHE4?oc=5",
    "published": "2026-06-02",
    "summary": "上海发布算力期货研发筹备对云赛智联有何影响？&nbsp;&nbsp;财富号",
    "full_text": "上海发布算力期货研发筹备对云赛智联有何影响？&nbsp;&nbsp;财富号",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "南华期货：中国发展自身算力期货市场，具有超越单纯经济价值的战略意义",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFBoS29vRldSdUphVVZ1U1NvcWMtanhPX3ZBZEMtS0dpZjdUVlBKOFBXSDBPRE9GTU4yX1Ria2N4QlMtNWF0V0VtaEdSLWMyb2JycmZNaFJEMlV3anVHOGFOWlFPOFBoQQ?oc=5",
    "published": "2026-06-02",
    "summary": "南华期货：中国发展自身算力期货市场，具有超越单纯经济价值的战略意义&nbsp;&nbsp;东方财富",
    "full_text": "南华期货：中国发展自身算力期货市场，具有超越单纯经济价值的战略意义&nbsp;&nbsp;东方财富",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力期货提上日程 衍生品服务科创大有可为",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFBmNlB1RHVoWU5wUWJEcldFcXJUaFREUzhEeko1bXQ1SnpXeXJ5VEVSUnZ5RUZLdjdHdlVxMWhkWVdGSkpub2Y1R0ozX04xZzdRN3VUblJkTVBxbHdZSnItYUFSTmR2dw?oc=5",
    "published": "2026-06-02",
    "summary": "算力期货提上日程 衍生品服务科创大有可为&nbsp;&nbsp;东方财富",
    "full_text": "算力期货提上日程 衍生品服务科创大有可为&nbsp;&nbsp;东方财富",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力期货说明什么",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1SekZRdklYcEJIZVRteWptNWNUWDNrdVY3M2I0WnFMcWRnZDVkcnV0OU01bHpWem13dFNKM1kzY1QyQVhXT3ZUT3RZZk13RGtGTC1COWlqT2R3MTBXVk9tS1hsdWQxUW5YWlNF?oc=5",
    "published": "2026-06-02",
    "summary": "算力期货说明什么&nbsp;&nbsp;财富号",
    "full_text": "算力期货说明什么&nbsp;&nbsp;财富号",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "上海做好算力期货研发准备 新大宗商品呼之欲出",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE0ySjNmM0swbkFaeTQ1ZHRtbWhLclplVkxhV0g4ai1RTXZ5SXJYb21UeGUzdEZCdVlZT0pncENXYlg5MzVoVGRscmNCU0E5ejNoSTNsRUFMdW5XckxFRjNVMHhVUlJUUQ?oc=5",
    "published": "2026-06-01",
    "summary": "上海做好算力期货研发准备 新大宗商品呼之欲出&nbsp;&nbsp;东方财富",
    "full_text": "上海做好算力期货研发准备 新大宗商品呼之欲出&nbsp;&nbsp;东方财富",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Is ICE’s Record Energy OI and GPU Futures Push Altering The Investment Case For Intercontinental Exchange (ICE)?",
    "source": "simplywall.st",
    "source_url": "https://simplywall.st",
    "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxQX0tXNGx6NTJBWl9faFZYRGVQdzd0UkNEZm1mTlVzSkc3dWdCa1VHanY5d0tMcWw3VzFXY0RLMlFFOXhMczdjV00yWi1qX1c2UjFvalJnMG9aaTA0bWw2TEdiQlZSM0NTT3V0VGZmY3h1RFoyU0hrTUNrcERydTRKemc0LXJqUGZoNG5rb3IteGs4Y2VPeHNKdEZaYXVIdHdtTVI0Yl9DMkZuWEpzWm5VUmNFbmdneHB1NldyNGRxTGwzUndVeXpWUTNNZEdpY0FsVVRzRGtFREF6bVNjTmxZUEs0WkYxakhzM0pF0gHwAUFVX3lxTE51LXFUamx1ZGRJMGQ0bG9Ea2M3SlNUbHltZGlIOUgzLWlEWVotaVdFWjlwVkJROExSZmdNbWhBTUFyMk5sZVNTSHBmcHpvY2JpYmV1M09xSUQyeGljTVJPSFM2aWt2SFEydExSVXZIbmFhUHE0OXFaanRpdUVfajRWZ09pcnJRdHRPWTlEcHlGYVR1VnFEQVotRGM4NDB5QXk2OUdIOGNNdkhseGd5VWtGeHpQNEJHcFV5Ym14NFVqVDhvWUdEeTg5aTdoclBGcklMZjJubDdndm9SVlF2bkVwRFZmV1ltSWFNNE5LdUpJOA?oc=5",
    "published": "2026-05-31",
    "summary": "Is ICE’s Record Energy OI and GPU Futures Push Altering The Investment Case For Intercontinental Exchange (ICE)?&nbsp;&nbsp;simplywall.st",
    "full_text": "Is ICE’s Record Energy OI and GPU Futures Push Altering The Investment Case For Intercontinental Exchange (ICE)?&nbsp;&nbsp;simplywall.st",
    "images": [],
    "lang": "en",
    "title_cn": "ICE 创纪录的能源 OI 和 GPU 期货推动是否会改变洲际交易所 (ICE) 的投资案例？",
    "summary_cn": "ICE 创纪录的能源 OI 和 GPU 期货推动是否会改变洲际交易所 (ICE) 的投资案例？&nbsp;&nbsp;simplywall.st",
    "translated": true
  },
  {
    "title": "09:32:37【香港交易所回应“算力期货布局规划”：暂无评论可提供，将来如有相关信息将及时公布】",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE5tVldKenNwOVBXSUhyZV8tNFQ2SXJ3cGNJU3hqMko5Ykk0M2xtR0V4NjJyRkFUQjk5N0JTOUdnNWpuWFMzRFkybA?oc=5",
    "published": "2026-05-25",
    "summary": "09:32:37【香港交易所回应“算力期货布局规划”：暂无评论可提供，将来如有相关信息将及时公布】&nbsp;&nbsp;财联社",
    "full_text": "09:32:37【香港交易所回应“算力期货布局规划”：暂无评论可提供，将来如有相关信息将及时公布】&nbsp;&nbsp;财联社",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Wall Street giants are scrambling to buy GPU futures, the crypto market has already begun its battle.",
    "source": "PANews",
    "source_url": "https://www.panewslab.com",
    "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTFB0YWFJOWxjejBsbnZDMmh3OUJwcUhGbVltSmNYQm5XWlZ0ME5VSFBrdjVLekh4Mjk1U0xhQmJSU2FjZUxobkU5cVNlQmdSd0pqQ2d3VWhVUG03UWhFbm5UcWRDMHc0aGxvN0ZfMlI5eUk4OUd1b2ZVUlFqT09aM3M?oc=5",
    "published": "2026-05-22",
    "summary": "Wall Street giants are scrambling to buy GPU futures, the crypto market has already begun its battle.&nbsp;&nbsp;PANews",
    "full_text": "Wall Street giants are scrambling to buy GPU futures, the crypto market has already begun its battle.&nbsp;&nbsp;PANews",
    "images": [],
    "lang": "en",
    "title_cn": "华尔街巨头争先恐后买入GPU期货，加密市场已然打响。",
    "summary_cn": "华尔街巨头争相买入GPU期货，加密市场已然打响。&nbsp;&nbsp;PANews",
    "translated": true
  },
  {
    "title": "华尔街巨头抢滩GPU期货，加密市场已经提前开打",
    "source": "PANews",
    "source_url": "https://www.panewslab.com",
    "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE1QUEo2d1ZWQmxqNUU1N1hFSDZrZjZaNW04ejdMUk13R3VjdHhsSi1wSnZxZGpMUExoazNWN1ZqWklUVG5INE9mRHpGWmhqZ3k5Vjd6SVdEUFFvanJScHdfandSQ2hsc2Y4U1otY2FoTWhxamI4UUtYbFhFbmxmQW8?oc=5",
    "published": "2026-05-22",
    "summary": "华尔街巨头抢滩GPU期货，加密市场已经提前开打&nbsp;&nbsp;PANews",
    "full_text": "华尔街巨头抢滩GPU期货，加密市场已经提前开打&nbsp;&nbsp;PANews",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "当算力可以像期货一样交易，会发生什么",
    "source": "thepaper.cn",
    "source_url": "https://m.thepaper.cn",
    "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTFBiOXc2czRaX3FrbmNWRnZhRGI2UWl5NXFLTXh2R0s2ZUZoYVFSOVdZeWJ5R2g2ZGNNallwSUM2Tk5UZm1lQjBXMm5va1BNeG1DdjhTU3NlQWdvNVV5SWc?oc=5",
    "published": "2026-05-22",
    "summary": "当算力可以像期货一样交易，会发生什么&nbsp;&nbsp;thepaper.cn",
    "full_text": "当算力可以像期货一样交易，会发生什么&nbsp;&nbsp;thepaper.cn",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Intercontinental Exchange and Ornn Launching Suite Of GPU Compute Futures Contracts",
    "source": "Pulse 2.0",
    "source_url": "https://pulse2.com",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQTGcxRW5oVkliWDl3VlJlZHlvU25iUlZIVTVTU1N0Nm9SaUwtbTBsb1NBelI5NmMwUkFFdS1Pb0kzSTc3VVUyZVE1aFNEdU9WY2M0Y05fNGNUYUZiSzlNZ0Nuano2eU5UMkZJdjV3VjJWa2VJd2pZVWZpX3JOYkVqSENLR1R0LWlvOFNGVkF5bXhoZHNtYjVLUGtZT0NCNlB0QUYzcXhn0gGrAUFVX3lxTFBvNmFGcEpBelNLbHlDSEhuamxSUG0xUVZiUE0xTWxESVpxTjlyT3BydFg5Q1RGWnYzckt0QXBLbkx0bWZ0LVdSM2FIMGJUVkVOeWhNMDRsTFgtNHpLWEZzd0JyekFQZzVkazAtS1hOdWc4azUxTzItWmxVSVhCSFF6dFRTZzNFaTFNVmx4R09YYmtmbmdNYks4X1VjcWx3dFJDS0tLWlR4bkdwYw?oc=5",
    "published": "2026-05-21",
    "summary": "Intercontinental Exchange and Ornn Launching Suite Of GPU Compute Futures Contracts&nbsp;&nbsp;Pulse 2.0",
    "full_text": "Intercontinental Exchange and Ornn Launching Suite Of GPU Compute Futures Contracts&nbsp;&nbsp;Pulse 2.0",
    "images": [],
    "lang": "en",
    "title_cn": "洲际交易所和 Ornn 推出 GPU 计算期货合约套件",
    "summary_cn": "洲际交易所和 Ornn 推出 GPU 计算期货合约套件 Pulse 2.0",
    "translated": true
  },
  {
    "title": "Intercontinental Exchange (ICE) To Launch GPU Compute Futures Contracts Suite To Bring Transparency To GPU Costs",
    "source": "Yahoo Finance",
    "source_url": "https://finance.yahoo.com",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNX1FXLXBxbTNoMnZqVkVZVmF0QXF6YVR3ZmJDdjExSlBsNUpIRm9BZzhSeTZKU0t0MFo3dXVxRExsMWR1YmFPR0hQZUhHaE13YW9CSGxXVHhLdUZTQnFLTXUzSmtuNjVIU2pqYTBteWIxM1l6dHRVUGxuMUFGellaYUd0ZFZ2YVNyanhEcG9qRmJkeEU0QTgtWWVRTlg3U0d0NGVFMy1IOWJ4QQ?oc=5",
    "published": "2026-05-21",
    "summary": "Intercontinental Exchange (ICE) To Launch GPU Compute Futures Contracts Suite To Bring Transparency To GPU Costs&nbsp;&nbsp;Yahoo Finance",
    "full_text": "Intercontinental Exchange (ICE) To Launch GPU Compute Futures Contracts Suite To Bring Transparency To GPU Costs&nbsp;&nbsp;Yahoo Finance",
    "images": [],
    "lang": "en",
    "title_cn": "洲际交易所 (ICE) 将推出 GPU 计算期货合约套件，以提高 GPU 成本的透明度",
    "summary_cn": "洲际交易所 (ICE) 将推出 GPU 计算期货合约套件，以提高 GPU 成本的透明度 雅虎财经",
    "translated": true
  },
  {
    "title": "How ICE’s Planned GPU Compute Futures Could Reshape Intercontinental Exchange (ICE) Investors’ AI Narrative",
    "source": "Yahoo Finance",
    "source_url": "https://finance.yahoo.com",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxPWVEySmJjaUhNUlZrV1RfSUlTaW9PdEEwOC05MjBaa05EaXlnck1YX1V1YW01VFoyMGRGMTlqZ2NfbnhMb19FZGFGS3MyS2loSjU5ZllLUFBQbnhZZHFkUjBDckQyQm05VzlVU3NmOHR6TDBjRjdTVzVlVGRaM29FMENjYWhzOEZpSkd4WGNlbTFlZmNGRVFlVnV5TGx5QQ?oc=5",
    "published": "2026-05-20",
    "summary": "How ICE’s Planned GPU Compute Futures Could Reshape Intercontinental Exchange (ICE) Investors’ AI Narrative&nbsp;&nbsp;Yahoo Finance",
    "full_text": "How ICE’s Planned GPU Compute Futures Could Reshape Intercontinental Exchange (ICE) Investors’ AI Narrative&nbsp;&nbsp;Yahoo Finance",
    "images": [],
    "lang": "en",
    "title_cn": "ICE 计划的 GPU 计算未来如何重塑洲际交易所 (ICE) 投资者的人工智能叙事",
    "summary_cn": "ICE 计划的 GPU 计算未来如何重塑洲际交易所 (ICE) 投资者的人工智能叙事 雅虎财经",
    "translated": true
  },
  {
    "title": "DERIVSOURCE: CME Group, Silicon Data to Launch Futures for Computing Power",
    "source": "Traders Magazine",
    "source_url": "https://www.tradersmagazine.com",
    "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxOcDZLaktzYVM0NW5xUjB1eDBGUkRPMFlXdXhhX1M3RGEwcjFiMGQ5cEVkbnkyY19SNTdvMWpxenhYdzMzSGc5NjZnaG1wQ3JmNVdDeHhZbW1wZU4weUNjLTBXTmh4ZEJrUXp5MVdiUV9NWkN1NzBsUW9zSXM2cUFYTzJzeDhUbkNNd2pGeVBQVFYwZ0VwSnpXZmNyOEFhZFRxTjhTb1l3MXNfVFFILVdzV09zWW95SkFS?oc=5",
    "published": "2026-05-20",
    "summary": "DERIVSOURCE: CME Group, Silicon Data to Launch Futures for Computing Power&nbsp;&nbsp;Traders Magazine",
    "full_text": "DERIVSOURCE: CME Group, Silicon Data to Launch Futures for Computing Power&nbsp;&nbsp;Traders Magazine",
    "images": [],
    "lang": "en",
    "title_cn": "DERIVSOURCE：CME 集团与 Silicon Data 推出计算能力期货",
    "summary_cn": "DERIVSOURCE：CME 集团和 Silicon Data 将推出计算能力期货交易者杂志",
    "translated": true
  },
  {
    "title": "ICE moves to list futures on GPU compute, putting AI infrastructure on the trading floor",
    "source": "Startup Fortune",
    "source_url": "https://startupfortune.com",
    "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxPUDhmdjk2bWx1OGFXMy1acXhYTmJIaFpKajh1X3dpWVE5V1NuaUpwYUVwTVFhRlduSEhsdnE4MzdkUGhDRmZvZUY0enlNQ1BJcDFIcGQ4R0JuSlNNMnJkbERzWTBpRTJZLVBZVk1aQWQtTmlKY0RpOWNERDVfaHBHU3JLVHBtcV9rcF9KcXVYd1VUVzdUb2M2YVI3dTZPZzBRLXN0NXoxUTEzTGd0cW1NdHFZdWRRQQ?oc=5",
    "published": "2026-05-19",
    "summary": "ICE moves to list futures on GPU compute, putting AI infrastructure on the trading floor&nbsp;&nbsp;Startup Fortune",
    "full_text": "ICE moves to list futures on GPU compute, putting AI infrastructure on the trading floor&nbsp;&nbsp;Startup Fortune",
    "images": [],
    "lang": "en",
    "title_cn": "ICE 开始上市 GPU 计算期货，将人工智能基础设施置于交易大厅",
    "summary_cn": "ICE 开始上市 GPU 计算期货，将人工智能基础设施置于交易大厅 创业财富",
    "translated": true
  },
  {
    "title": "ICE, Ornn plan to launch GPU compute futures contracts",
    "source": "FX News Group",
    "source_url": "https://fxnewsgroup.com",
    "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxQa0pTRzhYTjktUGp1WGVvdVBpeF9VQlV4dlR0b3hUMG1VNXhYblN0Rk1QM3kwLURhemZjYnE3NU0yRFFQcE9MR1V1aThpcnNMR3U1dzBRNzU0WEF1ajlLSmtrMnJJdFdEMTgtcmdfOXluSGlYc0x0R01mVzVTa3V5TFlhQWd4SEtON01UNTdCa2wtdjFieWJHUG9vVkFjUUdM?oc=5",
    "published": "2026-05-19",
    "summary": "ICE, Ornn plan to launch GPU compute futures contracts&nbsp;&nbsp;FX News Group",
    "full_text": "ICE, Ornn plan to launch GPU compute futures contracts&nbsp;&nbsp;FX News Group",
    "images": [],
    "lang": "en",
    "title_cn": "ICE 和 Ornn 计划推出 GPU 计算期货合约",
    "summary_cn": "ICE 和 Ornn 计划推出 GPU 计算期货合约 FX News Group",
    "translated": true
  },
  {
    "title": "ICE and Ornn to launch GPU compute futures contracts",
    "source": "Blockspace Media",
    "source_url": "https://blockspace.media",
    "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxPZDdIMFlGS2RrUU1Dczh6ZmthY1JsMktiSWlCdVVfZGFBSHllTnp2MGJRTmdWSTNXMGNCQkFTZ1N4dVZpaWVrajYzLVBVSGxua291dERDWmdzWkpaTC1Hd2lPZmE1OWdXUE0wMUNGeDJFdmpMN3ppcWxIZlFjd0JWQmR3?oc=5",
    "published": "2026-05-19",
    "summary": "ICE and Ornn to launch GPU compute futures contracts&nbsp;&nbsp;Blockspace Media",
    "full_text": "ICE and Ornn to launch GPU compute futures contracts&nbsp;&nbsp;Blockspace Media",
    "images": [],
    "lang": "en",
    "title_cn": "ICE 和 Ornn 将推出 GPU 计算期货合约",
    "summary_cn": "ICE 和 Ornn 将推出 GPU 计算期货合约 Blockspace Media",
    "translated": true
  }
];
