// GPU 算力新闻 v2
// 生成: 2026-06-12T13:27:24Z
var NEWS_FETCHED_AT = "2026-06-12T13:27:24Z";
var GPU_NEWS = [
  {
    "title": "AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场",
    "source": "财联社",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFB1NXZMVWl6N1JYV2xKd0V1ajlGdk1Dem10ajR5RUx6WXJpc1FoV3N4OFJvdHZfdXFjUFJDSi1zR0gxeWhTZWM5Nw?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-12",
    "summary": "AI世界的“原油期货”要来了：芝商所官宣将推出算力期货市场&nbsp;&nbsp;财联社",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFB1NXZMVWl6N1JYV2xKd0V1ajlGdk1Dem10ajR5RUx6WXJpc1FoV3N4OFJvdHZfdXFjUFJDSi1zR0gxeWhTZWM5Nw?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "688802，国产GPU龙头宣布赴港上市计划",
    "source": "搜狐网",
    "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxOeGVEVzl4YlJsRWJmQ2xNRTd2UFpPTjZxVmxKS1N3cFk2ZER4NUxXUEdQaXVpLTZCN0VmRkl2V09DUWVVWC1EX2kwNl93bFdsLVE4cDUzMlI2clAyVkZFX0E5ZkV5SlJyZzh5c2RRMkR4eUtYYVlMU2t1d25QTDQzLVZoRWZlRVAzY0ZRRA?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-12",
    "summary": "688802，国产GPU龙头宣布赴港上市计划&nbsp;&nbsp;搜狐网",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxOeGVEVzl4YlJsRWJmQ2xNRTd2UFpPTjZxVmxKS1N3cFk2ZER4NUxXUEdQaXVpLTZCN0VmRkl2V09DUWVVWC1EX2kwNl93bFdsLVE4cDUzMlI2clAyVkZFX0E5ZkV5SlJyZzh5c2RRMkR4eUtYYVlMU2t1d25QTDQzLVZoRWZlRVAzY0ZRRA?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "高端算力紧缺，英伟达云端GPU租价大涨，天弘中证全指通信设备指数基金(A/C：020899/020900)聚焦算力光模块龙头享红利",
    "source": "新浪财经",
    "url": "https://news.google.com/rss/articles/CBMiuwJBVV95cUxPcU9KNTNNN3JPdWFHbzJtb3ZHWXp1bG1wQ3ROSURmVXNSUEpqODQ1dnNNbEhaVEpfWXdfVGVCXzZEUE94LTJka2dpS0JPaUlpVVVpdm1peGN6RlRaZEt6SERCR2UxTlJYSmRkZDZiNXZHcGNrUmxVOGFDQTRMNFdYa0ZnTGs1cWN5TWVnN1ZLNzhCY1BfMDVTdkhDdEE0Q1pZeWlBeTEyaW5iWTk3dXczbEx5RGhnREFyLUtkMGlnc182elV1YjNfUVRIejdiNUdiRlJpRnZuVWZxZVlQOUlnLXM1dXhtOS1fYU1EVTRJT2RudzJ1bF9kMkY1aDZQQy0xU2RtU25oajczNkNBemFTLWIwTmdZS3VvOVlIdTZNaGZlQnhSVUN4YXBlc0w1eFhRQ1ZtSlZjQXJneDA?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-11",
    "summary": "高端算力紧缺，英伟达云端GPU租价大涨，天弘中证全指通信设备指数基金(A/C：020899/020900)聚焦算力光模块龙头享红利&nbsp;&nbsp;新浪财经",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiuwJBVV95cUxPcU9KNTNNN3JPdWFHbzJtb3ZHWXp1bG1wQ3ROSURmVXNSUEpqODQ1dnNNbEhaVEpfWXdfVGVCXzZEUE94LTJka2dpS0JPaUlpVVVpdm1peGN6RlRaZEt6SERCR2UxTlJYSmRkZDZiNXZHcGNrUmxVOGFDQTRMNFdYa0ZnTGs1cWN5TWVnN1ZLNzhCY1BfMDVTdkhDdEE0Q1pZeWlBeTEyaW5iWTk3dXczbEx5RGhnREFyLUtkMGlnc182elV1YjNfUVRIejdiNUdiRlJpRnZuVWZxZVlQOUlnLXM1dXhtOS1fYU1EVTRJT2RudzJ1bF9kMkY1aDZQQy0xU2RtU25oajczNkNBemFTLWIwTmdZS3VvOVlIdTZNaGZlQnhSVUN4YXBlc0w1eFhRQ1ZtSlZjQXJneDA?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "云天畅想茅晓东：AI算力市场将增十万倍达百万亿级|连线创始人",
    "source": "电子工程专辑",
    "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFBlZzlabFVwMWQzQ2ItZEJjQkZIdU9vcWNQbnJGT2VUR29XaUpPa1RSXzY5S2ZXek93U3h0UnFfUUhNUHF0NndmVEEzLVctWVRmQ1lr?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-11",
    "summary": "云天畅想茅晓东：AI算力市场将增十万倍达百万亿级|连线创始人&nbsp;&nbsp;电子工程专辑",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFBlZzlabFVwMWQzQ2ItZEJjQkZIdU9vcWNQbnJGT2VUR29XaUpPa1RSXzY5S2ZXek93U3h0UnFfUUhNUHF0NndmVEEzLVctWVRmQ1lr?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "全球TPU算力赛道爆发！技术革新重塑AI算力产业新格局",
    "source": "雷科技",
    "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9UdktiSzNrOHBZY3Qxbk1Wblo4bEljYmozXzR0NEN5azd6aE40UXFXS1JlZ3VGNGJTdEljVGpyWnhQSnVieUNMS1owcG80QQ?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-10",
    "summary": "全球TPU算力赛道爆发！技术革新重塑AI算力产业新格局&nbsp;&nbsp;雷科技",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9UdktiSzNrOHBZY3Qxbk1Wblo4bEljYmozXzR0NEN5azd6aE40UXFXS1JlZ3VGNGJTdEljVGpyWnhQSnVieUNMS1owcG80QQ?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "国产算力链弄潮：CPU紧俏、GPU爆发",
    "source": "新浪财经",
    "url": "https://news.google.com/rss/articles/CBMiggVBVV95cUxNTEVLY0ZxZlFLME5PVVpZX1FCYmlGaFEtejdZa0pzSmxxakJ6dzBEOGx1blVYeW1NS09OSWVEeU5kS1JwMnlGOU1QMHA5MmdSNmxUMVE4a2Q0SEtFM3k2OG1PWmZXcU54TGp6MFRtNmpZek5tZ0J0VVZNakNiTXZaNjhxMVpuZGY0eEdzWGxGc2FEdEViMURzV1lRZy1ldGp4VU1mTC02SzZJVEdoRjQtTE1EU2U4V3pwWmR0ajJKS2lhUGVwOFo4VzJ2R2NXT1FVVGpPOW1MdFBETmpmdnBqd1UwNFotM2o3eE5Kal9COF84ZzZNdDFsRmdNa2o2eGdaZFVlTFF4ZTVnZm5ab1FLQ2NjZE14M1h6SG5rNUp6b1FvSEFiNVhLNmMtV2FGY25yZkM3LVRQZDMzMDU3a2hZdHF6SWZMMnJGWWtDVHJMY0lvMzU4ckhCazBETjMwdnhid012RVZCcHh5MmJEdllodmxuTTVHQ0FXOWIwZzJlWlNKTndQbjFvQ3A0dUZjVWI3Z0lTOUFob2ZvRnNRQko5b1B1aHlwWUNWOGJGVVo1b0FxWGFFaVBiZ29mREJPZ2hhZ2JiLVhkaFBoXzRTUGpXT2Vtc1lrRFpPdHllRG9ydGxpZE5HcG1RT3Z0REhvdzlvUVFmZDFvNnNueFJuSmZmNHZwY1RUajhFcTZLS25GakNpYUpXYThyaWZ1Mlhqd3ZEZ1QyOTlpVFhTSjZ3c2hwOXZYZkIwMDFUSTJSOEdSWTVIZnAybWJpUE8xbUxLOUtBR1dtQzEyZHR6ZDdCRndJZGhXTFFPNGlSbENMelI1bGZIc05scG93ODhQSHJFTTBCWGc?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-09",
    "summary": "国产算力链弄潮：CPU紧俏、GPU爆发&nbsp;&nbsp;新浪财经",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiggVBVV95cUxNTEVLY0ZxZlFLME5PVVpZX1FCYmlGaFEtejdZa0pzSmxxakJ6dzBEOGx1blVYeW1NS09OSWVEeU5kS1JwMnlGOU1QMHA5MmdSNmxUMVE4a2Q0SEtFM3k2OG1PWmZXcU54TGp6MFRtNmpZek5tZ0J0VVZNakNiTXZaNjhxMVpuZGY0eEdzWGxGc2FEdEViMURzV1lRZy1ldGp4VU1mTC02SzZJVEdoRjQtTE1EU2U4V3pwWmR0ajJKS2lhUGVwOFo4VzJ2R2NXT1FVVGpPOW1MdFBETmpmdnBqd1UwNFotM2o3eE5Kal9COF84ZzZNdDFsRmdNa2o2eGdaZFVlTFF4ZTVnZm5ab1FLQ2NjZE14M1h6SG5rNUp6b1FvSEFiNVhLNmMtV2FGY25yZkM3LVRQZDMzMDU3a2hZdHF6SWZMMnJGWWtDVHJMY0lvMzU4ckhCazBETjMwdnhid012RVZCcHh5MmJEdllodmxuTTVHQ0FXOWIwZzJlWlNKTndQbjFvQ3A0dUZjVWI3Z0lTOUFob2ZvRnNRQko5b1B1aHlwWUNWOGJGVVo1b0FxWGFFaVBiZ29mREJPZ2hhZ2JiLVhkaFBoXzRTUGpXT2Vtc1lrRFpPdHllRG9ydGxpZE5HcG1RT3Z0REhvdzlvUVFmZDFvNnNueFJuSmZmNHZwY1RUajhFcTZLS25GakNpYUpXYThyaWZ1Mlhqd3ZEZ1QyOTlpVFhTSjZ3c2hwOXZYZkIwMDFUSTJSOEdSWTVIZnAybWJpUE8xbUxLOUtBR1dtQzEyZHR6ZDdCRndJZGhXTFFPNGlSbENMelI1bGZIc05scG93ODhQSHJFTTBCWGc?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "2026AI算力全产业链全景分析报告",
    "source": "财富号",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE13UE1qM0V4THZDYjk4bFJOZkpLQ2k3UHoyYUZaTWtoZ1p1QzVHUDNjcXQyZ2lEaGRyY0xnOUdZdGl0VDdiTEt3THd0aHhMSFZyMS02ZDNQcDVqNGo1M2tGNWVhZkdrb2Q2RGdN?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-09",
    "summary": "2026AI算力全产业链全景分析报告&nbsp;&nbsp;财富号",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE13UE1qM0V4THZDYjk4bFJOZkpLQ2k3UHoyYUZaTWtoZ1p1QzVHUDNjcXQyZ2lEaGRyY0xnOUdZdGl0VDdiTEt3THd0aHhMSFZyMS02ZDNQcDVqNGo1M2tGNWVhZkdrb2Q2RGdN?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "Apple Will Run Advanced AI Model on Nvidia GPUs via Google Cloud, Ditching Private Infrastructure",
    "source": "24/7 Wall St.",
    "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQVXZqR2FKSlM5V21HUUt2X0NUNEFvN19YVkIxR3hNVFBvbGxmYVV2N0FIejIyemJ2MFNoQzhoTkF0Z19HR1lLTU1hWkpCMTRhaEE4OFc4QlRIODg2OW94aGNzNDNBa1ZJRUNYaC1SLWVpdUFLbE1uclhkVERfR2FsMHpPc2hISFhhMkJWd3pNLVZ1RWx4YVo0UVdmbTJaZWM0Y0hkcDA3d0x5VTNqbHF5NF90ZHduSG01bDhvQ24wWWs2cmc1b3hPOFl1SF9ZUkh2ZF9ycnhKSQ?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-09",
    "summary": "Apple Will Run Advanced AI Model on Nvidia GPUs via Google Cloud, Ditching Private Infrastructure&nbsp;&nbsp;24/7 Wall St.",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQVXZqR2FKSlM5V21HUUt2X0NUNEFvN19YVkIxR3hNVFBvbGxmYVV2N0FIejIyemJ2MFNoQzhoTkF0Z19HR1lLTU1hWkpCMTRhaEE4OFc4QlRIODg2OW94aGNzNDNBa1ZJRUNYaC1SLWVpdUFLbE1uclhkVERfR2FsMHpPc2hISFhhMkJWd3pNLVZ1RWx4YVo0UVdmbTJaZWM0Y0hkcDA3d0x5VTNqbHF5NF90ZHduSG01bDhvQ24wWWs2cmc1b3hPOFl1SF9ZUkh2ZF9ycnhKSQ?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "苹果将​​通过谷歌云在 Nvidia GPU 上运行高级人工智能模型，放弃私有基础设施",
    "summary_cn": "苹果将​​通过谷歌云在 Nvidia GPU 上运行高级人工智能模型，放弃私有基础设施&nbsp;&nbsp;24/7 Wall St.",
    "full_text_cn": "",
    "translated": true
  },
  {
    "title": "“以租代买”，AI时代为什么需要DaaS？",
    "source": "风闻",
    "url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE43Uk1JS3ZjYmJ1UWUzUTRINGFjeEVNVUpSYUZpd0lmM3Y1cFBacHdSdGlZQ3FTOVE0b25xZmxFQlhvelFBb2xhQlcyc1dPSEFySWtJSU81TTNvQjZkWlVwY1RmYUE2VTZoaUE?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-08",
    "summary": "“以租代买”，AI时代为什么需要DaaS？&nbsp;&nbsp;风闻",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiakFVX3lxTE43Uk1JS3ZjYmJ1UWUzUTRINGFjeEVNVUpSYUZpd0lmM3Y1cFBacHdSdGlZQ3FTOVE0b25xZmxFQlhvelFBb2xhQlcyc1dPSEFySWtJSU81TTNvQjZkWlVwY1RmYUE2VTZoaUE?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "谷歌豪掷300亿美元向SpaceX租算力！xAI成算力新巨头，11万颗英伟达GPU救急Gemini",
    "source": "Sina finance",
    "url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE8tQWw2VnVxdjFqWk00bHN3d3F5d1VwYnRjb1lXM1VGemJYVGdzM2NueW9XWW9Lc1p3YTlKR1A1alMtUmY3WkxzY1BWd0k5X2U5b3pjbG8taHBjWWcyNGw5bXRfU2tDaXJ3UGxWWTR3UGo0RDIwSndlUnVlakZTTjA?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-08",
    "summary": "谷歌豪掷300亿美元向SpaceX租算力！xAI成算力新巨头，11万颗英伟达GPU救急Gemini&nbsp;&nbsp;Sina finance",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMif0FVX3lxTE8tQWw2VnVxdjFqWk00bHN3d3F5d1VwYnRjb1lXM1VGemJYVGdzM2NueW9XWW9Lc1p3YTlKR1A1alMtUmY3WkxzY1BWd0k5X2U5b3pjbG8taHBjWWcyNGw5bXRfU2tDaXJ3UGxWWTR3UGo0RDIwSndlUnVlakZTTjA?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "AI的新价格语言，算力何以成期货",
    "source": "thepaper.cn",
    "url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE9YRnRTekpzOEZvNDJVdFl5cHcxQ01RRDJHSUw5Z2pWb2tEX2tLdE9hb293dDN3cDROVXRUQ3NJY0I2WnJTS2VvMFNlMmpZNFV2aGN4di1OVHdFT2FCZnc?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-08",
    "summary": "AI的新价格语言，算力何以成期货&nbsp;&nbsp;thepaper.cn",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiXkFVX3lxTE9YRnRTekpzOEZvNDJVdFl5cHcxQ01RRDJHSUw5Z2pWb2tEX2tLdE9hb293dDN3cDROVXRUQ3NJY0I2WnJTS2VvMFNlMmpZNFV2aGN4di1OVHdFT2FCZnc?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "夯实Token算力底座，中诚华隆加速国产GPU突围，构筑普惠算力黄金三角- 人工智能",
    "source": "eetop.cn",
    "url": "https://news.google.com/rss/articles/CBMiTEFVX3lxTE9qWk5sSE16QTVJZTdaQUk2R1hxQ3lHWVIyV1l5TkV4ZXZ0ME1sMnBnbTF5WlMwNDlrZkNONm4xaXlyeE10cVNfSEJzS1k?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-08",
    "summary": "夯实Token算力底座，中诚华隆加速国产GPU突围，构筑普惠算力黄金三角- 人工智能&nbsp;&nbsp;eetop.cn",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiTEFVX3lxTE9qWk5sSE16QTVJZTdaQUk2R1hxQ3lHWVIyV1l5TkV4ZXZ0ME1sMnBnbTF5WlMwNDlrZkNONm4xaXlyeE10cVNfSEJzS1k?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "谷歌携手SpaceX达成算力合作 租赁11万颗英伟达GPU",
    "source": "驱动之家",
    "url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE8yY2wyRzUzSzM2UjRzeXdhWGIxdGhDVFQ0MmNkbFNSUzJPUmlIMmFIMHlUS3FpR2w5X01BWV8yV0l5Q2JmaF9hUjlwcXhwN3ZlS0puRVpvd1c?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-07",
    "summary": "谷歌携手SpaceX达成算力合作 租赁11万颗英伟达GPU&nbsp;&nbsp;驱动之家",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE8yY2wyRzUzSzM2UjRzeXdhWGIxdGhDVFQ0MmNkbFNSUzJPUmlIMmFIMHlUS3FpR2w5X01BWV8yV0l5Q2JmaF9hUjlwcXhwN3ZlS0puRVpvd1c?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  },
  {
    "title": "Google Pays SpaceX $920M/Month for 110,000 GPUs at xAI Data Center",
    "source": "abhs.in",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxOSU95UUdqYkQ5Q05hRFgySnIyWjlLRERVZk1MdXpzcEJnLXBLMkRmOTFvUFI5SzhINkNEa3hnc1ZqOXlsbnMzd2hTb3d1NW00WW1wM3Y2QWRpTWdZYmxUelVESWN2MXo5eHh1eW1wVGI5TjU0Y3Y4Ri1XMHRmc1k0WjVKX3FpSEVuUlBURkdqZURIdm90aVpaWkdzdElsZw?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-07",
    "summary": "Google Pays SpaceX $920M/Month for 110,000 GPUs at xAI Data Center&nbsp;&nbsp;abhs.in",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMingFBVV95cUxOSU95UUdqYkQ5Q05hRFgySnIyWjlLRERVZk1MdXpzcEJnLXBLMkRmOTFvUFI5SzhINkNEa3hnc1ZqOXlsbnMzd2hTb3d1NW00WW1wM3Y2QWRpTWdZYmxUelVESWN2MXo5eHh1eW1wVGI5TjU0Y3Y4Ri1XMHRmc1k0WjVKX3FpSEVuUlBURkdqZURIdm90aVpaWkdzdElsZw?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "Google 每月向 SpaceX 支付 9.2 亿美元，购买 xAI 数据中心的 110,000 个 GPU",
    "summary_cn": "Google 每月向 SpaceX 支付 9.2 亿美元，购买 xAI 数据中心的 110,000 个 GPU &nbsp;&nbsp;abhs.in",
    "full_text_cn": "",
    "translated": true
  },
  {
    "title": "合计700亿美元！SpaceX先后与Anthropic和谷歌签下大单，“算力租赁”ARR高达260亿美元",
    "source": "华尔街见闻",
    "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9SN0Q3aGx3VlhKWmNaNkFXYl9JVkRKVVhEZm1VbGtOWm1tZnlaUG1wa1ZRelZrRUlxUW9RT2tuSTUzMjk0aE1tUGlWbXQ4LURaeGdn?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "2026-06-06",
    "summary": "合计700亿美元！SpaceX先后与Anthropic和谷歌签下大单，“算力租赁”ARR高达260亿美元&nbsp;&nbsp;华尔街见闻",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9SN0Q3aGx3VlhKWmNaNkFXYl9JVkRKVVhEZm1VbGtOWm1tZnlaUG1wa1ZRelZrRUlxUW9RT2tuSTUzMjk0aE1tUGlWbXQ4LURaeGdn?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "",
    "summary_cn": "",
    "full_text_cn": "",
    "translated": false
  }
];
