// GPU算力租赁新闻 v4
// Generated: 2026-06-13T06:06:19Z
var NEWS_FETCHED_AT = "2026-06-13T06:06:19Z";
var GPU_NEWS = [
  {
    "title": "算力价格大幅下降_新浪新闻",
    "source": "手机新浪网",
    "source_url": "https://www.sina.cn",
    "url": "https://news.google.com/rss/articles/CBMiY0FVX3lxTE5BME9nU1ljbW5rRWhnOTYwV3VFaE02Z0cyeHg1b0k3U2xhVVBhNl9Id3NJUFFaNWJPVmk5UzV5TU5xcC1vY3JGWV9acDh6UmxuVmtZYVhDRm5hX1BodmpFNDdWYw?oc=5",
    "published": "2026-06-11",
    "summary": "算力价格大幅下降_新浪新闻&nbsp;&nbsp;手机新浪网",
    "full_text": "「算力价格大幅下降_新浪新闻」\n\n来源：手机新浪网\n发布日期：2026-06-11\n\n本文由 Google News 聚合自 手机新浪网。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "百万Token仅需数元：算力租赁价格下行，AI大模型应用成本门槛降低",
    "source": "第一财经",
    "source_url": "https://www.yicai.com",
    "url": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE1jOVNKVmNwV09YQ0FTaTBrcTY0aVFJcmhNSWI2OURzR0ptX1d3VVZPcWJETEFtMUVySDdKWFYteHlkWnpEYzlsdExFU3FNR3NJUHVMbg?oc=5",
    "published": "2026-06-11",
    "summary": "百万Token仅需数元：算力租赁价格下行，AI大模型应用成本门槛降低&nbsp;&nbsp;第一财经",
    "full_text": "「百万Token仅需数元：算力租赁价格下行，AI大模型应用成本门槛降低」\n\n来源：第一财经\n发布日期：2026-06-11\n\n本文由 Google News 聚合自 第一财经。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力租赁概念快速拉升 美利云、拓维信息双双涨停",
    "source": "东方财富",
    "source_url": "https://wap.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE1GNjdycjlnOENKZ1paQzIwd0NnVGhZeHlMMlpSNEppcVg4VDc4RU55Y1RhRmlzRG1aN0FpYkIwTlNnWkdjX0F5NmRqaHVMVkJKNGhjUE5hVTVOdS1KenJQYQ?oc=5",
    "published": "2026-06-10",
    "summary": "算力租赁概念快速拉升 美利云、拓维信息双双涨停&nbsp;&nbsp;东方财富",
    "full_text": "「算力租赁概念快速拉升 美利云、拓维信息双双涨停」\n\n来源：东方财富\n发布日期：2026-06-10\n\n本文由 Google News 聚合自 东方财富。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力租赁板块短线走高",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE1YQktmS242Ym4xUW1MTzRDZUlnWjRxZEV0RXVhelEzUzA4TUk4enk4WEN6QUVQbXRIY2x0TUhDd0dhbl9XU004V3lRSW9MeFhwdndaUS16QTRxS1Q3TnVfdDBJeS0xdw?oc=5",
    "published": "2026-06-10",
    "summary": "算力租赁板块短线走高&nbsp;&nbsp;东方财富",
    "full_text": "「算力租赁板块短线走高」\n\n来源：东方财富\n发布日期：2026-06-10\n\n本文由 Google News 聚合自 东方财富。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "SpaceX入局AI算力租赁，轻松健康（2661.HK）“证元芳”携近7万医生生态卡位医疗场景",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5uemxydDF6YTZwZEJyYld0NTU3c1NKck5wR2JiUThMUVRqLTg5SW5ZUjg1S2RSRUlQZTBSSXlWdFhnaFh4ZG4ybFRVX2ljS1g1Xy1DY05VM2wyTzJHRWFfdHNOb0RfcW5sZjZr?oc=5",
    "published": "2026-06-10",
    "summary": "SpaceX入局AI算力租赁，轻松健康（2661.HK）“证元芳”携近7万医生生态卡位医疗场景&nbsp;&nbsp;财富号",
    "full_text": "「SpaceX入局AI算力租赁，轻松健康（2661.HK）“证元芳”携近7万医生生态卡位医疗场景」\n\n来源：财富号\n发布日期：2026-06-10\n\n本文由 Google News 聚合自 财富号。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI 代理现在急需廉价算力，去中心化云正好能提供",
    "source": "Yellow.com",
    "source_url": "https://yellow.com",
    "url": "https://news.google.com/rss/articles/CBMiwgJBVV95cUxOMUJRSUk0ckVmclB6QlZpRnpKNGdDRS1aOUM2MV9rbFJzRV9nTzhLYzZ2aU5rZ3dKSTVLMVc3NlhYb3dVMEtwaUpsT3U0U0NKazNUbXBVQ0p6WnhYUm5kd1JMZkdoMTEwM1l6NzhRdnFBSzV1U2NLZTFCa29HYl9DVnQxamJ0bERXVEs2YkFoRmJ4ZW5BcEhSM1FkbnhFaXdBWVpVMWJSd2ZheE5YTEFJWWxENXFNZHM1Z0NnYndVQ0ZyZ2toY0FBa0J1WkVmRVR2cTlVcHpzZ1NJejRHRXdJUXNzb19FOEhGdk1QcmFkYmR0WmNFUW96UzdVODd3ZVltQUlPN2dITG14ak8taWViLVR6QzN5eHpHNVFkSDhnSWhFLXkzVkkwOW1QOWh4V18wemduZkJxWmZVdDZYelI4WnpB?oc=5",
    "published": "2026-06-09",
    "summary": "AI 代理现在急需廉价算力，去中心化云正好能提供&nbsp;&nbsp;Yellow.com",
    "full_text": "「AI 代理现在急需廉价算力，去中心化云正好能提供」\n\n来源：Yellow.com\n发布日期：2026-06-09\n\n本文由 Google News 聚合自 Yellow.com。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力租赁头部重构",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMi8gFBVV95cUxOSFMxY2RCUDllTGpWQTlhdTlzazAwa2NRclAxZU5iWHViQ2otQ3pVQkt6dDBLZ2JocXd4SU9ad252a1hBUzVhSTVpQUpFUkltVWJiQU5JZTRFX2NkVkZmMnE4T24za2M0X0FrYTlsVjkyZjZuNEpKTDlUQ1psVmRJNVlRcG5fd0lvd3ZONjFneGdQR0NVS1Vodjk3T0lXSUduRHNCeEoyT3dDUmp1QnlEclY5NTY3ZTFkejRzNms1TXVqZWRxYlRsVlQtR3Jjdk5FaHRjLWowTWtmRFc5RzAtclZ4WVdiZmpDd2JCenZSX2lvQQ?oc=5",
    "published": "2026-06-08",
    "summary": "算力租赁头部重构&nbsp;&nbsp;财富号",
    "full_text": "「算力租赁头部重构」\n\n来源：财富号\n发布日期：2026-06-08\n\n本文由 Google News 聚合自 财富号。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI的新价格语言，算力何以成期货",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE5VZW1kTFNtWnRsRFNneEgwbS0tMEluSG41UXJLeWp4LVNmUkF1TVhIY2NZM0hnLXRCRkU0cTBjY19xNnJJNi15VWZOcnhRUXR1LTYxb2cxbnhKcnh1R1R3QncySHJFTURTSmlMYWtrVG9QX2pTMjYtZA?oc=5",
    "published": "2026-06-08",
    "summary": "AI的新价格语言，算力何以成期货&nbsp;&nbsp;Sina finance",
    "full_text": "「AI的新价格语言，算力何以成期货」\n\n来源：Sina finance\n发布日期：2026-06-08\n\n本文由 Google News 聚合自 Sina finance。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "SpaceX公布第二笔大规模算力租赁交易：谷歌每月9.2亿美元租SpaceX算力",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTE5XU2l2TzEyMm5xZE9KcWtEb1pTNGwydms5Z0JmN19URjZhc3kxZVRhLWxzUDBQWWdqV3RvMXhsYXQyc0Y5ME5WbFR0RmE3c3ZYWUVDdldwbzg2aUU1MVNrTDRaMm9aTEFvcVhwQ3dZNzZFUWV1ZWhuWA?oc=5",
    "published": "2026-06-06",
    "summary": "SpaceX公布第二笔大规模算力租赁交易：谷歌每月9.2亿美元租SpaceX算力&nbsp;&nbsp;Sina finance",
    "full_text": "「SpaceX公布第二笔大规模算力租赁交易：谷歌每月9.2亿美元租SpaceX算力」\n\n来源：Sina finance\n发布日期：2026-06-06\n\n本文由 Google News 聚合自 Sina finance。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI时代的“算力”期货市场什么样？",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE5ORXM3UVlMLU1ZTVFWbzBHa3ljU0JwZXlGTW9GbVV6MGJseHNXZ1JFaTlYeTI5cHk4bWg1VVdjZDV1OGViQXdjbkh3LUQ5WGFJMk9iOXBsRWllOXd5a2ZkSlNwX083QU5TRXRPRzBfZnNEcG9VYVE?oc=5",
    "published": "2026-06-04",
    "summary": "AI时代的“算力”期货市场什么样？&nbsp;&nbsp;Sina finance",
    "full_text": "「AI时代的“算力”期货市场什么样？」\n\n来源：Sina finance\n发布日期：2026-06-04\n\n本文由 Google News 聚合自 Sina finance。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "GPU Marketplace: Vast.ai vs Shadeform vs Prime Intellect",
    "source": "AIMultiple",
    "source_url": "https://aimultiple.com",
    "url": "https://news.google.com/rss/articles/CBMiT0FVX3lxTE05UkhpZ0xPYmpjQzI0dFFLb3hhRmUxdkNGRWxhZVZySVNKdElSOVloR2Y1RUFaWnc5bVBMYURseHdmcGJuTmJMcngtbFhxM2s?oc=5",
    "published": "2026-06-03",
    "summary": "GPU Marketplace: Vast.ai vs Shadeform vs Prime Intellect&nbsp;&nbsp;AIMultiple",
    "full_text": "「GPU 市场：Vast.ai、Shadeform、Prime Intellect」\n\nSource: AIMultiple\nPublished: 2026-06-03\n\nOriginal: GPU Marketplace: Vast.ai vs Shadeform vs Prime Intellect\n\nThis article is aggregated from AIMultiple via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "GPU 市场：Vast.ai、Shadeform、Prime Intellect",
    "summary_cn": "GPU 市场：Vast.ai vs Shadeform vs Prime Intellect AIMultiple",
    "translated": true,
    "full_text_cn": "「GPU市场：Vast.ai、Shadeform、Prime Intellect」\n\n来源：AIMultiple\n发布时间：2026-06-03\n\n原文：GPU 市场：Vast.ai vs Shadeform vs Prime Intellect\n\n本文来自 AIMultiple 通过 Google 新闻汇总。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "大模型降价利好算力租赁市场",
    "source": "财富号",
    "source_url": "https://caifuhao.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1MU1EyMGdqaHlzY0ZHZXpUbHFtanFyU0VidUw1VkFOSlRRY284YnBOX3c4bHFNdzl1X2ktVVlQdkpBUXFyMzVmWVpIT19faHkzTVlYaFFZd09QV0k4akZiN3hzN0dvU05JWDRr?oc=5",
    "published": "2026-06-03",
    "summary": "大模型降价利好算力租赁市场&nbsp;&nbsp;财富号",
    "full_text": "「大模型降价利好算力租赁市场」\n\n来源：财富号\n发布日期：2026-06-03\n\n本文由 Google News 聚合自 财富号。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "凤凰传媒：公司目前不涉及算力租赁业务",
    "source": "东方财富",
    "source_url": "https://wap.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE1BODBvNlFfZERndVVZamlraVVkdmJ4QXlXRjd4Y1FQMWRGUU5tYWZSUXNGZXdKRHJIWmRUWFZtMmpTMXFIYlVzeWYzYkpaUlFycUxCUDdVY2JuU3UwVmxGUw?oc=5",
    "published": "2026-05-29",
    "summary": "凤凰传媒：公司目前不涉及算力租赁业务&nbsp;&nbsp;东方财富",
    "full_text": "「凤凰传媒：公司目前不涉及算力租赁业务」\n\n来源：东方财富\n发布日期：2026-05-29\n\n本文由 Google News 聚合自 东方财富。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "GPU as a Service Market Size, Share | Industry Report [2034]",
    "source": "Fortune Business Insights",
    "source_url": "https://www.fortunebusinessinsights.com",
    "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTE9QMFhxUVU5aDB1cklWZDNReDhFMzhNczAxWEpDWjM0ZWdVRDVKZndXa0dURllVa1B5Q0FkMVlwRUZ5SEhEdllVR2ViQVpXS2FaXzB0MFptMGdwUk1adWZfWWxCOVJreG44T1BEWURGQ1FEaGNNckRIZWtB?oc=5",
    "published": "2026-05-25",
    "summary": "GPU as a Service Market Size, Share | Industry Report [2034]&nbsp;&nbsp;Fortune Business Insights",
    "full_text": "「GPU 即服务市场规模、份额 |行业报告[2034]」\n\nSource: Fortune Business Insights\nPublished: 2026-05-25\n\nOriginal: GPU as a Service Market Size, Share | Industry Report [2034]\n\nThis article is aggregated from Fortune Business Insights via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "GPU 即服务市场规模、份额 |行业报告[2034]",
    "summary_cn": "GPU 即服务市场规模、份额 |行业报告[2034] 财富商业洞察",
    "translated": true,
    "full_text_cn": "「GPU即服务市场规模、贡献|行业报告[2034]」\n\n资料来源：财富商业洞察\n发布时间：2026-05-25\n\n原文：GPU 即服务市场规模、分享 |行业报告[2034]\n\n本文通过 Google 新闻汇总自《财富商业洞察》。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "算力租赁的“下一站”：Token运营",
    "source": "华尔街见闻",
    "source_url": "https://wallstreetcn.com",
    "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFAwUnFfZFFlb2VyRFdlbUNyaDExRzViMjU4c3FKVFhnMGc0V0xwdkZOd3ctajZHWWJTdDQ0bWc0bDZDRjFyb292UXMzdkh3VVM3aTJr?oc=5",
    "published": "2026-05-25",
    "summary": "算力租赁的“下一站”：Token运营&nbsp;&nbsp;华尔街见闻",
    "full_text": "「算力租赁的“下一站”：Token运营」\n\n来源：华尔街见闻\n发布日期：2026-05-25\n\n本文由 Google News 聚合自 华尔街见闻。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "天威视讯：公司暂时未涉及算力租赁",
    "source": "东方财富",
    "source_url": "https://finance.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFAzMGhxNmlDQndRSlRvaHp3WHB1Vzc4S1NiR2NoaWVkOEtuYzZtUHluaXJzYU9Zc3d1dXpDUE1EdlpSZGc5ZjUyelhEajZTaHNVWDVobmN2VkQzbjFCcXJ4QzY3Z2RCdw?oc=5",
    "published": "2026-05-25",
    "summary": "天威视讯：公司暂时未涉及算力租赁&nbsp;&nbsp;东方财富",
    "full_text": "「天威视讯：公司暂时未涉及算力租赁」\n\n来源：东方财富\n发布日期：2026-05-25\n\n本文由 Google News 聚合自 东方财富。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "4.8 万美元买 GPU 服务器值不值？实测节省 1.7 万，成果获 40 多万次浏览！",
    "source": "blog.csdn.net",
    "source_url": "https://blog.csdn.net",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5nV2cyNUZpRnFRY1g5cHJOenpfZG5SMU9NYmRwUVhhU1gtaWVfQV9MX2h6X184VVRCRU1PNzAteWRzdm5hbjB5LS1oVGFQdVF4amhrcUhINEN3cjhNQ2FwVUR6c1lXMnl0c09B?oc=5",
    "published": "2026-05-22",
    "summary": "4.8 万美元买 GPU 服务器值不值？实测节省 1.7 万，成果获 40 多万次浏览！&nbsp;&nbsp;blog.csdn.net",
    "full_text": "「4.8 万美元买 GPU 服务器值不值？实测节省 1.7 万，成果获 40 多万次浏览！」\n\n来源：blog.csdn.net\n发布日期：2026-05-22\n\n本文由 Google News 聚合自 blog.csdn.net。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Anthropic rents Colossus 1 for $1.25 billion/month on an xAI park capped at 11% capacity",
    "source": "ActuIA",
    "source_url": "https://www.actuia.com",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxNSElPVFFaMVlvU2U1TFpNRFQ0WklhZFZXdUxhNS1GYzJOWlZ2a3BuNFZFOGw0bzM1c0wyT01NWTNBLUpoZ05kdGd1aHpxazhGN0ZyTHllMWNyWDVvMTNJTDl0ZDhZX1pZQlU5SUdOQWFkTGlHWFBsXzBnYk1MVGxIdjBFZi1qS1NlYjRrdC1pbFA4cGlYV2o3dkVTcmRyeWdNV0ZzdGk2dnY4WFhZcVhERjlBMzJ3amc?oc=5",
    "published": "2026-05-21",
    "summary": "Anthropic rents Colossus 1 for $1.25 billion/month on an xAI park capped at 11% capacity&nbsp;&nbsp;ActuIA",
    "full_text": "「Anthropic 以每月 12.5 亿美元的价格租用 Colossus 1，其 xAI 园区容量上限为 11%」\n\nSource: ActuIA\nPublished: 2026-05-21\n\nOriginal: Anthropic rents Colossus 1 for $1.25 billion/month on an xAI park capped at 11% capacity\n\nThis article is aggregated from ActuIA via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "Anthropic 以每月 12.5 亿美元的价格租用 Colossus 1，其 xAI 园区容量上限为 11%",
    "summary_cn": "Anthropic 以每月 12.5 亿美元的价格在 xAI 园区租用 Colossus 1，容量上限为 11% ActuIA",
    "translated": true,
    "full_text_cn": "「Anthropic 每月以 12.5 亿美元的价格租用 Colossus 1，其 xAI 园区容量上限为 11%」\n\n资料来源：ActuIA\n发布时间：2026-05-21\n\n原文：Anthropic 以每月 12.5 亿美元的价格在 xAI 园区租用 Colossus 1，容量上限为 11%\n\n本文是通过 Google 新闻从 ActuIA 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "AI 'compute capacity anxiety' reignites! NVIDIA H100 GPU rental prices rise, cloud providers like NEBIUS (NBIS.US) surge in response",
    "source": "Moomoo",
    "source_url": "https://www.moomoo.com",
    "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxNbG1OTDBiZC1JdDZyVDlpbkFmRkJQajV0TDcySTdaUlQyUXBzSTUzY0YxV1dkSWQ5VWdkWHdvN0NvaHVwcE1GV05pRnFHQkRqYXlpcDFaRW9QQUpMckdaRDdJUV9SbFNZalB4MWFudGZhZkJ1Y3lwVlFKUlBrLU4wTEZyc1NlR1FKaDl6T19BMm4yTmZuWm94dTNZZnI0LTFFNEpXWkVId1Nmc3AyTXc?oc=5",
    "published": "2026-05-21",
    "summary": "AI 'compute capacity anxiety' reignites! NVIDIA H100 GPU rental prices rise, cloud providers like NEBIUS (NBIS.US) surge in response&nbsp;&nbsp;Moomoo",
    "full_text": "「AI“计算能力焦虑”重燃！ NVIDIA H100 GPU租赁价格上涨，NEBIUS (NBIS.US)等云提供商响应激增」\n\nSource: Moomoo\nPublished: 2026-05-21\n\nOriginal: AI 'compute capacity anxiety' reignites! NVIDIA H100 GPU rental prices rise, cloud providers like NEBIUS (NBIS.US) surge in response\n\nThis article is aggregated from Moomoo via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "AI“计算能力焦虑”重燃！ NVIDIA H100 GPU租赁价格上涨，NEBIUS (NBIS.US)等云提供商响应激增",
    "summary_cn": "AI“计算能力焦虑”重燃！ NVIDIA H100 GPU 租赁价格上涨，NEBIUS (NBIS.US) 等云提供商响应激增 &nbsp; &nbsp;Moomoo",
    "translated": true,
    "full_text_cn": "「AI“计算能力焦虑”重燃！NVIDIA H100 GPU 租赁价格上涨，NEBIUS (NBIS.US) 等云实现高峰响应》\n\n来源：Moomoo\n发布时间：2026-05-21\n\n原文：AI“计算能力焦虑”重燃！ NVIDIA H100 GPU租赁价格上涨，NEBIUS (NBIS.US)等云提供商响应激增\n\n本文是通过 Google 新闻从 Moomoo 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "600358 重要收购！算力租赁热门股获两大资金同时大幅抢筹",
    "source": "东方财富",
    "source_url": "https://wap.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiYEFVX3lxTE9NaU9PNnh1S0dNVEg2eDV5b2pfZmsxQVQyWGItdVk5dURObjRsdlZYMXRtWGEtLXpxeGNwNkdzVG5QQmk0dWdTbm1pNUN6YXBxa0ttYkhiNndOVDZEY285Ug?oc=5",
    "published": "2026-05-20",
    "summary": "600358 重要收购！算力租赁热门股获两大资金同时大幅抢筹&nbsp;&nbsp;东方财富",
    "full_text": "「600358 重要收购！算力租赁热门股获两大资金同时大幅抢筹」\n\n来源：东方财富\n发布日期：2026-05-20\n\n本文由 Google News 聚合自 东方财富。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "热点丨算力期货来了，AI行业定价权重新洗牌",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE5ZTmVHck5PemQ5QVVjTmVyS0kxOFJYQVIyVFlwRWwybzFZQ1JWZnRPdUE2b0pmenNPcVVoYnMtMnV4NHNNZHlLdDByY2xLOXljYzVyUEUwRHdiSENpUFJOZlN6VXBWa0xobmV5RzFEWWpSRG5JMnc?oc=5",
    "published": "2026-05-18",
    "summary": "热点丨算力期货来了，AI行业定价权重新洗牌&nbsp;&nbsp;Sina finance",
    "full_text": "「热点丨算力期货来了，AI行业定价权重新洗牌」\n\n来源：Sina finance\n发布日期：2026-05-18\n\n本文由 Google News 聚合自 Sina finance。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力基础设施 “涨价潮”：IDC 与 GPU 租赁的定价权博",
    "source": "财经号",
    "source_url": "http://mp.cnfol.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE9DYzRQZThkb3p1UkRIRzVuMUVHZWVfLUdTZEZZYnVlSzUxdGJHSGhOQnUzYWhzaUNZWHFfY2tiR0owYVh0ekVTal91MW5yTDFQdVdtVFp3SWprRlNOYXJBV0VEZTlzd2ZVWmVr?oc=5",
    "published": "2026-05-15",
    "summary": "算力基础设施 “涨价潮”：IDC 与 GPU 租赁的定价权博&nbsp;&nbsp;财经号",
    "full_text": "「算力基础设施 “涨价潮”：IDC 与 GPU 租赁的定价权博」\n\n来源：财经号\n发布日期：2026-05-15\n\n本文由 Google News 聚合自 财经号。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Live GPU Rental Listings Point to Early Price Compression",
    "source": "Data Center Knowledge",
    "source_url": "https://www.datacenterknowledge.com",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQRW1pTERHREZDU3h4cEdoZzZlOEpzbFdqcFFxaG5GaXJFOXlBRWxvSlRQZ0NlUkdmN1NrUklVVXd1ME0yYkZNTHhmeDJubEtqX193ZmJXQWhuUk5ycVNGc1kxSE9WWkJzX0R5RmVFa2FSZExhM0ZvSElvRTFySVkyRldrclJRWVFrNlRhZDdTREJyQU5JYjZfT2RhVUQwNzZNbE9vMWp3?oc=5",
    "published": "2026-05-13",
    "summary": "Live GPU Rental Listings Point to Early Price Compression&nbsp;&nbsp;Data Center Knowledge",
    "full_text": "「实时 GPU 租赁列表表明早期价格压缩」\n\nSource: Data Center Knowledge\nPublished: 2026-05-13\n\nOriginal: Live GPU Rental Listings Point to Early Price Compression\n\nThis article is aggregated from Data Center Knowledge via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "实时 GPU 租赁列表表明早期价格压缩",
    "summary_cn": "实时 GPU 租赁列表表明早期价格压缩 数据中心知识",
    "translated": true,
    "full_text_cn": "「实时 GPU 租赁列表演出早期价格压缩」\n\n来源：数据中心知识\n发布时间：2026-05-13\n\n原文：实时 GPU 租赁清单表明早期价格压缩\n\n本文是通过 Google 新闻从数据中心知识汇总而来。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "Nvidia Blackwell GPU Rental Hits .08/hr: Inside the 48% Surge [2026]",
    "source": "tech-insider.org",
    "source_url": "https://tech-insider.org",
    "url": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxOdUdMV0ZBR2cyT0hRbUFZR2ZNWmNvSndyeGdHMFpxMV83M1F6ZUg1OVo3eXRBYjhydE1RNXNPNHZ2aFROaHA5RXRTS2ctYkZ1QXQ2MU5PNng0YXRNTkp4eGxYT3BTTDd3WFdBdm52d2s0d1JvWjdkUE53U3pGRVBJbEs4aFg2ZVpp?oc=5",
    "published": "2026-05-13",
    "summary": "Nvidia Blackwell GPU Rental Hits .08/hr: Inside the 48% Surge [2026]&nbsp;&nbsp;tech-insider.org",
    "full_text": "「Nvidia Blackwell GPU 租金达到 0.08/小时：激增 48% [2026]」\n\nSource: tech-insider.org\nPublished: 2026-05-13\n\nOriginal: Nvidia Blackwell GPU Rental Hits .08/hr: Inside the 48% Surge [2026]\n\nThis article is aggregated from tech-insider.org via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "Nvidia Blackwell GPU 租金达到 0.08/小时：激增 48% [2026]",
    "summary_cn": "Nvidia Blackwell GPU 租金达到 0.08/小时：激增 48% [2026]&nbsp;&nbsp;tech-insider.org",
    "translated": true,
    "full_text_cn": "「Nvidia Blackwell GPU 租金达到 0.08/小时：突破 48% [2026]」\n\n资料来源：tech-insider.org\n发布时间：2026-05-13\n\n原文：Nvidia Blackwell GPU 租金达到 0.08/小时：飙升 48% [2026]\n\n本文是通过 Google 新闻从 tech-insider.org 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "Traders will soon be able to bet on computer chip prices as AI drives costs skyward",
    "source": "CNBC",
    "source_url": "https://www.cnbc.com",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxPV3ZRVVZpOXRSZ3lpbHFWVnNKblBYcmxCMjRpX2pKYS1NMHY0cWRRcXlXS1A5Y0tiZk9kdlhOS2lmRmtXR2FDdFVvcV9rYUFfc29LZUJTd3pRdEJxdlNOcVRXbExBTVc0V3NPNnU5cG1ONDUtMW9TbHFLOTFIX0JBdU5SelFkbGtOVnowekthQnFrMnVHV0E0RU5IakU3ZDZEek1WVnZTSVQ3Q1nSAbABQVVfeXFMTXFsU1UtbHlfTmE0aXZsVi1hSHZ6UTVyTk9mNnBDOWpGT3AyeURxTnVVcEZJU2R4aFREaVg0VENSQm1BYjVUZWxKUWtoaXpXUVJGNVprRzZSRFZGQnZPc2VNQXZ1dTRoQU9vbTZRWTN6QTBYdDRRdDY4QThHR3NJZHlqemFGVFZGWThXZ2Q5YXV6SFFrbmNXT3kzbWJBczZ3d0NnR2gtYldBc1lHZ0dqZXU?oc=5",
    "published": "2026-05-12",
    "summary": "Traders will soon be able to bet on computer chip prices as AI drives costs skyward&nbsp;&nbsp;CNBC",
    "full_text": "「随着人工智能推动成本飙升，交易员很快就能押注计算机芯片价格」\n\nSource: CNBC\nPublished: 2026-05-12\n\nOriginal: Traders will soon be able to bet on computer chip prices as AI drives costs skyward\n\nThis article is aggregated from CNBC via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "随着人工智能推动成本飙升，交易员很快就能押注计算机芯片价格",
    "summary_cn": "随着人工智能推动成本飙升，交易员很快就能押注计算机芯片价格 &nbsp; &nbsp;CNBC",
    "translated": true,
    "full_text_cn": "「随着人工智能推动成本激增，交易员很快就能押注计算机芯片价格」\n\n来源：CNBC\n发布时间：2026-05-12\n\n原文：随着人工智能推动成本飙升，交易员很快就能押注计算机芯片价格\n\n本文通过 Google 新闻从 CNBC 汇总。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "算力租赁隐秘江湖：赢家藏在巨头指缝间",
    "source": "caijing.com.cn",
    "source_url": "https://m.caijing.com.cn",
    "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFBxdlM4eWs4VzNEVElLM0lBWFRUQ0VZZ3dGRE8xVGVxRmtJVldGYmk1MzE2Vk1lbGhpX0s0d0tONkFrU25PbVV0NWFOb3Y2RGh0YmxF?oc=5",
    "published": "2026-05-08",
    "summary": "算力租赁隐秘江湖：赢家藏在巨头指缝间&nbsp;&nbsp;caijing.com.cn",
    "full_text": "「算力租赁隐秘江湖：赢家藏在巨头指缝间」\n\n来源：caijing.com.cn\n发布日期：2026-05-08\n\n本文由 Google News 聚合自 caijing.com.cn。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力太紧张！微软等云服务商被曝对中小客户“挑挑拣拣”",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFB2Vkd2a1RreXhrS3Zkc0J5ZmpheDZQVFhhZG9OSGl6eWV6X2lVVDgxUVplRlJjTkJ0RFFhTzM2UjYwWko0cGhRaQ?oc=5",
    "published": "2026-04-25",
    "summary": "算力太紧张！微软等云服务商被曝对中小客户“挑挑拣拣”&nbsp;&nbsp;财联社",
    "full_text": "「算力太紧张！微软等云服务商被曝对中小客户“挑挑拣拣”」\n\n来源：财联社\n发布日期：2026-04-25\n\n本文由 Google News 聚合自 财联社。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "微软等云厂商收紧GPU资源管控 AI企业承压",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxPUFhvWDF3SVVvejIwdV9WelZyVTlUa3VKVkVNVFFFUkszcjdfR1ZYdnBDeDdVU29jOWxIbjRpODZkcnVpQ3ZoVlh6STUyOHM0VnJqTEV5c0FMSlEyYTJSUVRoQ245UFIzV3pObE1CN0k4LUJNTkVKdjhfdDJvZWpVQkJuWm5vSWdxb0VGZk1wOFJCSlgzQkE?oc=5",
    "published": "2026-04-24",
    "summary": "微软等云厂商收紧GPU资源管控 AI企业承压&nbsp;&nbsp;Sina finance",
    "full_text": "「微软等云厂商收紧GPU资源管控 AI企业承压」\n\n来源：Sina finance\n发布日期：2026-04-24\n\n本文由 Google News 聚合自 Sina finance。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "CoreWeave算力租赁模式_新浪新闻",
    "source": "手机新浪网",
    "source_url": "https://www.sina.cn",
    "url": "https://news.google.com/rss/articles/CBMiY0FVX3lxTE5DRVVJRTRPT3ZYbjkzUEREYzRsd0h6UXJsTHgyampub0NRS1g1UmRrdzdreFp1OXp2dHUzWTVVa29JZmlHbnJuZTBPaElHamx3V2phZlRtQkhpRjZzNmhFQWhxUQ?oc=5",
    "published": "2026-04-23",
    "summary": "CoreWeave算力租赁模式_新浪新闻&nbsp;&nbsp;手机新浪网",
    "full_text": "「CoreWeave算力租赁模式_新浪新闻」\n\n来源：手机新浪网\n发布日期：2026-04-23\n\n本文由 Google News 聚合自 手机新浪网。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力租赁：中国AI新核心资产",
    "source": "华尔街见闻",
    "source_url": "https://wallstreetcn.com",
    "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE9JaHFnMkluRUZMN0FqdnVJYW5VSV9JRFhVZkR5U0VmS1VvclZTbU1iLXhlMG1NczdEUk1iOHNLOG9vOVBNLTFITzVObXZVTnluWk1Z?oc=5",
    "published": "2026-04-22",
    "summary": "算力租赁：中国AI新核心资产&nbsp;&nbsp;华尔街见闻",
    "full_text": "「算力租赁：中国AI新核心资产」\n\n来源：华尔街见闻\n发布日期：2026-04-22\n\n本文由 Google News 聚合自 华尔街见闻。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Best 10 Serverless GPU Clouds & 14 Cost-Effective GPUs",
    "source": "AIMultiple",
    "source_url": "https://aimultiple.com",
    "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTFBIby10d0x0a29mR21xQTRBWU5TaXQwSHVvVVhia2dUVzg0N1lrZEJaS0YwcVc0bnFPVktub25XdXV1WE4td3duY19JZW1KZw?oc=5",
    "published": "2026-04-15",
    "summary": "Best 10 Serverless GPU Clouds & 14 Cost-Effective GPUs&nbsp;&nbsp;AIMultiple",
    "full_text": "「最佳 10 个无服务器 GPU 云和 14 个经济高效的 GPU」\n\nSource: AIMultiple\nPublished: 2026-04-15\n\nOriginal: Best 10 Serverless GPU Clouds & 14 Cost-Effective GPUs\n\nThis article is aggregated from AIMultiple via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "最佳 10 个无服务器 GPU 云和 14 个经济高效的 GPU",
    "summary_cn": "最佳 10 个无服务器 GPU 云和 14 个经济高效的 GPU AIMultiple",
    "translated": true,
    "full_text_cn": "「最佳10个无服务器GPU云和14个经济高效的GPU」\n\n来源：AIMultiple\n发布时间：2026-04-15\n\n原文：最佳 10 个无服务器 GPU 云和 14 个经济高效的 GPU\n\n本文来自 AIMultiple 通过 Google 新闻汇总。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "算力租赁价格暴涨48%！协创数据20%涨停，机构称算力租赁厂商议价权有望提升",
    "source": "金融界",
    "source_url": "https://m.jrj.com.cn",
    "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE5uc2pEdDFEMGVzR25qUFNqMHE3QXRSZl93RWdRWm9MVTdtc0pjUGFQRTdGOUx1YUsyc29pTWRtQTE2YU1ONVpsQmZlRGRTejJpM1dHTUROb19tZEdzTVZQZzVRT2xxWFpOUmpJMFo2dnVhQQ?oc=5",
    "published": "2026-04-14",
    "summary": "算力租赁价格暴涨48%！协创数据20%涨停，机构称算力租赁厂商议价权有望提升&nbsp;&nbsp;金融界",
    "full_text": "「算力租赁价格暴涨48%！协创数据20%涨停，机构称算力租赁厂商议价权有望提升」\n\n来源：金融界\n发布日期：2026-04-14\n\n本文由 Google News 聚合自 金融界。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "算力紧缺程度较高 机构称算力租赁厂商议价权有望提升",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE1kVFlmMVNGdXo4RXpSVEJhdUpfdVZadmtOTFlhNC0xQW9iRVlrdzlDUjZkc2VJUVVYZ1JiLWZYSFZXaGtISVdsXw?oc=5",
    "published": "2026-04-14",
    "summary": "算力紧缺程度较高 机构称算力租赁厂商议价权有望提升&nbsp;&nbsp;财联社",
    "full_text": "「算力紧缺程度较高 机构称算力租赁厂商议价权有望提升」\n\n来源：财联社\n发布日期：2026-04-14\n\n本文由 Google News 聚合自 财联社。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "GPU租金飙涨！高端算力持续紧缺 多只算力租赁概念股获资金青睐",
    "source": "东方财富",
    "source_url": "https://wap.eastmoney.com",
    "url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE1iSmRCNEc1NzduUEhPbnVWSnlReTBMUjIyUXQwUWpTQVdTNF9QblVoMGtBMm5jcG5VY2VZdmJFcmQxVFI3cTdlVi1kRllMZWxOcklWcWlqOW9pMGY2eHNKWlktb1ZPbEU?oc=5",
    "published": "2026-04-14",
    "summary": "GPU租金飙涨！高端算力持续紧缺 多只算力租赁概念股获资金青睐&nbsp;&nbsp;东方财富",
    "full_text": "「GPU租金飙涨！高端算力持续紧缺 多只算力租赁概念股获资金青睐」\n\n来源：东方财富\n发布日期：2026-04-14\n\n本文由 Google News 聚合自 东方财富。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "AI Cloud GPU Rental Platform Opens New Passive Income",
    "source": "GlobeNewswire",
    "source_url": "https://www.globenewswire.com",
    "url": "https://news.google.com/rss/articles/CBMiqAJBVV95cUxOb0FPY3JZS2lVVHRrRm94X1dISmxqSHlaOFQwVFM5dDVuUzhwQjhPRXpRSUJubF9zOEx4eFI0dmppZFBJSzlUTFV3d1VOdjc3VkZEbXdQZ3VNb3RKN1NxbWlObXljV05NOWY5aGtLOElHMF96WjNLYW9oamplVE4xTHdnNjgydjcxdU4tbjQ4RWZXUVAxT3ZRX2licndIUkI0QUtEYkVPel9tN1lfV3NPeTlRQ2FsTlIwQkhQdWZub2pOTm1PcEJrMU45UlE4dllPbl9pbkxiWWs0RDhqNmxUMUN2VktaeUdOck1UOFFicC1jc3NjOGxfZkQ5LWVSRE5EWkVJRDgzRUNrMVJWY2VsNmlDUzdUUl9xT1NnUW84Q1U3U2MwVXhDdA?oc=5",
    "published": "2026-04-13",
    "summary": "AI Cloud GPU Rental Platform Opens New Passive Income&nbsp;&nbsp;GlobeNewswire",
    "full_text": "「AI云GPU租赁平台开启新的被动收入」\n\nSource: GlobeNewswire\nPublished: 2026-04-13\n\nOriginal: AI Cloud GPU Rental Platform Opens New Passive Income\n\nThis article is aggregated from GlobeNewswire via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "AI云GPU租赁平台开启新的被动收入",
    "summary_cn": "AI云GPU租赁平台开启新的被动收入&nbsp;&nbsp;GlobeNewswire",
    "translated": true,
    "full_text_cn": "「AI云GPU租赁平台开启新的密码收入」\n\n资料来源：环球通讯社\n发布时间：2026-04-13\n\n原文：AI云GPU租赁平台开启新的被动收入\n\n本文是通过 Google 新闻从 GlobeNewswire 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "NVIDIA (NVDA) GPU Rental Prices Surge in Cloud Data Centers",
    "source": "GuruFocus",
    "source_url": "https://www.gurufocus.com",
    "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxQQXRFUTE0U0dNdTdha2V2MGZZMEpzRTc5WjRmMnRCVVJ2Tll1RUZyVWpmUElKUEtPdEMxbm1IMkdUT3pNLWVkaWhiVzRMeXdHaERsVGYxRnpSZ3A0WmR6ajZjYTlYVzdRc0dUZnFOMGJFek5JZFZVeU5iRmhDaTcyWkUzSTJ1Rzh4LWwtTGxIcmphejRuN2ViZXgwS1pqcHAwUmJuUXlGTXBzeVc4?oc=5",
    "published": "2026-04-13",
    "summary": "NVIDIA (NVDA) GPU Rental Prices Surge in Cloud Data Centers&nbsp;&nbsp;GuruFocus",
    "full_text": "「NVIDIA (NVDA) 云数据中心 GPU 租赁价格飙升」\n\nSource: GuruFocus\nPublished: 2026-04-13\n\nOriginal: NVIDIA (NVDA) GPU Rental Prices Surge in Cloud Data Centers\n\nThis article is aggregated from GuruFocus via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "NVIDIA (NVDA) 云数据中心 GPU 租赁价格飙升",
    "summary_cn": "云数据中心的 NVIDIA (NVDA) GPU 租赁价格飙升 &nbsp;&nbsp;GuruFocus",
    "translated": true,
    "full_text_cn": "「NVIDIA (NVDA) 云数据中心 GPU 租赁价格激增」\n\n资料来源：GuruFocus\n发布时间：2026-04-13\n\n原文：NVIDIA (NVDA) 云数据中心 GPU 租赁价格飙升\n\n本文是通过 Google 新闻从 GuruFocus 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "Why Nvidia GPU prices are 'going nuts,' according to one CEO",
    "source": "Business Insider",
    "source_url": "https://www.businessinsider.com",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxNVzFQQm5KYXNXZ0tBZ3JoRC1Xd2E5eGlRMXpxMDQ4UWFBb09WNy03OE1fek1FQm5vZEYxRTgwQW85TXcxcXJJNl9xRHRJQzRHN2pweVpJbUtMQWUyYndMYkpJYTZEU0NLU0k2ZDU4VEVNUFYtQmpCbEU1cDRQRzJUQmxTaUN4ZzRFZW02OVQzZ2U4RXNiQnVpeg?oc=5",
    "published": "2026-04-06",
    "summary": "Why Nvidia GPU prices are 'going nuts,' according to one CEO&nbsp;&nbsp;Business Insider",
    "full_text": "「一位首席执行官表示，为何 Nvidia GPU 价格“疯涨”」\n\nSource: Business Insider\nPublished: 2026-04-06\n\nOriginal: Why Nvidia GPU prices are 'going nuts,' according to one CEO\n\nThis article is aggregated from Business Insider via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "一位首席执行官表示，为何 Nvidia GPU 价格“疯涨”",
    "summary_cn": "一位首席执行官表示，为什么 Nvidia GPU 价格“疯涨”&nbsp;&nbsp;Business Insider",
    "translated": true,
    "full_text_cn": "「一位多数表示，为何 Nvidia GPU 价格“疯涨”」\n\n资料来源：商业内幕\n发布时间：2026-04-06\n\n原文：一位首席执行官表示，为何 Nvidia GPU 价格“疯狂”\n\n本文是通过 Google 新闻从 Business Insider 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "算力太紧俏！英伟达四年前发布的H100租赁费用近半年飙升近40%",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE5hZENZcndneG9OTUh1SHk5SkNuMXo4SVlPcllRcUhxVnVid29YS0ZzYVhBN21QNDVqREktQks2c2lFM1J0X0ZYVQ?oc=5",
    "published": "2026-04-03",
    "summary": "算力太紧俏！英伟达四年前发布的H100租赁费用近半年飙升近40%&nbsp;&nbsp;财联社",
    "full_text": "「算力太紧俏！英伟达四年前发布的H100租赁费用近半年飙升近40%」\n\n来源：财联社\n发布日期：2026-04-03\n\n本文由 Google News 聚合自 财联社。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "英伟达4年前的老芯片，租赁价格5个月涨40%",
    "source": "第一财经",
    "source_url": "https://www.yicai.com",
    "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE56Ykw2RmZQUnVfc1l4aFlxSnpTMHBYdUNlYk03RUFRMEY3UHJlLUtKSWxrUnFJM1pJazBtalhRTjNpblpqTVZSMlNUSnRWMlozNEVj?oc=5",
    "published": "2026-04-03",
    "summary": "英伟达4年前的老芯片，租赁价格5个月涨40%&nbsp;&nbsp;第一财经",
    "full_text": "「英伟达4年前的老芯片，租赁价格5个月涨40%」\n\n来源：第一财经\n发布日期：2026-04-03\n\n本文由 Google News 聚合自 第一财经。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "The Great GPU Shortage – Rental Capacity – Launching our H100 1 Year Rental Price Index",
    "source": "SemiAnalysis",
    "source_url": "https://newsletter.semianalysis.com",
    "url": "https://news.google.com/rss/articles/CBMiggFBVV95cUxPVHJVcTNIVXFVM1F4Z1JRbk44eV9KVENUTlVuamhlQlVZWENmR2lzYnVyUVpxQkRFTGVzX0dJcjZaSXBrRlUtT3NTT3kwdk1jSUhIanlPZFVON3pyS215RXlEdnBPY3hRRUoxNzlJTjAtajliTV9ORC1yM2x5RmlPSmV3?oc=5",
    "published": "2026-04-01",
    "summary": "The Great GPU Shortage – Rental Capacity – Launching our H100 1 Year Rental Price Index&nbsp;&nbsp;SemiAnalysis",
    "full_text": "「GPU 严重短缺 – 租赁容量 – 推出我们的 H100 1 年租赁价格指数」\n\nSource: SemiAnalysis\nPublished: 2026-04-01\n\nOriginal: The Great GPU Shortage – Rental Capacity – Launching our H100 1 Year Rental Price Index\n\nThis article is aggregated from SemiAnalysis via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "GPU 严重短缺 – 租赁容量 – 推出我们的 H100 1 年租赁价格指数",
    "summary_cn": "GPU 严重短缺 - 租赁能力 - 推出我们的 H100 1 年租赁价格指数 &nbsp;&nbsp;SemiAnalysis",
    "translated": true,
    "full_text_cn": "「GPU 严重期待 – 租赁能力 – 推出我们的 H100 1 年租赁价格指数」\n\n资料来源：半分析\n发布时间：2026-04-01\n\n原文：GPU 严重短缺 – 租赁容量 – 推出我们的 H100 1 年租赁价格指数\n\n本文是通过 Google 新闻从 SemiAnalysis 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "Why developers are choosing contract-free GPU deployments",
    "source": "businesscloud.co.uk",
    "source_url": "https://businesscloud.co.uk",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxOMjdqTFlaYkR6OENRelUySGlNVWFxckw3ekRZdWdIV2Z5cEYtd0plSjhWREd2bG9seGtYZnV0VlRMSzAtUkRzUUVPeW05NkZOaWpyVTJsRk5MeDRpajFWNks0bDMzNDBXOHY1aW8wUTJ1Umc0b2Z4MGtiNzEwWmJzRHZEVkFpQTYyUnB1eUdBMEhHQVdkN1E?oc=5",
    "published": "2026-03-24",
    "summary": "Why developers are choosing contract-free GPU deployments&nbsp;&nbsp;businesscloud.co.uk",
    "full_text": "「为什么开发人员选择无合同 GPU 部署」\n\nSource: businesscloud.co.uk\nPublished: 2026-03-24\n\nOriginal: Why developers are choosing contract-free GPU deployments\n\nThis article is aggregated from businesscloud.co.uk via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "为什么开发人员选择无合同 GPU 部署",
    "summary_cn": "",
    "translated": true,
    "full_text_cn": "「为什么开发人员选择无合同GPU部署」\n\n资料来源：businesscloud.co.uk\n发布时间：2026-03-24\n\n原文：为什么开发人员选择无合同 GPU 部署\n\n本文是通过 Google 新闻从businesscloud.co.uk 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "“龙虾”爆火，Token调用量激增，云厂商涨价推动算力租赁行业迎来新拐点",
    "source": "财经号",
    "source_url": "http://mp.cnfol.com",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1yeVhDTmpaVzA4RVlfeUszclZtYUJNendXdEdpV1VtbWxBMUVWYXFncndCMU5qakg2RENreUxvajM0NFdpdG5lX2Fkakp6YkhpbUZ1cXNmU0hKQy1YY1hNeVNUQWttaVFCTzhB?oc=5",
    "published": "2026-03-20",
    "summary": "“龙虾”爆火，Token调用量激增，云厂商涨价推动算力租赁行业迎来新拐点&nbsp;&nbsp;财经号",
    "full_text": "「“龙虾”爆火，Token调用量激增，云厂商涨价推动算力租赁行业迎来新拐点」\n\n来源：财经号\n发布日期：2026-03-20\n\n本文由 Google News 聚合自 财经号。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "A practical guide to the 6 categories of AI cloud infrastructure in 2026",
    "source": "The New Stack",
    "source_url": "https://thenewstack.io",
    "url": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9obVk1WFRMb0c0UkJ5akVLZ1pqNkNybEdBSWxUdi1SaHRQRHdjaVA4TVpCTy1wN2c2VmRZRjhLUDZnTDNyZUZPY3FSY1pLZlJVN010SXdtRHdHdw?oc=5",
    "published": "2026-03-15",
    "summary": "A practical guide to the 6 categories of AI cloud infrastructure in 2026&nbsp;&nbsp;The New Stack",
    "full_text": "「2026年6大类AI云基础设施实用指南」\n\nSource: The New Stack\nPublished: 2026-03-15\n\nOriginal: A practical guide to the 6 categories of AI cloud infrastructure in 2026\n\nThis article is aggregated from The New Stack via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "2026年6大类AI云基础设施实用指南",
    "summary_cn": "2026年6大类AI云基础设施实用指南&nbsp;&nbsp;The New Stack",
    "translated": true,
    "full_text_cn": "「2026年6大类AI云基础设施实用指南」\n\n资料来源：新堆栈\n发布时间：2026-03-15\n\n原文：2026年6大类AI云基础设施实用指南\n\n本文是通过 Google 新闻从 The New Stack 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "中国AI调用量首超美国，引发冰火两重天！国产算力、云计算、数据中心掀涨停潮，英伟达一天蒸发1.77万亿",
    "source": "Sina finance",
    "source_url": "https://finance.sina.com.cn",
    "url": "https://news.google.com/rss/articles/CBMieEFVX3lxTFAwN1lleWwxdThRUDVwZ2JHZkJXbjQxT0pHQVg3MUE1TnNrZGRsTzlfb0s5OUpvWkNSa2h4NzRvWlJ2bHFPOEZBSERoNmxRRm5JTG5xMlJGSW45aTlzdjEzTEZLeDFOZlZ6Z3pPYW5mdnZoYms5bUVfOA?oc=5",
    "published": "2026-02-27",
    "summary": "中国AI调用量首超美国，引发冰火两重天！国产算力、云计算、数据中心掀涨停潮，英伟达一天蒸发1.77万亿&nbsp;&nbsp;Sina finance",
    "full_text": "「中国AI调用量首超美国，引发冰火两重天！国产算力、云计算、数据中心掀涨停潮，英伟达一天蒸发1.77万亿」\n\n来源：Sina finance\n发布日期：2026-02-27\n\n本文由 Google News 聚合自 Sina finance。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "2026算力市场开局：显卡商转行炒内存 “套牌车”混进服务器 业内驳算力泡沫论|传真",
    "source": "财联社",
    "source_url": "https://www.cls.cn",
    "url": "https://news.google.com/rss/articles/CBMiSEFVX3lxTFBCblRmdXYxTy1hUHpWVlc4YTVSMDduazRiTW95SzNFVlkyYnVYTnJhSEk5YWVsQUo0aE0wTW8tZkp4OW03bHJ1Ug?oc=5",
    "published": "2026-01-22",
    "summary": "2026算力市场开局：显卡商转行炒内存 “套牌车”混进服务器 业内驳算力泡沫论|传真&nbsp;&nbsp;财联社",
    "full_text": "「2026算力市场开局：显卡商转行炒内存 “套牌车”混进服务器 业内驳算力泡沫论|传真」\n\n来源：财联社\n发布日期：2026-01-22\n\n本文由 Google News 聚合自 财联社。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Cloud Computing Gets Transparent With Silicon Data GPU Index",
    "source": "AI CERTs",
    "source_url": "https://www.aicerts.ai",
    "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNajFHRVNwbTgxOWM1bmRFR3F4anNKcFRBbUFjWEhoTnl1Q1Z1NE9kYjdubVJFbnU5aEpkS1dyNzd2ZjBQWldBOWVYamtFSHE1ODJFUXl3U19GRnNBR29yV0ZMLTFfd0dsd18tTE1xOEpSTFFUU2tvZTU0dmhHT1BpMjV3azA1TFp5ejEtaTFvOEtMdHc?oc=5",
    "published": "2026-01-20",
    "summary": "Cloud Computing Gets Transparent With Silicon Data GPU Index&nbsp;&nbsp;AI CERTs",
    "full_text": "「Silicon Data GPU 索引使云计算变得透明」\n\nSource: AI CERTs\nPublished: 2026-01-20\n\nOriginal: Cloud Computing Gets Transparent With Silicon Data GPU Index\n\nThis article is aggregated from AI CERTs via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "Silicon Data GPU 索引使云计算变得透明",
    "summary_cn": "借助 Silicon Data GPU 索引，云计算变得透明 &nbsp;&nbsp;AI CERT",
    "translated": true,
    "full_text_cn": "「硅数据GPU索引使云计算变得更加透明」\n\n来源：AI CERT\n发布时间：2026-01-20\n\n原文：Silicon Data GPU 指数使云计算变得透明\n\n本文是通过 Google 新闻从 AI CERT 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "U.S. House passes bill to stop Chinese companies from accessing export-controlled American AI chips using offshore rental loophole — Remote Access Security Act effectively extends export controls to the cloud",
    "source": "Tom's Hardware",
    "source_url": "https://www.tomshardware.com",
    "url": "https://news.google.com/rss/articles/CBMikANBVV95cUxPZmVjc19wamdyT0FjNW9BNVJsZkprODhWZG5paExmbU9lMGJmNGN5Tnh6UzJVaTdTUUczWE5RZU9fSkV5bUtYY3lENnVFN3RVWDR2MUpWWmt0d1cweGFReF9GWWdHNkczYmh2U0pFQUlDYXE5TDZYUnl0dmQtZzFXdm9uUGQ0UkN6RGNodU84UFVVMVI1TjNZN09nLTdUY1pNT0RXZExHcnY4UkgtM3d2cldzeThNTFhFR0FoYkdNb1hpQ09QbWVzM0pDVjljekFWTGhZdTBkTDcySHNfeXNidDhFY3RUamRiWWw1NkFTcnhhaGRNalNlS0ZSY0ZTNWhEWFFsaTFyM2g4SklpVXhfNEk5djFhaTB4N1d2V3Zid2ZqR2RPck0tWFJDRllvUEJQTE92NkdjVDI0N3NEUnRXcEVCWGM1ZnBjRWdoT2tFejJyZjNYcWk3QWFsLUIzWVNuSFAtcWpkakhyaHpXVXJSb3d2Yk9CUlVZZzZNTVMyUzFGcXM0V0piUktWdlhoUUZI?oc=5",
    "published": "2026-01-13",
    "summary": "U.S. House passes bill to stop Chinese companies from accessing export-controlled American AI chips using offshore rental loophole — Remote Access Security Act effectively extends export controls to the cloud&nbsp;&nbsp;Tom's Hardware",
    "full_text": "「美国众议院通过法案，阻止中国企业利用离岸租赁漏洞获取受出口管制的美国人工智能芯片——《远程访问安全法案》有效将出口管制延伸至云端」\n\nSource: Tom's Hardware\nPublished: 2026-01-13\n\nOriginal: U.S. House passes bill to stop Chinese companies from accessing export-controlled American AI chips using offshore rental loophole — Remote Access Security Act effectively extends export controls to the cloud\n\nThis article is aggregated from Tom's Hardware via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "美国众议院通过法案，阻止中国企业利用离岸租赁漏洞获取受出口管制的美国人工智能芯片——《远程访问安全法案》有效将出口管制延伸至云端",
    "summary_cn": "美国众议院通过法案，阻止中国公司利用离岸租赁漏洞获取受出口管制的美国人工智能芯片——《远程访问安全法案》有效地将出口管制延伸至云端",
    "translated": true,
    "full_text_cn": "「美国通过法案，阻止中国企业利用离岸房地产漏洞获取受出口管制的美国人工智能芯片——《远程访问安全法案》有效将出口管制延伸至云端」\n\n资料来源：汤姆的硬件\n发布时间：2026-01-13\n\n原文：美国众议院通过法案，阻止中国企业利用离岸租赁漏洞获取受出口管制的美国人工智能芯片——远程访问安全法案有效将出口管制延伸至云端\n\n本文是通过 Google 新闻从 Tom's Hardware 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  },
  {
    "title": "“英伟达亲儿子”CoreWeave(CRWV.US)把违约红线往后挪 竭尽全力为AI云算力交付争取时间",
    "source": "Bitget",
    "source_url": "https://www.bitget.com",
    "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE95QjNCT0J3RXVEZDgzUkF3eVJ4QXRvSEJzUXdWSE5KY3JSMzlpYjJGUkJwZ0p5YnBwbzYzTDNITmdaV0NRZWlYWllpXzgyeUNGNGlhbk92bC1NdzV5VWNYNlk5NW1id9IBa0FVX3lxTFB6NE9XOEhCVE4yc3g4eE9SSjR2RjZVVjV1LS1PR1IwYmh6a3k0bnVGejNBa2IxN3BqYWZnUHdvTkF2bzZIOERWM2xBNjhDRWRJMGY1VTFoZnlWcDRKMldjN2R5VmVCZW9WejZ3?oc=5",
    "published": "2026-01-05",
    "summary": "“英伟达亲儿子”CoreWeave(CRWV.US)把违约红线往后挪 竭尽全力为AI云算力交付争取时间&nbsp;&nbsp;Bitget",
    "full_text": "「“英伟达亲儿子”CoreWeave(CRWV.US)把违约红线往后挪 竭尽全力为AI云算力交付争取时间」\n\n来源：Bitget\n发布日期：2026-01-05\n\n本文由 Google News 聚合自 Bitget。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "“英伟达亲儿子”CoreWeave把违约红线往后挪 竭尽全力为AI云算力交付争取时间",
    "source": "Moomoo",
    "source_url": "https://www.moomoo.com",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNVmYyLWwzQnRKQUY4c25DNldBSVlKeXc0aFVTSy1QTkxSR29QVDJtekRUb2RBV0ZicDc3MUhLTFdpSDV4SnB2bzNqTWtVNlpydlAxY3U2c01pdTBVYWhZYmpnUV9pSlVFb3dBNmdzWXN1dDgtY2lOM2hKMkhfcGROZFA3LTFEUmVHX1BSQklXRVhXbVJkNGlWNkdXSkUzZGtHNVRZLWJZMDREdw?oc=5",
    "published": "2026-01-05",
    "summary": "“英伟达亲儿子”CoreWeave把违约红线往后挪 竭尽全力为AI云算力交付争取时间&nbsp;&nbsp;Moomoo",
    "full_text": "「“英伟达亲儿子”CoreWeave把违约红线往后挪 竭尽全力为AI云算力交付争取时间」\n\n来源：Moomoo\n发布日期：2026-01-05\n\n本文由 Google News 聚合自 Moomoo。点击卡片可跳转到原始文章页面阅读完整内容。\n\n本栏目聚焦 GPU 算力租赁市场动态，涵盖 H100/A100/H200/B200 等 GPU 云租赁价格、CoreWeave/RunPod/Vast.ai/Lambda Labs 等平台定价、以及 GPU 云计算市场的供需变化与成本趋势。",
    "images": [],
    "lang": "zh",
    "title_cn": "",
    "summary_cn": "",
    "translated": false
  },
  {
    "title": "Sold Out Cloud: How GPU Demand Created a New Rental Market",
    "source": "inc.com",
    "source_url": "https://www.inc.com",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxOTGhfczZySFhKUzZhenVJUkhyS3F6a1pEcXhtb09wUVREN01aRkVmNjl6VVFqR3dRaktkS1UwQUZQakJIM1laX0RpYW1saW93WDBMNFRvV0VEOU4tTnBDTWJYSy1BaUV6LWdjZ3VQTmVoenJnanM2VWJxY1V4eUZHZ0FuYzdIT0RhUkxTWngwLTlhSXJ6b2RFZC1uQlVTZFRBRWVCSzFSeXVYQQ?oc=5",
    "published": "2025-12-09",
    "summary": "Sold Out Cloud: How GPU Demand Created a New Rental Market&nbsp;&nbsp;inc.com",
    "full_text": "「云计算已售罄：GPU 需求如何创造新的租赁市场」\n\nSource: inc.com\nPublished: 2025-12-09\n\nOriginal: Sold Out Cloud: How GPU Demand Created a New Rental Market\n\nThis article is aggregated from inc.com via Google News. Click the card to read the full article. The Google News link will redirect you to the original page.\n\nThis section covers GPU compute rental market trends, including H100/A100/H200/B200 cloud pricing, CoreWeave/RunPod/Vast.ai/Lambda Labs rates, and GPU cloud supply-demand dynamics.",
    "images": [],
    "lang": "en",
    "title_cn": "云计算已售罄：GPU 需求如何创造新的租赁市场",
    "summary_cn": "售空云：GPU 需求如何创造新的租赁市场 &nbsp;&nbsp;inc.com",
    "translated": true,
    "full_text_cn": "「云计算已售先：GPU 需求如何创造新的租赁市场」\n\n资料来源：inc.com\n发布时间：2025-12-09\n\n原文：Sold Out Cloud：GPU 需求如何创造新的租赁市场\n\n本文是通过 Google 新闻从 inc.com 汇总的。单击卡片即可阅读全文。 Google 新闻链接会将您重定向到原始页面。\n\n本节涵盖 GPU 计算租赁市场趋势，包括 H100/A100/H200/B200 云定价、CoreWeave/RunPod/Vast.ai/Lambda Labs 费率以及 GPU 云供需动态。"
  }
];
