// GPU 算力新闻 v2
// 生成: 2026-06-12T13:20:13Z
var NEWS_FETCHED_AT = "2026-06-12T13:20:13Z";
var GPU_NEWS = [
  {
    "title": "全球TPU算力赛道爆发！技术革新重塑AI算力产业新格局",
    "source": "雷科技",
    "url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9UdktiSzNrOHBZY3Qxbk1Wblo4bEljYmozXzR0NEN5azd6aE40UXFXS1JlZ3VGNGJTdEljVGpyWnhQSnVieUNMS1owcG80QQ?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Wed, 10 Jun 2026 06:05:43 GMT",
    "summary": "全球TPU算力赛道爆发！技术革新重塑AI算力产业新格局&nbsp;&nbsp;雷科技",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE9UdktiSzNrOHBZY3Qxbk1Wblo4bEljYmozXzR0NEN5azd6aE40UXFXS1JlZ3VGNGJTdEljVGpyWnhQSnVieUNMS1owcG80QQ?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "GPU租金飙涨！高端算力持续紧缺 多只算力租赁概念股获资金青睐",
    "source": "东方财富",
    "url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE1iSmRCNEc1NzduUEhPbnVWSnlReTBMUjIyUXQwUWpTQVdTNF9QblVoMGtBMm5jcG5VY2VZdmJFcmQxVFI3cTdlVi1kRllMZWxOcklWcWlqOW9pMGY2eHNKWlktb1ZPbEU?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Tue, 14 Apr 2026 07:00:00 GMT",
    "summary": "GPU租金飙涨！高端算力持续紧缺 多只算力租赁概念股获资金青睐&nbsp;&nbsp;东方财富",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE1iSmRCNEc1NzduUEhPbnVWSnlReTBMUjIyUXQwUWpTQVdTNF9QblVoMGtBMm5jcG5VY2VZdmJFcmQxVFI3cTdlVi1kRllMZWxOcklWcWlqOW9pMGY2eHNKWlktb1ZPbEU?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "US House moves to extend AI chip export controls to the cloud",
    "source": "eeNews Europe",
    "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNYmYwc3FzclN6c0NTLTlGMUtJS3FBQzJ0Tll6Z21WMG1WM0lQeXBRZ0VBNjBHNVVXMEE0Z2dQMnhBYjl3bzd0MDFFRjdUbEt2Vy04VzFIOE1rbHNmYXRHcHU2TWJqd05GcU1XTjlmSjZxNXg0V1N0WExRRUdvZ3dqYmxtaU5uZkRJd28wNklKR3dZOGs?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Tue, 13 Jan 2026 08:00:00 GMT",
    "summary": "US House moves to extend AI chip export controls to the cloud&nbsp;&nbsp;eeNews Europe",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNYmYwc3FzclN6c0NTLTlGMUtJS3FBQzJ0Tll6Z21WMG1WM0lQeXBRZ0VBNjBHNVVXMEE0Z2dQMnhBYjl3bzd0MDFFRjdUbEt2Vy04VzFIOE1rbHNmYXRHcHU2TWJqd05GcU1XTjlmSjZxNXg0V1N0WExRRUdvZ3dqYmxtaU5uZkRJd28wNklKR3dZOGs?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "美国众议院采取行动将人工智能芯片出口管制扩大到云端",
    "summary_cn": "美国众议院将人工智能芯片出口管制扩大到云端&nbsp;&nbsp;eeNews Europe",
    "full_text_cn": "谷歌新闻",
    "translated": true
  },
  {
    "title": "Congress votes to close China cloud chip export loophole",
    "source": "The Register",
    "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPb0JoLTdnMl9nMUJfWGg1WURJcXEzM3dVYkxaM3dWZFgzNUF4Y0JzbTZRcm5wblk5Sjk0alBfSDlCVm5VelhNRnFUZjNFV3FyOHlraGd0NWhtRDZyblB5bHRDSThfV2VyZVR3ZkdJTjNWY3otZmpLN2Q3VGgtOElqdEsxenBMTjNsQVcza3F3ZGx6MndBeGk2Z08yRDEzYVdvWWtSMlBfSm1URnFnN2IySw?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Tue, 13 Jan 2026 08:00:00 GMT",
    "summary": "Congress votes to close China cloud chip export loophole&nbsp;&nbsp;The Register",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPb0JoLTdnMl9nMUJfWGg1WURJcXEzM3dVYkxaM3dWZFgzNUF4Y0JzbTZRcm5wblk5Sjk0alBfSDlCVm5VelhNRnFUZjNFV3FyOHlraGd0NWhtRDZyblB5bHRDSThfV2VyZVR3ZkdJTjNWY3otZmpLN2Q3VGgtOElqdEsxenBMTjNsQVcza3F3ZGx6MndBeGk2Z08yRDEzYVdvWWtSMlBfSm1URnFnN2IySw?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "国会投票封堵中国云芯片出口漏洞",
    "summary_cn": "国会投票封堵中国云芯片出口漏洞 The Register",
    "full_text_cn": "谷歌新闻",
    "translated": true
  },
  {
    "title": "NVIDIA Blackwell $30K GPU Destroys $300K Cards [2026]",
    "source": "tech-insider.org",
    "url": "https://news.google.com/rss/articles/CBMiZEFVX3lxTE5VRU8yNWtxYXkzVDlLRlk3bGpqNG1PUXJ1UTNaR3V2alNXd3VQZ3VMaGZFbVlHVVZ0cDJEd2hZN3kxRmpuOUNLY0lmT3RwVkpUTHZKOEVia3dOM25tbF9tYTBiY0Q?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Tue, 10 Mar 2026 07:00:00 GMT",
    "summary": "NVIDIA Blackwell $30K GPU Destroys $300K Cards [2026]&nbsp;&nbsp;tech-insider.org",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMiZEFVX3lxTE5VRU8yNWtxYXkzVDlLRlk3bGpqNG1PUXJ1UTNaR3V2alNXd3VQZ3VMaGZFbVlHVVZ0cDJEd2hZN3kxRmpuOUNLY0lmT3RwVkpUTHZKOEVia3dOM25tbF9tYTBiY0Q?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "NVIDIA Blackwell 3 万美元 GPU 摧毁了 30 万美元卡 [2026]",
    "summary_cn": "NVIDIA Blackwell 3 万美元 GPU 摧毁了 30 万美元卡 [2026]&nbsp;&nbsp;tech-insider.org",
    "full_text_cn": "谷歌新闻",
    "translated": true
  },
  {
    "title": "Apple Will Run Advanced AI Model on Nvidia GPUs via Google Cloud, Ditching Private Infrastructure",
    "source": "24/7 Wall St.",
    "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQVXZqR2FKSlM5V21HUUt2X0NUNEFvN19YVkIxR3hNVFBvbGxmYVV2N0FIejIyemJ2MFNoQzhoTkF0Z19HR1lLTU1hWkpCMTRhaEE4OFc4QlRIODg2OW94aGNzNDNBa1ZJRUNYaC1SLWVpdUFLbE1uclhkVERfR2FsMHpPc2hISFhhMkJWd3pNLVZ1RWx4YVo0UVdmbTJaZWM0Y0hkcDA3d0x5VTNqbHF5NF90ZHduSG01bDhvQ24wWWs2cmc1b3hPOFl1SF9ZUkh2ZF9ycnhKSQ?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Tue, 09 Jun 2026 22:26:00 GMT",
    "summary": "Apple Will Run Advanced AI Model on Nvidia GPUs via Google Cloud, Ditching Private Infrastructure&nbsp;&nbsp;24/7 Wall St.",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQVXZqR2FKSlM5V21HUUt2X0NUNEFvN19YVkIxR3hNVFBvbGxmYVV2N0FIejIyemJ2MFNoQzhoTkF0Z19HR1lLTU1hWkpCMTRhaEE4OFc4QlRIODg2OW94aGNzNDNBa1ZJRUNYaC1SLWVpdUFLbE1uclhkVERfR2FsMHpPc2hISFhhMkJWd3pNLVZ1RWx4YVo0UVdmbTJaZWM0Y0hkcDA3d0x5VTNqbHF5NF90ZHduSG01bDhvQ24wWWs2cmc1b3hPOFl1SF9ZUkh2ZF9ycnhKSQ?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "苹果将​​通过谷歌云在 Nvidia GPU 上运行高级人工智能模型，放弃私有基础设施",
    "summary_cn": "苹果将​​通过谷歌云在 Nvidia GPU 上运行高级人工智能模型，放弃私有基础设施&nbsp;&nbsp;24/7 Wall St.",
    "full_text_cn": "谷歌新闻",
    "translated": true
  },
  {
    "title": "2026AI算力全产业链全景分析报告",
    "source": "财富号",
    "url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE13UE1qM0V4THZDYjk4bFJOZkpLQ2k3UHoyYUZaTWtoZ1p1QzVHUDNjcXQyZ2lEaGRyY0xnOUdZdGl0VDdiTEt3THd0aHhMSFZyMS02ZDNQcDVqNGo1M2tGNWVhZkdrb2Q2RGdN?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Tue, 09 Jun 2026 06:42:00 GMT",
    "summary": "2026AI算力全产业链全景分析报告&nbsp;&nbsp;财富号",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMia0FVX3lxTE13UE1qM0V4THZDYjk4bFJOZkpLQ2k3UHoyYUZaTWtoZ1p1QzVHUDNjcXQyZ2lEaGRyY0xnOUdZdGl0VDdiTEt3THd0aHhMSFZyMS02ZDNQcDVqNGo1M2tGNWVhZkdrb2Q2RGdN?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "国产算力链弄潮：CPU紧俏、GPU爆发",
    "source": "新浪财经",
    "url": "https://news.google.com/rss/articles/CBMiggVBVV95cUxNTEVLY0ZxZlFLME5PVVpZX1FCYmlGaFEtejdZa0pzSmxxakJ6dzBEOGx1blVYeW1NS09OSWVEeU5kS1JwMnlGOU1QMHA5MmdSNmxUMVE4a2Q0SEtFM3k2OG1PWmZXcU54TGp6MFRtNmpZek5tZ0J0VVZNakNiTXZaNjhxMVpuZGY0eEdzWGxGc2FEdEViMURzV1lRZy1ldGp4VU1mTC02SzZJVEdoRjQtTE1EU2U4V3pwWmR0ajJKS2lhUGVwOFo4VzJ2R2NXT1FVVGpPOW1MdFBETmpmdnBqd1UwNFotM2o3eE5Kal9COF84ZzZNdDFsRmdNa2o2eGdaZFVlTFF4ZTVnZm5ab1FLQ2NjZE14M1h6SG5rNUp6b1FvSEFiNVhLNmMtV2FGY25yZkM3LVRQZDMzMDU3a2hZdHF6SWZMMnJGWWtDVHJMY0lvMzU4ckhCazBETjMwdnhid012RVZCcHh5MmJEdllodmxuTTVHQ0FXOWIwZzJlWlNKTndQbjFvQ3A0dUZjVWI3Z0lTOUFob2ZvRnNRQko5b1B1aHlwWUNWOGJGVVo1b0FxWGFFaVBiZ29mREJPZ2hhZ2JiLVhkaFBoXzRTUGpXT2Vtc1lrRFpPdHllRG9ydGxpZE5HcG1RT3Z0REhvdzlvUVFmZDFvNnNueFJuSmZmNHZwY1RUajhFcTZLS25GakNpYUpXYThyaWZ1Mlhqd3ZEZ1QyOTlpVFhTSjZ3c2hwOXZYZkIwMDFUSTJSOEdSWTVIZnAybWJpUE8xbUxLOUtBR1dtQzEyZHR6ZDdCRndJZGhXTFFPNGlSbENMelI1bGZIc05scG93ODhQSHJFTTBCWGc?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Tue, 09 Jun 2026 03:31:07 GMT",
    "summary": "国产算力链弄潮：CPU紧俏、GPU爆发&nbsp;&nbsp;新浪财经",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiggVBVV95cUxNTEVLY0ZxZlFLME5PVVpZX1FCYmlGaFEtejdZa0pzSmxxakJ6dzBEOGx1blVYeW1NS09OSWVEeU5kS1JwMnlGOU1QMHA5MmdSNmxUMVE4a2Q0SEtFM3k2OG1PWmZXcU54TGp6MFRtNmpZek5tZ0J0VVZNakNiTXZaNjhxMVpuZGY0eEdzWGxGc2FEdEViMURzV1lRZy1ldGp4VU1mTC02SzZJVEdoRjQtTE1EU2U4V3pwWmR0ajJKS2lhUGVwOFo4VzJ2R2NXT1FVVGpPOW1MdFBETmpmdnBqd1UwNFotM2o3eE5Kal9COF84ZzZNdDFsRmdNa2o2eGdaZFVlTFF4ZTVnZm5ab1FLQ2NjZE14M1h6SG5rNUp6b1FvSEFiNVhLNmMtV2FGY25yZkM3LVRQZDMzMDU3a2hZdHF6SWZMMnJGWWtDVHJMY0lvMzU4ckhCazBETjMwdnhid012RVZCcHh5MmJEdllodmxuTTVHQ0FXOWIwZzJlWlNKTndQbjFvQ3A0dUZjVWI3Z0lTOUFob2ZvRnNRQko5b1B1aHlwWUNWOGJGVVo1b0FxWGFFaVBiZ29mREJPZ2hhZ2JiLVhkaFBoXzRTUGpXT2Vtc1lrRFpPdHllRG9ydGxpZE5HcG1RT3Z0REhvdzlvUVFmZDFvNnNueFJuSmZmNHZwY1RUajhFcTZLS25GakNpYUpXYThyaWZ1Mlhqd3ZEZ1QyOTlpVFhTSjZ3c2hwOXZYZkIwMDFUSTJSOEdSWTVIZnAybWJpUE8xbUxLOUtBR1dtQzEyZHR6ZDdCRndJZGhXTFFPNGlSbENMelI1bGZIc05scG93ODhQSHJFTTBCWGc?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "Building Token‑Metered AI Services on Telco AI Factories | NVIDIA Technical Blog",
    "source": "NVIDIA Developer",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxPWF9DdmdtUmFWYzBYbFRjOEZOUkxBcWhwNm85eEw0UkRSeExPMTQyN2l2VzBpVzBSTHBsNjFBNUlVdDdGbjRNRjQ0TnQ5ZFNrMGxaTFFNUUlXR0cwcGc4TzNlVEhjMFZmYTZhR2EtdF84U0lhX0ZPSVRpYkRETjB3SkFlMHgzVGx3YmFxcVFXZkRpMWVLNWc?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Thu, 21 May 2026 07:00:00 GMT",
    "summary": "Building Token‑Metered AI Services on Telco AI Factories | NVIDIA Technical Blog&nbsp;&nbsp;NVIDIA Developer",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxPWF9DdmdtUmFWYzBYbFRjOEZOUkxBcWhwNm85eEw0UkRSeExPMTQyN2l2VzBpVzBSTHBsNjFBNUlVdDdGbjRNRjQ0TnQ5ZFNrMGxaTFFNUUlXR0cwcGc4TzNlVEhjMFZmYTZhR2EtdF84U0lhX0ZPSVRpYkRETjB3SkFlMHgzVGx3YmFxcVFXZkRpMWVLNWc?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "在电信 AI 工厂上构建按代币计量的 AI 服务 | NVIDIA 技术博客",
    "summary_cn": "在电信 AI 工厂上构建按代币计量的 AI 服务 | NVIDIA 技术博客NVIDIA 开发人员",
    "full_text_cn": "谷歌新闻",
    "translated": true
  },
  {
    "title": "高端算力紧缺，英伟达云端GPU租价大涨，天弘中证全指通信设备指数基金(A/C：020899/020900)聚焦算力光模块龙头享红利",
    "source": "新浪财经",
    "url": "https://news.google.com/rss/articles/CBMiuwJBVV95cUxPcU9KNTNNN3JPdWFHbzJtb3ZHWXp1bG1wQ3ROSURmVXNSUEpqODQ1dnNNbEhaVEpfWXdfVGVCXzZEUE94LTJka2dpS0JPaUlpVVVpdm1peGN6RlRaZEt6SERCR2UxTlJYSmRkZDZiNXZHcGNrUmxVOGFDQTRMNFdYa0ZnTGs1cWN5TWVnN1ZLNzhCY1BfMDVTdkhDdEE0Q1pZeWlBeTEyaW5iWTk3dXczbEx5RGhnREFyLUtkMGlnc182elV1YjNfUVRIejdiNUdiRlJpRnZuVWZxZVlQOUlnLXM1dXhtOS1fYU1EVTRJT2RudzJ1bF9kMkY1aDZQQy0xU2RtU25oajczNkNBemFTLWIwTmdZS3VvOVlIdTZNaGZlQnhSVUN4YXBlc0w1eFhRQ1ZtSlZjQXJneDA?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Thu, 11 Jun 2026 19:48:53 GMT",
    "summary": "高端算力紧缺，英伟达云端GPU租价大涨，天弘中证全指通信设备指数基金(A/C：020899/020900)聚焦算力光模块龙头享红利&nbsp;&nbsp;新浪财经",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiuwJBVV95cUxPcU9KNTNNN3JPdWFHbzJtb3ZHWXp1bG1wQ3ROSURmVXNSUEpqODQ1dnNNbEhaVEpfWXdfVGVCXzZEUE94LTJka2dpS0JPaUlpVVVpdm1peGN6RlRaZEt6SERCR2UxTlJYSmRkZDZiNXZHcGNrUmxVOGFDQTRMNFdYa0ZnTGs1cWN5TWVnN1ZLNzhCY1BfMDVTdkhDdEE0Q1pZeWlBeTEyaW5iWTk3dXczbEx5RGhnREFyLUtkMGlnc182elV1YjNfUVRIejdiNUdiRlJpRnZuVWZxZVlQOUlnLXM1dXhtOS1fYU1EVTRJT2RudzJ1bF9kMkY1aDZQQy0xU2RtU25oajczNkNBemFTLWIwTmdZS3VvOVlIdTZNaGZlQnhSVUN4YXBlc0w1eFhRQ1ZtSlZjQXJneDA?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "云天畅想茅晓东：AI算力市场将增十万倍达百万亿级|连线创始人",
    "source": "电子工程专辑",
    "url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFBlZzlabFVwMWQzQ2ItZEJjQkZIdU9vcWNQbnJGT2VUR29XaUpPa1RSXzY5S2ZXek93U3h0UnFfUUhNUHF0NndmVEEzLVctWVRmQ1lr?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Thu, 11 Jun 2026 13:12:00 GMT",
    "summary": "云天畅想茅晓东：AI算力市场将增十万倍达百万亿级|连线创始人&nbsp;&nbsp;电子工程专辑",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiU0FVX3lxTFBlZzlabFVwMWQzQ2ItZEJjQkZIdU9vcWNQbnJGT2VUR29XaUpPa1RSXzY5S2ZXek93U3h0UnFfUUhNUHF0NndmVEEzLVctWVRmQ1lr?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "ClusterMAX™ 2.0: The Industry Standard GPU Cloud Rating System",
    "source": "SemiAnalysis",
    "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFB3X1hlQlRUcGh0aE1yVEVIOEYzdGdJRW03NVNhX0hxOTUxemU4WTMwcW1fRVViSEVfRzVkMmptTi02T0JtTjVzQ0NXQVRXc1lnOVMzckp4WHNYRGVZRlRvclNsSkV6bkZIUUxMM01wVHFUcE5uUU9TTng2UVl1Zw?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Thu, 06 Nov 2025 08:00:00 GMT",
    "summary": "ClusterMAX™ 2.0: The Industry Standard GPU Cloud Rating System&nbsp;&nbsp;SemiAnalysis",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMifkFVX3lxTFB3X1hlQlRUcGh0aE1yVEVIOEYzdGdJRW03NVNhX0hxOTUxemU4WTMwcW1fRVViSEVfRzVkMmptTi02T0JtTjVzQ0NXQVRXc1lnOVMzckp4WHNYRGVZRlRvclNsSkV6bkZIUUxMM01wVHFUcE5uUU9TTng2UVl1Zw?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "ClusterMAX™ 2.0：行业标准 GPU 云评级系统",
    "summary_cn": "ClusterMAX™ 2.0：行业标准 GPU 云评级系统&nbsp;&nbsp;SemiAnalysis",
    "full_text_cn": "谷歌新闻",
    "translated": true
  },
  {
    "title": "算力租赁洞察：行业最近发生了什么？算力租赁投资框架拆解",
    "source": "雪球",
    "url": "https://news.google.com/rss/articles/CBMiUEFVX3lxTFBvWTJFdlJzNDhoWmRBMnhHcEYtcjBTR2R4TDctNGVtQmFzWVM1N2VIb0Q0RmJvc3V4YW5HaERlUWZtUEh2TGhpeGRqaVFlWDFq?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Sun, 24 May 2026 07:00:00 GMT",
    "summary": "算力租赁洞察：行业最近发生了什么？算力租赁投资框架拆解&nbsp;&nbsp;雪球",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiUEFVX3lxTFBvWTJFdlJzNDhoWmRBMnhHcEYtcjBTR2R4TDctNGVtQmFzWVM1N2VIb0Q0RmJvc3V4YW5HaERlUWZtUEh2TGhpeGRqaVFlWDFq?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "谷歌携手SpaceX达成算力合作 租赁11万颗英伟达GPU",
    "source": "驱动之家",
    "url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE8yY2wyRzUzSzM2UjRzeXdhWGIxdGhDVFQ0MmNkbFNSUzJPUmlIMmFIMHlUS3FpR2w5X01BWV8yV0l5Q2JmaF9hUjlwcXhwN3ZlS0puRVpvd1c?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Sun, 07 Jun 2026 11:11:00 GMT",
    "summary": "谷歌携手SpaceX达成算力合作 租赁11万颗英伟达GPU&nbsp;&nbsp;驱动之家",
    "lang": "zh",
    "source_url": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE8yY2wyRzUzSzM2UjRzeXdhWGIxdGhDVFQ0MmNkbFNSUzJPUmlIMmFIMHlUS3FpR2w5X01BWV8yV0l5Q2JmaF9hUjlwcXhwN3ZlS0puRVpvd1c?oc=5",
    "full_text": "Google News",
    "images": []
  },
  {
    "title": "Chinese AI developers explore renting Nvidia’s Rubin GPU in the cloud — cost, complexity, and regulatory hurdles could limit deployments",
    "source": "Tom's Hardware",
    "url": "https://news.google.com/rss/articles/CBMipAJBVV95cUxNVUt0WHB6VDZKRXJnT0xDWVZvY210ZEMtUDllOTdjR1dnaGNrNzFYYzUzaFFWbGQ5TWNHTzRJaFVFN0I4eGNpYzNwRUtIalN1OTYydHhRMDNGN0FBR09pcXZfWjR3LTZwTWdROXFIN2ZJeWlWNW03X09LdE1ULVlFbk94elZHYkM4WHlwZUF6d05RVG1LUHhPTVNMcUFWWU9kRUtKd2prNjdaSmRQVENwLWdOS1o3ZUk3SUhMaXRaeWdHYVVrMXp4WG4zNDhSbjk3N3N6MDFTdGRHTlFMMUsxNmY1SURqMFM1NU9XbFp2NENkbV94OEU2aHQ0Q3lid1JCNER0WGpPY1I5dDhuVUZkTHhFSjh0d0ZEU2pKMlE2Z2YtMUJD?oc=5&hl=en-US&gl=US&ceid=US:en",
    "published": "Sat, 17 Jan 2026 08:00:00 GMT",
    "summary": "Chinese AI developers explore renting Nvidia’s Rubin GPU in the cloud — cost, complexity, and regulatory hurdles could limit deployments&nbsp;&nbsp;Tom's Hardware",
    "lang": "en",
    "source_url": "https://news.google.com/rss/articles/CBMipAJBVV95cUxNVUt0WHB6VDZKRXJnT0xDWVZvY210ZEMtUDllOTdjR1dnaGNrNzFYYzUzaFFWbGQ5TWNHTzRJaFVFN0I4eGNpYzNwRUtIalN1OTYydHhRMDNGN0FBR09pcXZfWjR3LTZwTWdROXFIN2ZJeWlWNW03X09LdE1ULVlFbk94elZHYkM4WHlwZUF6d05RVG1LUHhPTVNMcUFWWU9kRUtKd2prNjdaSmRQVENwLWdOS1o3ZUk3SUhMaXRaeWdHYVVrMXp4WG4zNDhSbjk3N3N6MDFTdGRHTlFMMUsxNmY1SURqMFM1NU9XbFp2NENkbV94OEU2aHQ0Q3lid1JCNER0WGpPY1I5dDhuVUZkTHhFSjh0d0ZEU2pKMlE2Z2YtMUJD?oc=5",
    "full_text": "Google News",
    "images": [],
    "title_cn": "中国人工智能开发人员探索在云端租用 Nvidia Rubin GPU——成本、复杂性和监管障碍可能会限制部署",
    "summary_cn": "中国人工智能开发人员探索在云端租用 Nvidia Rubin GPU——成本、复杂性和监管障碍可能会限制部署 Tom's Hardware",
    "full_text_cn": "谷歌新闻",
    "translated": true
  }
];
